/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Core.ReadNLearnForm.VLessonsModules;

import Core.Actions.ButtonActions;
import Utilities.MusicPlayer;

import javax.swing.*;
import java.awt.*;

/**
 * @author Marc
 */
public class Vowels extends javax.swing.JPanel {

    //    Methods creates a hand cursor for the labels
    private void setHandCursor(JLabel... labels) {
        for (JLabel label : labels) {
            label.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }

    private MusicPlayer musicPlayer;

    /**
     * Creates new form Vowel
     */
    public Vowels() {
        initComponents();

        setHandCursor(AaLabel, EeLabel, IiLabel, OoLabel, UuLabel);
    }

    public void setMusicPlayer(MusicPlayer musicPlayer) {
        this.musicPlayer = musicPlayer;
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AaLabel = new javax.swing.JLabel();
        EeLabel = new javax.swing.JLabel();
        IiLabel = new javax.swing.JLabel();
        OoLabel = new javax.swing.JLabel();
        UuLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1520, 880));
        setMinimumSize(new java.awt.Dimension(1520, 880));
        setPreferredSize(new java.awt.Dimension(1520, 880));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AaLabel.setBackground(new java.awt.Color(255, 51, 51));
        AaLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        AaLabel.setForeground(new java.awt.Color(255, 255, 255));
        AaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alphabet letters/Vowels/Aa.png"))); // NOI18N
        AaLabel.setText("/eɪ/ A for apple");
        AaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AaLabelMouseClicked(evt);
            }
        });
        add(AaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        EeLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        EeLabel.setForeground(new java.awt.Color(255, 255, 255));
        EeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alphabet letters/Vowels/Ee.png"))); // NOI18N
        EeLabel.setText("/i:/ E for egg");
        EeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EeLabelMouseClicked(evt);
            }
        });
        add(EeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 270, -1, -1));

        IiLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        IiLabel.setForeground(new java.awt.Color(255, 255, 255));
        IiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alphabet letters/Vowels/Ii.png"))); // NOI18N
        IiLabel.setText("/aɪ/ I for iguana");
        IiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IiLabelMouseClicked(evt);
            }
        });
        add(IiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        OoLabel.setBackground(new java.awt.Color(255, 255, 255));
        OoLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        OoLabel.setForeground(new java.awt.Color(255, 255, 255));
        OoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alphabet letters/Vowels/Oo.png"))); // NOI18N
        OoLabel.setText("/əʊ/ O for octopus");
        OoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OoLabelMouseClicked(evt);
            }
        });
        add(OoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 600, 530, -1));

        UuLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        UuLabel.setForeground(new java.awt.Color(255, 255, 255));
        UuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alphabet letters/Vowels/Uu.png"))); // NOI18N
        UuLabel.setText("/ju:/ U for umbrella");
        UuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UuLabelMouseClicked(evt);
            }
        });
        add(UuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Layout__200_x_150_px_-removebg-preview.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 650, 200, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Layout__200_x_150_px_-removebg-preview.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 320, 200, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Layout__200_x_150_px_-removebg-preview.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 220, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Layout__200_x_150_px_-removebg-preview.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 200, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Layout__200_x_150_px_-removebg-preview.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 450, 210, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vowels__Wood_-removebg-preview.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, -150, 600, 510));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pAGOD NA KO.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -1550, 2200, 2450));
    }// </editor-fold>//GEN-END:initComponents

    String[] vowels = {"Aa", "Ee", "Ii", "Oo", "Uu"};
    int[] vowelsDurationInSeconds = {21, 21, 18, 20, 19};

    private void AaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AaLabelMouseClicked
        // TODO add your handling code here:
        ButtonActions.playVideoLesson(vowelsDurationInSeconds[0], vowels[0], true, musicPlayer);
    }//GEN-LAST:event_AaLabelMouseClicked


    private void EeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EeLabelMouseClicked
        // TODO add your handling code here:
        ButtonActions.playVideoLesson(vowelsDurationInSeconds[1], vowels[1], true, musicPlayer);
    }//GEN-LAST:event_EeLabelMouseClicked

    private void IiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IiLabelMouseClicked
        // TODO add your handling code here:
        ButtonActions.playVideoLesson(vowelsDurationInSeconds[2], vowels[2], true, musicPlayer);
    }//GEN-LAST:event_IiLabelMouseClicked

    private void OoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OoLabelMouseClicked
        // TODO add your handling code here:
        ButtonActions.playVideoLesson(vowelsDurationInSeconds[3], vowels[3], true, musicPlayer);
    }//GEN-LAST:event_OoLabelMouseClicked

    private void UuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UuLabelMouseClicked
        // TODO add your handling code here:
        ButtonActions.playVideoLesson(vowelsDurationInSeconds[4], vowels[4], true, musicPlayer);
    }//GEN-LAST:event_UuLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AaLabel;
    private javax.swing.JLabel EeLabel;
    private javax.swing.JLabel IiLabel;
    private javax.swing.JLabel OoLabel;
    private javax.swing.JLabel UuLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
