/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Core.ReadNLearnForm.VLessonsModules;

import Core.Actions.ButtonActions;

import javax.swing.*;
import java.awt.*;

/**
 * @author Marc
 */
public class Vowels extends javax.swing.JPanel {

    //    Methods creates a hand cursor for the labels
    private void setHandCursor(JLabel... labels) {
        for (JLabel label : labels) {
            label.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }

    /**
     * Creates new form Vowel
     */
    public Vowels() {
        initComponents();

        setHandCursor(AaLabel, EeLabel, IiLabel, OoLabel);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                AaLabel = new javax.swing.JLabel();
                EeLabel = new javax.swing.JLabel();
                IiLabel = new javax.swing.JLabel();
                OoLabel = new javax.swing.JLabel();
                UuLabel = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();

                AaLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                AaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alphabet letters/Vowels/Aa.png"))); // NOI18N
                AaLabel.setText("/eɪ/ A for apple");
                AaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                AaLabelMouseClicked(evt);
                        }
                });

                EeLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                EeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alphabet letters/Vowels/Ee.png"))); // NOI18N
                EeLabel.setText("/i:/ E for egg");
                EeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                EeLabelMouseClicked(evt);
                        }
                });

                IiLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                IiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alphabet letters/Vowels/Ii.png"))); // NOI18N
                IiLabel.setText("/aɪ/ I for iguana");
                IiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                IiLabelMouseClicked(evt);
                        }
                });

                OoLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                OoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alphabet letters/Vowels/Oo.png"))); // NOI18N
                OoLabel.setText("/əʊ/ O for octopus");
                OoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                OoLabelMouseClicked(evt);
                        }
                });

                UuLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                UuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alphabet letters/Vowels/Uu.png"))); // NOI18N
                UuLabel.setText("/ju:/ U for umbrella");
                UuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                UuLabelMouseClicked(evt);
                        }
                });

                jLabel1.setFont(new java.awt.Font("Dialog", 1, 50)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Vowels");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(313, 313, 313)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(IiLabel)
                                                        .addComponent(AaLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(EeLabel)
                                                        .addComponent(OoLabel)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(257, 257, 257)
                                                .addComponent(UuLabel)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AaLabel)
                                        .addComponent(EeLabel))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(OoLabel)
                                        .addComponent(IiLabel))
                                .addGap(18, 18, 18)
                                .addComponent(UuLabel)
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents

    String[] vowels = {"Aa", "Ee", "Ii", "Oo", "Uu"};
    int[] vowelsDurationInSeconds = {21, 21, 18, 20, 19};

    private void AaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AaLabelMouseClicked
        // TODO add your handling code here:
        ButtonActions.playVideoLesson(vowelsDurationInSeconds[0], vowels[0], true);
    }//GEN-LAST:event_AaLabelMouseClicked


    private void EeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EeLabelMouseClicked
        // TODO add your handling code here:
        ButtonActions.playVideoLesson(vowelsDurationInSeconds[1], vowels[1], true);
    }//GEN-LAST:event_EeLabelMouseClicked

    private void IiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IiLabelMouseClicked
        // TODO add your handling code here:
        ButtonActions.playVideoLesson(vowelsDurationInSeconds[2], vowels[2], true);
    }//GEN-LAST:event_IiLabelMouseClicked

    private void OoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OoLabelMouseClicked
        // TODO add your handling code here:
        ButtonActions.playVideoLesson(vowelsDurationInSeconds[3], vowels[3], true);
    }//GEN-LAST:event_OoLabelMouseClicked

    private void UuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UuLabelMouseClicked
        // TODO add your handling code here:
        ButtonActions.playVideoLesson(vowelsDurationInSeconds[4], vowels[4], true);
    }//GEN-LAST:event_UuLabelMouseClicked


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel AaLabel;
        private javax.swing.JLabel EeLabel;
        private javax.swing.JLabel IiLabel;
        private javax.swing.JLabel OoLabel;
        private javax.swing.JLabel UuLabel;
        private javax.swing.JLabel jLabel1;
        // End of variables declaration//GEN-END:variables
}
