/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Core.AssessmentPage;

import Core.Actions.ButtonActions;
import Core.Assessment;

import javax.swing.*;
import java.awt.*;

/**
 * @author Marc
 */
public class OralAssessment extends javax.swing.JFrame {

    public OralAssessment() {
        initComponents();

        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/Assessment/Oral Assessment/WetNet.png"));
        Image originalImage = originalIcon.getImage();
        Image scaledImage = originalImage.getScaledInstance(iconT1.getWidth(), iconT1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        iconT1.setIcon(scaledIcon);

        ImageIcon originalIconT2 = new ImageIcon(getClass().getResource("/Assessment/Oral Assessment/CatMat.png"));
        Image originalImageT2 = originalIconT2.getImage();
        Image scaledImageT2 = originalImageT2.getScaledInstance(iconT2.getWidth(), iconT2.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconT2 = new ImageIcon(scaledImageT2);
        iconT2.setIcon(scaledIconT2);

        ImageIcon originalIconT3 = new ImageIcon(getClass().getResource("/Assessment/Oral Assessment/FishFins.png"));
        Image originalImageT3 = originalIconT3.getImage();
        Image scaledImageT3 = originalImageT3.getScaledInstance(iconT3.getWidth(), iconT3.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconT3 = new ImageIcon(scaledImageT3);
        iconT3.setIcon(scaledIconT3);

        ImageIcon originalIconT4 = new ImageIcon(getClass().getResource("/Assessment/Oral Assessment/Apple.png"));
        Image originalImageT4 = originalIconT4.getImage();
        Image scaledImageT4 = originalImageT4.getScaledInstance(iconT4.getWidth(), iconT4.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconT4 = new ImageIcon(scaledImageT4);
        iconT4.setIcon(scaledIconT4);

        ImageIcon originalIconT5 = new ImageIcon(getClass().getResource("/Assessment/Oral Assessment/CatBox.png"));
        Image originalImageT5 = originalIconT5.getImage();
        Image scaledImageT5 = originalImageT5.getScaledInstance(iconT5.getWidth(), iconT5.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconT5 = new ImageIcon(scaledImageT5);
        iconT5.setIcon(scaledIconT5);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                assessmentTabbedPane = new javax.swing.JTabbedPane();
                q1Panel = new javax.swing.JPanel();
                q1Label = new javax.swing.JLabel();
                directionLabel = new javax.swing.JLabel();
                textArea1 = new javax.swing.JTextArea();
                clearButton1 = new javax.swing.JButton();
                readButton1 = new javax.swing.JButton();
                netWordButton1 = new javax.swing.JButton();
                TheWordButton1 = new javax.swing.JButton();
                wetWordButton1 = new javax.swing.JButton();
                isWordButton1 = new javax.swing.JButton();
                nextButton1 = new javax.swing.JButton();
                textToSpeechToggleButton1 = new javax.swing.JToggleButton();
                jLabel1 = new javax.swing.JLabel();
                returnButton = new javax.swing.JButton();
                iconT1 = new javax.swing.JLabel();
                q2Panel = new javax.swing.JPanel();
                q2Label = new javax.swing.JLabel();
                directionLabel2 = new javax.swing.JLabel();
                textArea2 = new javax.swing.JTextArea();
                clearButton2 = new javax.swing.JButton();
                ReadButton2 = new javax.swing.JButton();
                matWordButton2 = new javax.swing.JButton();
                TheWordButton2 = new javax.swing.JButton();
                isWordButton2 = new javax.swing.JButton();
                onWordButton2 = new javax.swing.JButton();
                nextButton2 = new javax.swing.JButton();
                textToSpeechToggleButton2 = new javax.swing.JToggleButton();
                catWordButton2 = new javax.swing.JButton();
                theWordButton2 = new javax.swing.JButton();
                iconT2 = new javax.swing.JLabel();
                q3Panel = new javax.swing.JPanel();
                q3Label = new javax.swing.JLabel();
                directionLabel3 = new javax.swing.JLabel();
                textArea3 = new javax.swing.JTextArea();
                clearButton3 = new javax.swing.JButton();
                ReadButton3 = new javax.swing.JButton();
                fishWordButton3 = new javax.swing.JButton();
                TheWordButton3 = new javax.swing.JButton();
                bigWordButton3 = new javax.swing.JButton();
                hasWordButton3 = new javax.swing.JButton();
                nextButton3 = new javax.swing.JButton();
                textToSpeechToggleButton3 = new javax.swing.JToggleButton();
                finsWordButton3 = new javax.swing.JButton();
                iconT3 = new javax.swing.JLabel();
                q4Panel = new javax.swing.JPanel();
                q4Label = new javax.swing.JLabel();
                directionLabel4 = new javax.swing.JLabel();
                textArea4 = new javax.swing.JTextArea();
                clearButton4 = new javax.swing.JButton();
                ReadButton4 = new javax.swing.JButton();
                areWordButton4 = new javax.swing.JButton();
                sixWordButton4 = new javax.swing.JButton();
                applesWordButton4 = new javax.swing.JButton();
                ThereWordButton4 = new javax.swing.JButton();
                nextButton4 = new javax.swing.JButton();
                textToSpeechToggleButton4 = new javax.swing.JToggleButton();
                iconT4 = new javax.swing.JLabel();
                q5Panel = new javax.swing.JPanel();
                q4Label1 = new javax.swing.JLabel();
                directionLabel5 = new javax.swing.JLabel();
                textArea5 = new javax.swing.JTextArea();
                clearButton5 = new javax.swing.JButton();
                ReadButton5 = new javax.swing.JButton();
                boxWordButton5 = new javax.swing.JButton();
                isWordButton5 = new javax.swing.JButton();
                TheWordButton5 = new javax.swing.JButton();
                theWordButton5 = new javax.swing.JButton();
                nextButton5 = new javax.swing.JButton();
                textToSpeechToggleButton5 = new javax.swing.JToggleButton();
                catWordButton5 = new javax.swing.JButton();
                onWordButton5 = new javax.swing.JButton();
                returnButton1 = new javax.swing.JButton();
                iconT5 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                q1Panel.setBackground(new java.awt.Color(204, 204, 204));

                q1Label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                q1Label.setForeground(new java.awt.Color(0, 0, 0));
                q1Label.setText("1. What can you say about the net?");

                directionLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                directionLabel.setForeground(new java.awt.Color(0, 0, 0));
                directionLabel.setText("Direction: Describe the picture using the word");

                textArea1.setEditable(false);
                textArea1.setBackground(new java.awt.Color(153, 153, 153));
                textArea1.setColumns(20);
                textArea1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                textArea1.setForeground(new java.awt.Color(0, 0, 0));
                textArea1.setRows(5);

                clearButton1.setText("Clear");
                clearButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButton1ActionPerformed(evt);
                        }
                });

                readButton1.setText("Read");
                readButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButton1ActionPerformed(evt);
                        }
                });

                netWordButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                netWordButton1.setText("net");
                netWordButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                netWordButton1ActionPerformed(evt);
                        }
                });

                TheWordButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                TheWordButton1.setText("The");
                TheWordButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TheWordButton1ActionPerformed(evt);
                        }
                });

                wetWordButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                wetWordButton1.setText("wet");
                wetWordButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                wetWordButton1ActionPerformed(evt);
                        }
                });

                isWordButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                isWordButton1.setText("is");
                isWordButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                isWordButton1ActionPerformed(evt);
                        }
                });

                nextButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                nextButton1.setText("Next");
                nextButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButton1ActionPerformed(evt);
                        }
                });

                textToSpeechToggleButton1.setText("Sound");
                textToSpeechToggleButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textToSpeechToggleButton1ActionPerformed(evt);
                        }
                });

                jLabel1.setText("jLabel1");

                returnButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                returnButton.setText("Return");
                returnButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                returnButtonActionPerformed(evt);
                        }
                });

                iconT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Oral Assessment/WetNet.png"))); // NOI18N
                iconT1.setPreferredSize(new java.awt.Dimension(50, 15));

                javax.swing.GroupLayout q1PanelLayout = new javax.swing.GroupLayout(q1Panel);
                q1Panel.setLayout(q1PanelLayout);
                q1PanelLayout.setHorizontalGroup(
                        q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q1PanelLayout.createSequentialGroup()
                                .addGap(670, 670, 670)
                                .addComponent(textToSpeechToggleButton1))
                        .addGroup(q1PanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(directionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(q1PanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(q1Label))
                        .addGroup(q1PanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(nextButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(q1PanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(iconT1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q1PanelLayout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(clearButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(readButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(q1PanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(wetWordButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(netWordButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(5, 5, 5)
                                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(isWordButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(TheWordButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                );
                q1PanelLayout.setVerticalGroup(
                        q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q1PanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(textToSpeechToggleButton1)
                                .addGap(9, 9, 9)
                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(directionLabel)
                                        .addGroup(q1PanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel1)))
                                .addGap(12, 12, 12)
                                .addComponent(q1Label)
                                .addGap(20, 20, 20)
                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(q1PanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(clearButton1)
                                                .addGap(5, 5, 5)
                                                .addComponent(readButton1)))
                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q1PanelLayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(iconT1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(q1PanelLayout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(q1PanelLayout.createSequentialGroup()
                                                                .addComponent(wetWordButton1)
                                                                .addGap(11, 11, 11)
                                                                .addComponent(netWordButton1))
                                                        .addGroup(q1PanelLayout.createSequentialGroup()
                                                                .addComponent(isWordButton1)
                                                                .addGap(11, 11, 11)
                                                                .addComponent(TheWordButton1)))))
                                .addGap(18, 18, 18)
                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(returnButton)
                                        .addComponent(nextButton1)))
                );

                textArea1.setEditable(false);

                assessmentTabbedPane.addTab("tab1", q1Panel);

                q2Panel.setBackground(new java.awt.Color(204, 204, 204));

                q2Label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                q2Label.setForeground(new java.awt.Color(0, 0, 0));
                q2Label.setText("2. Where is the Cat?");

                directionLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                directionLabel2.setForeground(new java.awt.Color(0, 0, 0));
                directionLabel2.setText("Direction: Describe the picture using the word");

                textArea2.setEditable(false);
                textArea2.setBackground(new java.awt.Color(153, 153, 153));
                textArea2.setColumns(20);
                textArea2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                textArea2.setForeground(new java.awt.Color(0, 0, 0));
                textArea2.setRows(5);

                clearButton2.setText("Clear");
                clearButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButton2ActionPerformed(evt);
                        }
                });

                ReadButton2.setText("Read");
                ReadButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ReadButton2ActionPerformed(evt);
                        }
                });

                matWordButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                matWordButton2.setText("mat");
                matWordButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                matWordButton2ActionPerformed(evt);
                        }
                });

                TheWordButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                TheWordButton2.setText("The");
                TheWordButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TheWordButton2ActionPerformed(evt);
                        }
                });

                isWordButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                isWordButton2.setText("is");
                isWordButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                isWordButton2ActionPerformed(evt);
                        }
                });

                onWordButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                onWordButton2.setText("on");
                onWordButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                onWordButton2ActionPerformed(evt);
                        }
                });

                nextButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                nextButton2.setText("Next");
                nextButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButton2ActionPerformed(evt);
                        }
                });

                textToSpeechToggleButton2.setText("Sound");
                textToSpeechToggleButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textToSpeechToggleButton2ActionPerformed(evt);
                        }
                });

                catWordButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                catWordButton2.setText("cat");
                catWordButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                catWordButton2ActionPerformed(evt);
                        }
                });

                theWordButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                theWordButton2.setText("the");
                theWordButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                theWordButton2ActionPerformed(evt);
                        }
                });

                iconT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Oral Assessment/CatMat.png"))); // NOI18N
                iconT2.setPreferredSize(new java.awt.Dimension(50, 15));

                javax.swing.GroupLayout q2PanelLayout = new javax.swing.GroupLayout(q2Panel);
                q2Panel.setLayout(q2PanelLayout);
                q2PanelLayout.setHorizontalGroup(
                        q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q2PanelLayout.createSequentialGroup()
                                .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q2PanelLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(q2Label)
                                                        .addComponent(directionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(q2PanelLayout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addComponent(iconT2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(q2PanelLayout.createSequentialGroup()
                                                                                        .addComponent(isWordButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(onWordButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(q2PanelLayout.createSequentialGroup()
                                                                                        .addComponent(matWordButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(TheWordButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(clearButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(ReadButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(q2PanelLayout.createSequentialGroup()
                                                                                .addComponent(catWordButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(theWordButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q2PanelLayout.createSequentialGroup()
                                                .addGap(0, 667, Short.MAX_VALUE)
                                                .addComponent(textToSpeechToggleButton2))
                                        .addGroup(q2PanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(nextButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q2PanelLayout.createSequentialGroup()
                                        .addContainerGap(43, Short.MAX_VALUE)
                                        .addComponent(textArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(295, Short.MAX_VALUE)))
                );
                q2PanelLayout.setVerticalGroup(
                        q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q2PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textToSpeechToggleButton2)
                                .addGap(8, 8, 8)
                                .addComponent(directionLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(q2Label)
                                .addGap(31, 31, 31)
                                .addComponent(clearButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ReadButton2)
                                .addGap(29, 29, 29)
                                .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q2PanelLayout.createSequentialGroup()
                                                .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(matWordButton2)
                                                        .addComponent(TheWordButton2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(isWordButton2)
                                                        .addComponent(onWordButton2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(catWordButton2)
                                                        .addComponent(theWordButton2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                                .addComponent(nextButton2))
                                        .addGroup(q2PanelLayout.createSequentialGroup()
                                                .addComponent(iconT2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q2PanelLayout.createSequentialGroup()
                                        .addContainerGap(165, Short.MAX_VALUE)
                                        .addComponent(textArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(279, Short.MAX_VALUE)))
                );

                textArea1.setEditable(false);

                assessmentTabbedPane.addTab("tab2", q2Panel);

                q3Panel.setBackground(new java.awt.Color(204, 204, 204));

                q3Label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                q3Label.setForeground(new java.awt.Color(0, 0, 0));
                q3Label.setText("3. What does the fish have?");

                directionLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                directionLabel3.setForeground(new java.awt.Color(0, 0, 0));
                directionLabel3.setText("Direction: Describe the picture using the word");

                textArea3.setEditable(false);
                textArea3.setBackground(new java.awt.Color(153, 153, 153));
                textArea3.setColumns(20);
                textArea3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                textArea3.setForeground(new java.awt.Color(0, 0, 0));
                textArea3.setRows(5);

                clearButton3.setText("Clear");
                clearButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButton3ActionPerformed(evt);
                        }
                });

                ReadButton3.setText("Read");
                ReadButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ReadButton3ActionPerformed(evt);
                        }
                });

                fishWordButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                fishWordButton3.setText("fish");
                fishWordButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                fishWordButton3ActionPerformed(evt);
                        }
                });

                TheWordButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                TheWordButton3.setText("The");
                TheWordButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TheWordButton3ActionPerformed(evt);
                        }
                });

                bigWordButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                bigWordButton3.setText("big");
                bigWordButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bigWordButton3ActionPerformed(evt);
                        }
                });

                hasWordButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                hasWordButton3.setText("has");
                hasWordButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                hasWordButton3ActionPerformed(evt);
                        }
                });

                nextButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                nextButton3.setText("Next");
                nextButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButton3ActionPerformed(evt);
                        }
                });

                textToSpeechToggleButton3.setText("Sound");
                textToSpeechToggleButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textToSpeechToggleButton3ActionPerformed(evt);
                        }
                });

                finsWordButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                finsWordButton3.setText("fins");
                finsWordButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                finsWordButton3ActionPerformed(evt);
                        }
                });

                iconT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Oral Assessment/FishFins.png"))); // NOI18N
                iconT3.setPreferredSize(new java.awt.Dimension(50, 15));

                javax.swing.GroupLayout q3PanelLayout = new javax.swing.GroupLayout(q3Panel);
                q3Panel.setLayout(q3PanelLayout);
                q3PanelLayout.setHorizontalGroup(
                        q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q3PanelLayout.createSequentialGroup()
                                .addGap(667, 667, 667)
                                .addComponent(textToSpeechToggleButton3))
                        .addGroup(q3PanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(directionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(q3PanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(q3Label))
                        .addGroup(q3PanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(textArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addGroup(q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(clearButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ReadButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(q3PanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(iconT3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q3PanelLayout.createSequentialGroup()
                                                .addComponent(fishWordButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(5, 5, 5)
                                                .addComponent(TheWordButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(q3PanelLayout.createSequentialGroup()
                                                .addComponent(bigWordButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(5, 5, 5)
                                                .addComponent(hasWordButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(q3PanelLayout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(finsWordButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(q3PanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(nextButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                q3PanelLayout.setVerticalGroup(
                        q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q3PanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(textToSpeechToggleButton3)
                                .addGap(8, 8, 8)
                                .addComponent(directionLabel3)
                                .addGap(12, 12, 12)
                                .addComponent(q3Label)
                                .addGap(29, 29, 29)
                                .addGroup(q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q3PanelLayout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(textArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(q3PanelLayout.createSequentialGroup()
                                                .addComponent(clearButton3)
                                                .addGap(5, 5, 5)
                                                .addComponent(ReadButton3)))
                                .addGap(21, 21, 21)
                                .addGroup(q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(iconT3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(q3PanelLayout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(fishWordButton3)
                                                        .addComponent(TheWordButton3))
                                                .addGap(6, 6, 6)
                                                .addGroup(q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(bigWordButton3)
                                                        .addComponent(hasWordButton3)
                                                        .addGroup(q3PanelLayout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addComponent(finsWordButton3)))))
                                .addGap(23, 23, 23)
                                .addComponent(nextButton3))
                );

                textArea1.setEditable(false);

                assessmentTabbedPane.addTab("tab3", q3Panel);

                q4Panel.setBackground(new java.awt.Color(204, 204, 204));

                q4Label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                q4Label.setForeground(new java.awt.Color(0, 0, 0));
                q4Label.setText("4. How many apples are there?");

                directionLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                directionLabel4.setForeground(new java.awt.Color(0, 0, 0));
                directionLabel4.setText("Direction: Describe the picture using the word");

                textArea4.setEditable(false);
                textArea4.setBackground(new java.awt.Color(153, 153, 153));
                textArea4.setColumns(20);
                textArea4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                textArea4.setForeground(new java.awt.Color(0, 0, 0));
                textArea4.setRows(5);

                clearButton4.setText("Clear");
                clearButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButton4ActionPerformed(evt);
                        }
                });

                ReadButton4.setText("Read");
                ReadButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ReadButton4ActionPerformed(evt);
                        }
                });

                areWordButton4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                areWordButton4.setText("are");
                areWordButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                areWordButton4ActionPerformed(evt);
                        }
                });

                sixWordButton4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                sixWordButton4.setText("six");
                sixWordButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                sixWordButton4ActionPerformed(evt);
                        }
                });

                applesWordButton4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                applesWordButton4.setText("apples");
                applesWordButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                applesWordButton4ActionPerformed(evt);
                        }
                });

                ThereWordButton4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                ThereWordButton4.setText("There");
                ThereWordButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ThereWordButton4ActionPerformed(evt);
                        }
                });

                nextButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                nextButton4.setText("Next");
                nextButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButton4ActionPerformed(evt);
                        }
                });

                textToSpeechToggleButton4.setText("Sound");
                textToSpeechToggleButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textToSpeechToggleButton4ActionPerformed(evt);
                        }
                });

                iconT4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Oral Assessment/Apple.png"))); // NOI18N
                iconT4.setPreferredSize(new java.awt.Dimension(50, 15));

                javax.swing.GroupLayout q4PanelLayout = new javax.swing.GroupLayout(q4Panel);
                q4Panel.setLayout(q4PanelLayout);
                q4PanelLayout.setHorizontalGroup(
                        q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q4PanelLayout.createSequentialGroup()
                                .addGap(667, 667, 667)
                                .addComponent(textToSpeechToggleButton4))
                        .addGroup(q4PanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(directionLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(q4PanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(q4Label))
                        .addGroup(q4PanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(textArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(clearButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ReadButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(q4PanelLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(iconT4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(areWordButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(applesWordButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sixWordButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ThereWordButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(q4PanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(nextButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                q4PanelLayout.setVerticalGroup(
                        q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q4PanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(textToSpeechToggleButton4)
                                .addGap(8, 8, 8)
                                .addComponent(directionLabel4)
                                .addGap(12, 12, 12)
                                .addComponent(q4Label)
                                .addGap(19, 19, 19)
                                .addGroup(q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(q4PanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(clearButton4)
                                                .addGap(5, 5, 5)
                                                .addComponent(ReadButton4)))
                                .addGap(14, 14, 14)
                                .addGroup(q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(iconT4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(q4PanelLayout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(q4PanelLayout.createSequentialGroup()
                                                                .addComponent(areWordButton4)
                                                                .addGap(6, 6, 6)
                                                                .addComponent(applesWordButton4))
                                                        .addGroup(q4PanelLayout.createSequentialGroup()
                                                                .addComponent(sixWordButton4)
                                                                .addGap(6, 6, 6)
                                                                .addComponent(ThereWordButton4)))))
                                .addGap(23, 23, 23)
                                .addComponent(nextButton4))
                );

                textArea1.setEditable(false);

                assessmentTabbedPane.addTab("tab4", q4Panel);

                q5Panel.setBackground(new java.awt.Color(204, 204, 204));

                q4Label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                q4Label1.setForeground(new java.awt.Color(0, 0, 0));
                q4Label1.setText("5. What animal is on the box?");

                directionLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                directionLabel5.setForeground(new java.awt.Color(0, 0, 0));
                directionLabel5.setText("Direction: Describe the picture using the word");

                textArea5.setEditable(false);
                textArea5.setBackground(new java.awt.Color(153, 153, 153));
                textArea5.setColumns(20);
                textArea5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                textArea5.setForeground(new java.awt.Color(0, 0, 0));
                textArea5.setRows(5);

                clearButton5.setText("Clear");
                clearButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButton5ActionPerformed(evt);
                        }
                });

                ReadButton5.setText("Read");
                ReadButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ReadButton5ActionPerformed(evt);
                        }
                });

                boxWordButton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                boxWordButton5.setText("box");
                boxWordButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                boxWordButton5ActionPerformed(evt);
                        }
                });

                isWordButton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                isWordButton5.setText("is");
                isWordButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                isWordButton5ActionPerformed(evt);
                        }
                });

                TheWordButton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                TheWordButton5.setText("The");
                TheWordButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TheWordButton5ActionPerformed(evt);
                        }
                });

                theWordButton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                theWordButton5.setText("the");
                theWordButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                theWordButton5ActionPerformed(evt);
                        }
                });

                nextButton5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                nextButton5.setText("Next");
                nextButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButton5ActionPerformed(evt);
                        }
                });

                textToSpeechToggleButton5.setText("Sound");
                textToSpeechToggleButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textToSpeechToggleButton5ActionPerformed(evt);
                        }
                });

                catWordButton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                catWordButton5.setText("cat");
                catWordButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                catWordButton5ActionPerformed(evt);
                        }
                });

                onWordButton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                onWordButton5.setText("on");
                onWordButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                onWordButton5ActionPerformed(evt);
                        }
                });

                returnButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                returnButton1.setText("Exit");
                returnButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                returnButton1ActionPerformed(evt);
                        }
                });

                iconT5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Oral Assessment/CatBox.png"))); // NOI18N
                iconT5.setPreferredSize(new java.awt.Dimension(50, 15));

                javax.swing.GroupLayout q5PanelLayout = new javax.swing.GroupLayout(q5Panel);
                q5Panel.setLayout(q5PanelLayout);
                q5PanelLayout.setHorizontalGroup(
                        q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q5PanelLayout.createSequentialGroup()
                                .addGap(667, 667, 667)
                                .addComponent(textToSpeechToggleButton5))
                        .addGroup(q5PanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(directionLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(q5PanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(q4Label1))
                        .addGroup(q5PanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(textArea5, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(clearButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ReadButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(q5PanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(iconT5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(boxWordButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TheWordButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(onWordButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(isWordButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(theWordButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(catWordButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(q5PanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(returnButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(nextButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                q5PanelLayout.setVerticalGroup(
                        q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q5PanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(textToSpeechToggleButton5)
                                .addGap(8, 8, 8)
                                .addComponent(directionLabel5)
                                .addGap(12, 12, 12)
                                .addComponent(q4Label1)
                                .addGap(19, 19, 19)
                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textArea5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(q5PanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(clearButton5)
                                                .addGap(5, 5, 5)
                                                .addComponent(ReadButton5)))
                                .addGap(19, 19, 19)
                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(iconT5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(q5PanelLayout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(q5PanelLayout.createSequentialGroup()
                                                                .addComponent(boxWordButton5)
                                                                .addGap(6, 6, 6)
                                                                .addComponent(TheWordButton5)
                                                                .addGap(6, 6, 6)
                                                                .addComponent(onWordButton5))
                                                        .addGroup(q5PanelLayout.createSequentialGroup()
                                                                .addComponent(isWordButton5)
                                                                .addGap(6, 6, 6)
                                                                .addComponent(theWordButton5)
                                                                .addGap(6, 6, 6)
                                                                .addComponent(catWordButton5)))))
                                .addGap(23, 23, 23)
                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(returnButton1)
                                        .addComponent(nextButton5)))
                );

                textArea1.setEditable(false);

                assessmentTabbedPane.addTab("tab5", q5Panel);

                getContentPane().add(assessmentTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, -28, 750, 540));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void clearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textArea1);
    }//GEN-LAST:event_clearButton1ActionPerformed

    private void readButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButton1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textArea1);
    }//GEN-LAST:event_readButton1ActionPerformed

    String[] q1Words = {"The", "net", "is", "wet"};
    String[] q2Words = {"The", "cat", "is", "on", "the", "mat"};
    String[] q3Words = {"The", "fish", "has", "big", "fins"};
    String[] q4Words = {"There", "are", "six", "apples"};
    String[] q5Words = {"The", "cat", "is", "on", "the", "box"};


    private void TheWordButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Append the word to the text area
        textArea1.append(q1Words[0] + " ");
        ButtonActions.speak(q1Words[0] + " ", textToSpeechToggleButton1);
    }

    private void wetWordButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wetWordButton1ActionPerformed
        // TODO add your handling code here:
        textArea1.append(q1Words[3] + " ");
        ButtonActions.speak(q1Words[3] + " ", textToSpeechToggleButton1);
    }//GEN-LAST:event_wetWordButton1ActionPerformed

    private void isWordButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isWordButton1ActionPerformed
        // TODO add your handling code here:
        textArea1.append(q1Words[2] + " ");
        ButtonActions.speak(q1Words[2] + " ", textToSpeechToggleButton1);
    }//GEN-LAST:event_isWordButton1ActionPerformed

    private void netWordButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netWordButton1ActionPerformed
        // TODO add your handling code here:
        textArea1.append(q1Words[1] + " ");
        ButtonActions.speak(q1Words[1] + " ", textToSpeechToggleButton1);
    }//GEN-LAST:event_netWordButton1ActionPerformed

    private void nextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton1ActionPerformed
        // TODO add your handling code here:String correctAnswer = "The net is wet";
        String userAnswer = textArea1.getText().trim();
        ButtonActions.checkAnswerAndNext(q1Words, userAnswer, assessmentTabbedPane, textArea1, true);
    }//GEN-LAST:event_nextButton1ActionPerformed

    private void textToSpeechToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textToSpeechToggleButton1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(textToSpeechToggleButton1);
    }//GEN-LAST:event_textToSpeechToggleButton1ActionPerformed

    private void clearButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textArea2);
    }//GEN-LAST:event_clearButton2ActionPerformed

    private void ReadButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadButton2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textArea2);
    }//GEN-LAST:event_ReadButton2ActionPerformed

    private void matWordButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matWordButton2ActionPerformed
        // TODO add your handling code here:
        textArea2.append(q2Words[5] + " ");
        ButtonActions.speak(q2Words[5] + " ", textToSpeechToggleButton2);
    }//GEN-LAST:event_matWordButton2ActionPerformed

    private void TheWordButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheWordButton2ActionPerformed
        // TODO add your handling code here:
        textArea2.append(q2Words[0] + " ");
        ButtonActions.speak(q2Words[0] + " ", textToSpeechToggleButton2);
    }//GEN-LAST:event_TheWordButton2ActionPerformed

    private void isWordButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isWordButton2ActionPerformed
        // TODO add your handling code here:
        textArea2.append(q2Words[2] + " ");
        ButtonActions.speak(q2Words[2] + " ", textToSpeechToggleButton2);
    }//GEN-LAST:event_isWordButton2ActionPerformed

    private void onWordButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onWordButton2ActionPerformed
        // TODO add your handling code here:
        textArea2.append(q2Words[3] + " ");
        ButtonActions.speak(q2Words[3] + " ", textToSpeechToggleButton2);
    }//GEN-LAST:event_onWordButton2ActionPerformed

    private void nextButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton2ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textArea2.getText().trim();
        ButtonActions.checkAnswerAndNext(q2Words, userAnswer, assessmentTabbedPane, textArea2, true);
    }//GEN-LAST:event_nextButton2ActionPerformed

    private void textToSpeechToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textToSpeechToggleButton2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(textToSpeechToggleButton2);
    }//GEN-LAST:event_textToSpeechToggleButton2ActionPerformed

    private void catWordButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catWordButton2ActionPerformed
        // TODO add your handling code here:
        textArea2.append(q2Words[1] + " ");
        ButtonActions.speak(q2Words[1] + " ", textToSpeechToggleButton2);
    }//GEN-LAST:event_catWordButton2ActionPerformed

    private void theWordButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theWordButton2ActionPerformed
        // TODO add your handling code here:
        textArea2.append(q2Words[4] + " ");
        ButtonActions.speak(q2Words[4] + " ", textToSpeechToggleButton2);
    }//GEN-LAST:event_theWordButton2ActionPerformed

    private void clearButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textArea3);
    }//GEN-LAST:event_clearButton3ActionPerformed

    private void ReadButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadButton3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textArea3);
    }//GEN-LAST:event_ReadButton3ActionPerformed

    private void fishWordButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishWordButton3ActionPerformed
        // TODO add your handling code here:
        textArea3.append(q3Words[1] + " ");
        ButtonActions.speak(q3Words[1] + " ", textToSpeechToggleButton3);
    }//GEN-LAST:event_fishWordButton3ActionPerformed

    private void TheWordButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheWordButton3ActionPerformed
        // TODO add your handling code here:
        textArea3.append(q3Words[0] + " ");
        ButtonActions.speak(q3Words[0] + " ", textToSpeechToggleButton3);
    }//GEN-LAST:event_TheWordButton3ActionPerformed

    private void bigWordButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigWordButton3ActionPerformed
        // TODO add your handling code here:
        textArea3.append(q3Words[3] + " ");
        ButtonActions.speak(q3Words[3] + " ", textToSpeechToggleButton3);
    }//GEN-LAST:event_bigWordButton3ActionPerformed

    private void hasWordButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasWordButton3ActionPerformed
        // TODO add your handling code here:
        textArea3.append(q3Words[2] + " ");
        ButtonActions.speak(q3Words[2] + " ", textToSpeechToggleButton3);
    }//GEN-LAST:event_hasWordButton3ActionPerformed

    private void nextButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton3ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textArea3.getText().trim();
        ButtonActions.checkAnswerAndNext(q3Words, userAnswer, assessmentTabbedPane, textArea3, true);
    }//GEN-LAST:event_nextButton3ActionPerformed

    private void textToSpeechToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textToSpeechToggleButton3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(textToSpeechToggleButton3);
    }//GEN-LAST:event_textToSpeechToggleButton3ActionPerformed

    private void finsWordButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finsWordButton3ActionPerformed
        // TODO add your handling code here:
        textArea3.append(q3Words[4] + " ");
        ButtonActions.speak(q3Words[4] + " ", textToSpeechToggleButton3);
    }//GEN-LAST:event_finsWordButton3ActionPerformed

    private void clearButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textArea4);
    }//GEN-LAST:event_clearButton4ActionPerformed

    private void ReadButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadButton4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textArea4);
    }//GEN-LAST:event_ReadButton4ActionPerformed

    private void areWordButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areWordButton4ActionPerformed
        // TODO add your handling code here:
        textArea4.append(q4Words[1] + " ");
        ButtonActions.speak(q4Words[1] + " ", textToSpeechToggleButton4);
    }//GEN-LAST:event_areWordButton4ActionPerformed

    private void sixWordButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixWordButton4ActionPerformed
        // TODO add your handling code here:
        textArea4.append(q4Words[2] + " ");
        ButtonActions.speak(q4Words[2] + " ", textToSpeechToggleButton4);
    }//GEN-LAST:event_sixWordButton4ActionPerformed

    private void applesWordButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applesWordButton4ActionPerformed
        // TODO add your handling code here:
        textArea4.append(q4Words[3] + " ");
        ButtonActions.speak(q4Words[3] + " ", textToSpeechToggleButton4);
    }//GEN-LAST:event_applesWordButton4ActionPerformed

    private void ThereWordButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThereWordButton4ActionPerformed
        // TODO add your handling code here:
        textArea4.append(q4Words[0] + " ");
        ButtonActions.speak(q4Words[0] + " ", textToSpeechToggleButton4);
    }//GEN-LAST:event_ThereWordButton4ActionPerformed

    private void nextButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton4ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textArea4.getText().trim();
        ButtonActions.checkAnswerAndNext(q4Words, userAnswer, assessmentTabbedPane, textArea4, true);
    }//GEN-LAST:event_nextButton4ActionPerformed

    private void textToSpeechToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textToSpeechToggleButton4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(textToSpeechToggleButton4);
    }//GEN-LAST:event_textToSpeechToggleButton4ActionPerformed

    private void clearButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textArea5);
    }//GEN-LAST:event_clearButton5ActionPerformed

    private void ReadButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadButton5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textArea5);
    }//GEN-LAST:event_ReadButton5ActionPerformed

    private void boxWordButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxWordButton5ActionPerformed
        // TODO add your handling code here:
        textArea5.append(q5Words[5] + " ");
        ButtonActions.speak(q5Words[5] + " ", textToSpeechToggleButton5);
    }//GEN-LAST:event_boxWordButton5ActionPerformed

    private void isWordButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isWordButton5ActionPerformed
        // TODO add your handling code here:
        textArea5.append(q5Words[2] + " ");
        ButtonActions.speak(q5Words[2] + " ", textToSpeechToggleButton5);
    }//GEN-LAST:event_isWordButton5ActionPerformed

    private void TheWordButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheWordButton5ActionPerformed
        // TODO add your handling code here:
        textArea5.append(q5Words[0] + " ");
        ButtonActions.speak(q5Words[0] + " ", textToSpeechToggleButton5);
    }//GEN-LAST:event_TheWordButton5ActionPerformed

    private void theWordButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theWordButton5ActionPerformed
        // TODO add your handling code here:
        textArea5.append(q5Words[4] + " ");
        ButtonActions.speak(q5Words[4] + " ", textToSpeechToggleButton5);
    }//GEN-LAST:event_theWordButton5ActionPerformed

    private void nextButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton5ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textArea5.getText().trim();
        ButtonActions.checkAnswerAndNext(q5Words, userAnswer, assessmentTabbedPane, textArea5, true);
    }//GEN-LAST:event_nextButton5ActionPerformed

    private void textToSpeechToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textToSpeechToggleButton5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(textToSpeechToggleButton5);
    }//GEN-LAST:event_textToSpeechToggleButton5ActionPerformed

    private void catWordButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catWordButton5ActionPerformed
        // TODO add your handling code here:
        textArea5.append(q5Words[1] + " ");
        ButtonActions.speak(q5Words[1] + " ", textToSpeechToggleButton5);
    }//GEN-LAST:event_catWordButton5ActionPerformed

    private void onWordButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onWordButton5ActionPerformed
        // TODO add your handling code here:
        textArea5.append(q5Words[3] + " ");
        ButtonActions.speak(q5Words[3] + " ", textToSpeechToggleButton5);
    }//GEN-LAST:event_onWordButton5ActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        Assessment assessment = new Assessment();
        assessment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void returnButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButton1ActionPerformed
        // TODO add your handling code here:
        Assessment assessment = new Assessment();
        assessment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OralAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OralAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OralAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OralAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OralAssessment().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton ReadButton2;
        private javax.swing.JButton ReadButton3;
        private javax.swing.JButton ReadButton4;
        private javax.swing.JButton ReadButton5;
        private javax.swing.JButton TheWordButton1;
        private javax.swing.JButton TheWordButton2;
        private javax.swing.JButton TheWordButton3;
        private javax.swing.JButton TheWordButton5;
        private javax.swing.JButton ThereWordButton4;
        private javax.swing.JButton applesWordButton4;
        private javax.swing.JButton areWordButton4;
        private javax.swing.JTabbedPane assessmentTabbedPane;
        private javax.swing.JButton bigWordButton3;
        private javax.swing.JButton boxWordButton5;
        private javax.swing.JButton catWordButton2;
        private javax.swing.JButton catWordButton5;
        private javax.swing.JButton clearButton1;
        private javax.swing.JButton clearButton2;
        private javax.swing.JButton clearButton3;
        private javax.swing.JButton clearButton4;
        private javax.swing.JButton clearButton5;
        private javax.swing.JLabel directionLabel;
        private javax.swing.JLabel directionLabel2;
        private javax.swing.JLabel directionLabel3;
        private javax.swing.JLabel directionLabel4;
        private javax.swing.JLabel directionLabel5;
        private javax.swing.JButton finsWordButton3;
        private javax.swing.JButton fishWordButton3;
        private javax.swing.JButton hasWordButton3;
        private javax.swing.JLabel iconT1;
        private javax.swing.JLabel iconT2;
        private javax.swing.JLabel iconT3;
        private javax.swing.JLabel iconT4;
        private javax.swing.JLabel iconT5;
        private javax.swing.JButton isWordButton1;
        private javax.swing.JButton isWordButton2;
        private javax.swing.JButton isWordButton5;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JButton matWordButton2;
        private javax.swing.JButton netWordButton1;
        private javax.swing.JButton nextButton1;
        private javax.swing.JButton nextButton2;
        private javax.swing.JButton nextButton3;
        private javax.swing.JButton nextButton4;
        private javax.swing.JButton nextButton5;
        private javax.swing.JButton onWordButton2;
        private javax.swing.JButton onWordButton5;
        private javax.swing.JLabel q1Label;
        private javax.swing.JPanel q1Panel;
        private javax.swing.JLabel q2Label;
        private javax.swing.JPanel q2Panel;
        private javax.swing.JLabel q3Label;
        private javax.swing.JPanel q3Panel;
        private javax.swing.JLabel q4Label;
        private javax.swing.JLabel q4Label1;
        private javax.swing.JPanel q4Panel;
        private javax.swing.JPanel q5Panel;
        private javax.swing.JButton readButton1;
        private javax.swing.JButton returnButton;
        private javax.swing.JButton returnButton1;
        private javax.swing.JButton sixWordButton4;
        private javax.swing.JTextArea textArea1;
        private javax.swing.JTextArea textArea2;
        private javax.swing.JTextArea textArea3;
        private javax.swing.JTextArea textArea4;
        private javax.swing.JTextArea textArea5;
        private javax.swing.JToggleButton textToSpeechToggleButton1;
        private javax.swing.JToggleButton textToSpeechToggleButton2;
        private javax.swing.JToggleButton textToSpeechToggleButton3;
        private javax.swing.JToggleButton textToSpeechToggleButton4;
        private javax.swing.JToggleButton textToSpeechToggleButton5;
        private javax.swing.JButton theWordButton2;
        private javax.swing.JButton theWordButton5;
        private javax.swing.JButton wetWordButton1;
        // End of variables declaration//GEN-END:variables
}