/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Core.AssessmentPage.TakeChallengeModeOfDifficulty;

import Core.Actions.ButtonActions;
import Core.AssessmentPage.TakeChallengeAssessment;

import javax.swing.*;

/**
 * @author Marc
 */
public class EasyTakeChallenge extends javax.swing.JFrame {

    /**
     * Creates new form EasyTakeChallenge
     */
    public EasyTakeChallenge() {
        initComponents();

            ImageIcon originalIcon = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/TIGER.png"));
            ImageIcon icon = new ImageIcon(originalIcon.getImage().getScaledInstance(iconT1.getWidth(), iconT1.getHeight(), java.awt.Image.SCALE_SMOOTH));
            iconT1.setIcon(icon);

            originalIcon = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/CHAIR.png"));
            icon = new ImageIcon(originalIcon.getImage().getScaledInstance(iconT2.getWidth(), iconT2.getHeight(), java.awt.Image.SCALE_SMOOTH));
            iconT2.setIcon(icon);

            originalIcon = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/PHONE.png"));
            icon = new ImageIcon(originalIcon.getImage().getScaledInstance(iconT3.getWidth(), iconT3.getHeight(), java.awt.Image.SCALE_SMOOTH));
            iconT3.setIcon(icon);

            originalIcon = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/ZEBRA.png"));
            icon = new ImageIcon(originalIcon.getImage().getScaledInstance(iconT4.getWidth(), iconT4.getHeight(), java.awt.Image.SCALE_SMOOTH));
            iconT4.setIcon(icon);

            originalIcon = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/TABLE.png"));
            icon = new ImageIcon(originalIcon.getImage().getScaledInstance(iconT5.getWidth(), iconT5.getHeight(), java.awt.Image.SCALE_SMOOTH));
            iconT5.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                takeChallengeJTabbedPane = new javax.swing.JTabbedPane();
                TCtabbedPane1 = new javax.swing.JPanel();
                instructionLabelTC1 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                readButtonTC1 = new javax.swing.JButton();
                clearButtonTC1 = new javax.swing.JButton();
                hintButtonTC1 = new javax.swing.JButton();
                RButtonTC1 = new javax.swing.JButton();
                IButtonTC1 = new javax.swing.JButton();
                TButtonTC1 = new javax.swing.JButton();
                EButtonTC1 = new javax.swing.JButton();
                nextButtonTC1 = new javax.swing.JButton();
                GButtonTC1 = new javax.swing.JButton();
                textAreaTC1 = new javax.swing.JTextArea();
                soundToggleButtonTC1 = new javax.swing.JToggleButton();
                returnButtonTC1 = new javax.swing.JButton();
                iconT1 = new javax.swing.JLabel();
                TCtabbedPane2 = new javax.swing.JPanel();
                instructionLabelTC2 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                readButtonTC2 = new javax.swing.JButton();
                clearButtonTC2 = new javax.swing.JButton();
                hintButtonTC2 = new javax.swing.JButton();
                RButtonTC2 = new javax.swing.JButton();
                CButtonTC2 = new javax.swing.JButton();
                IButtonTC2 = new javax.swing.JButton();
                AButtonTC2 = new javax.swing.JButton();
                nextButtonTC2 = new javax.swing.JButton();
                HButtonTC2 = new javax.swing.JButton();
                textAreaTC2 = new javax.swing.JTextArea();
                soundToggleButtonTC2 = new javax.swing.JToggleButton();
                iconT2 = new javax.swing.JLabel();
                TCtabbedPane3 = new javax.swing.JPanel();
                instructionLabelTC3 = new javax.swing.JLabel();
                jPanel4 = new javax.swing.JPanel();
                readButtonTC3 = new javax.swing.JButton();
                clearButtonTC3 = new javax.swing.JButton();
                hintButtonTC3 = new javax.swing.JButton();
                PButtonTC3 = new javax.swing.JButton();
                HButtonTC3 = new javax.swing.JButton();
                OButtonTC3 = new javax.swing.JButton();
                EButtonTC3 = new javax.swing.JButton();
                nextButtonTC3 = new javax.swing.JButton();
                NButtonTC3 = new javax.swing.JButton();
                textAreaTC3 = new javax.swing.JTextArea();
                soundToggleButtonTC3 = new javax.swing.JToggleButton();
                iconT3 = new javax.swing.JLabel();
                TCtabbedPane4 = new javax.swing.JPanel();
                instructionLabelTC4 = new javax.swing.JLabel();
                jPanel7 = new javax.swing.JPanel();
                readButtonTC4 = new javax.swing.JButton();
                clearButtonTC4 = new javax.swing.JButton();
                hintButtonTC4 = new javax.swing.JButton();
                EButtonTC4 = new javax.swing.JButton();
                BButtonTC4 = new javax.swing.JButton();
                AButtonTC4 = new javax.swing.JButton();
                RButtonTC4 = new javax.swing.JButton();
                nextButtonTC4 = new javax.swing.JButton();
                ZButtonTC4 = new javax.swing.JButton();
                textAreaTC4 = new javax.swing.JTextArea();
                soundToggleButtonTC4 = new javax.swing.JToggleButton();
                iconT4 = new javax.swing.JLabel();
                TCtabbedPane5 = new javax.swing.JPanel();
                instructionLabelTC5 = new javax.swing.JLabel();
                jPanel9 = new javax.swing.JPanel();
                readButtonTC5 = new javax.swing.JButton();
                clearButtonTC5 = new javax.swing.JButton();
                hintButtonTC5 = new javax.swing.JButton();
                EButtonTC5 = new javax.swing.JButton();
                AButtonTC5 = new javax.swing.JButton();
                TButtonTC5 = new javax.swing.JButton();
                LButtonTC5 = new javax.swing.JButton();
                nextButtonTC5 = new javax.swing.JButton();
                BButtonTC5 = new javax.swing.JButton();
                textAreaTC5 = new javax.swing.JTextArea();
                soundToggleButtonTC5 = new javax.swing.JToggleButton();
                returnButtonTC5 = new javax.swing.JButton();
                iconT5 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                TCtabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC1.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC1.setText("Guess the Word");
                TCtabbedPane1.add(instructionLabelTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonTC1.setText("Read");
                readButtonTC1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonTC1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1.add(readButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonTC1.setText("Clear");
                clearButtonTC1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonTC1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1.add(clearButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonTC1.setText("Hint");
                TCtabbedPane1.add(hintButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                RButtonTC1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                RButtonTC1.setText("R");
                RButtonTC1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                RButtonTC1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1.add(RButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 98, 67));

                IButtonTC1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                IButtonTC1.setText("I");
                IButtonTC1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                IButtonTC1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1.add(IButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 98, 67));

                TButtonTC1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                TButtonTC1.setText("T");
                TButtonTC1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TButtonTC1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1.add(TButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 98, 67));

                EButtonTC1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                EButtonTC1.setText("E");
                EButtonTC1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EButtonTC1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1.add(EButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 98, 67));

                nextButtonTC1.setText("Next");
                nextButtonTC1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonTC1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1.add(nextButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                GButtonTC1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                GButtonTC1.setText("G");
                GButtonTC1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                GButtonTC1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1.add(GButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 98, 67));

                textAreaTC1.setEditable(false);
                textAreaTC1.setColumns(20);
                textAreaTC1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaTC1.setRows(5);
                TCtabbedPane1.add(textAreaTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 250, 80));

                soundToggleButtonTC1.setText("Sound");
                soundToggleButtonTC1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonTC1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1.add(soundToggleButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                returnButtonTC1.setText("Return");
                returnButtonTC1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                returnButtonTC1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1.add(returnButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 485, 73, -1));

                iconT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/TIGER.png"))); // NOI18N
                iconT1.setPreferredSize(new java.awt.Dimension(50, 15));
                TCtabbedPane1.add(iconT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

                takeChallengeJTabbedPane.addTab("tab1", TCtabbedPane1);

                TCtabbedPane2.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC2.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC2.setText("Guess the Word");
                TCtabbedPane2.add(instructionLabelTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonTC2.setText("Read");
                readButtonTC2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonTC2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2.add(readButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonTC2.setText("Clear");
                clearButtonTC2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonTC2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2.add(clearButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonTC2.setText("Hint");
                TCtabbedPane2.add(hintButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                RButtonTC2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                RButtonTC2.setText("R");
                RButtonTC2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                RButtonTC2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2.add(RButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 98, 67));

                CButtonTC2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                CButtonTC2.setText("C");
                CButtonTC2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CButtonTC2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2.add(CButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 98, 67));

                IButtonTC2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                IButtonTC2.setText("I");
                IButtonTC2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                IButtonTC2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2.add(IButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 98, 67));

                AButtonTC2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                AButtonTC2.setText("A");
                AButtonTC2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AButtonTC2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2.add(AButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 98, 67));

                nextButtonTC2.setText("Next");
                nextButtonTC2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonTC2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2.add(nextButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                HButtonTC2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                HButtonTC2.setText("H");
                HButtonTC2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                HButtonTC2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2.add(HButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 98, 67));

                textAreaTC2.setEditable(false);
                textAreaTC2.setColumns(20);
                textAreaTC2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaTC2.setRows(5);
                TCtabbedPane2.add(textAreaTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 240, 80));

                soundToggleButtonTC2.setText("Sound");
                soundToggleButtonTC2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonTC2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2.add(soundToggleButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                iconT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/CHAIR.png"))); // NOI18N
                iconT2.setPreferredSize(new java.awt.Dimension(50, 15));
                TCtabbedPane2.add(iconT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

                takeChallengeJTabbedPane.addTab("tab2", TCtabbedPane2);

                TCtabbedPane3.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC3.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC3.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC3.setText("Guess the Word");
                TCtabbedPane3.add(instructionLabelTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonTC3.setText("Read");
                readButtonTC3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonTC3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3.add(readButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonTC3.setText("Clear");
                clearButtonTC3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonTC3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3.add(clearButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonTC3.setText("Hint");
                TCtabbedPane3.add(hintButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                PButtonTC3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                PButtonTC3.setText("P");
                PButtonTC3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                PButtonTC3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3.add(PButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 98, 67));

                HButtonTC3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                HButtonTC3.setText("H");
                HButtonTC3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                HButtonTC3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3.add(HButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 98, 67));

                OButtonTC3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                OButtonTC3.setText("O");
                OButtonTC3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                OButtonTC3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3.add(OButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 98, 67));

                EButtonTC3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                EButtonTC3.setText("E");
                EButtonTC3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EButtonTC3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3.add(EButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 98, 67));

                nextButtonTC3.setText("Next");
                nextButtonTC3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonTC3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3.add(nextButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                NButtonTC3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                NButtonTC3.setText("N");
                NButtonTC3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                NButtonTC3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3.add(NButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 98, 67));

                textAreaTC3.setEditable(false);
                textAreaTC3.setColumns(20);
                textAreaTC3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaTC3.setRows(5);
                TCtabbedPane3.add(textAreaTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 240, 70));

                soundToggleButtonTC3.setText("Sound");
                soundToggleButtonTC3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonTC3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3.add(soundToggleButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                iconT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/PHONE.png"))); // NOI18N
                iconT3.setPreferredSize(new java.awt.Dimension(50, 15));
                TCtabbedPane3.add(iconT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 439, 209));

                takeChallengeJTabbedPane.addTab("tab3", TCtabbedPane3);

                TCtabbedPane4.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC4.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC4.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC4.setText("Guess the Word");
                TCtabbedPane4.add(instructionLabelTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel7Layout.setVerticalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonTC4.setText("Read");
                readButtonTC4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonTC4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4.add(readButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonTC4.setText("Clear");
                clearButtonTC4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonTC4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4.add(clearButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonTC4.setText("Hint");
                TCtabbedPane4.add(hintButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                EButtonTC4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                EButtonTC4.setText("E");
                EButtonTC4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EButtonTC4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4.add(EButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 98, 67));

                BButtonTC4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                BButtonTC4.setText("B");
                BButtonTC4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BButtonTC4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4.add(BButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 98, 67));

                AButtonTC4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                AButtonTC4.setText("A");
                AButtonTC4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AButtonTC4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4.add(AButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 98, 67));

                RButtonTC4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                RButtonTC4.setText("R");
                RButtonTC4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                RButtonTC4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4.add(RButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 98, 67));

                nextButtonTC4.setText("Next");
                nextButtonTC4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonTC4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4.add(nextButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                ZButtonTC4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                ZButtonTC4.setText("Z");
                ZButtonTC4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ZButtonTC4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4.add(ZButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 98, 67));

                textAreaTC4.setEditable(false);
                textAreaTC4.setColumns(20);
                textAreaTC4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaTC4.setRows(5);
                TCtabbedPane4.add(textAreaTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 240, 70));

                soundToggleButtonTC4.setText("Sound");
                soundToggleButtonTC4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonTC4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4.add(soundToggleButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                iconT4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/ZEBRA.png"))); // NOI18N
                iconT4.setPreferredSize(new java.awt.Dimension(50, 15));
                TCtabbedPane4.add(iconT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 439, 209));

                takeChallengeJTabbedPane.addTab("tab4", TCtabbedPane4);

                TCtabbedPane5.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC5.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC5.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC5.setText("Guess the Word");
                TCtabbedPane5.add(instructionLabelTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
                jPanel9.setLayout(jPanel9Layout);
                jPanel9Layout.setHorizontalGroup(
                        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel9Layout.setVerticalGroup(
                        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonTC5.setText("Read");
                readButtonTC5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonTC5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5.add(readButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonTC5.setText("Clear");
                clearButtonTC5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonTC5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5.add(clearButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonTC5.setText("Hint");
                TCtabbedPane5.add(hintButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                EButtonTC5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                EButtonTC5.setText("E");
                EButtonTC5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EButtonTC5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5.add(EButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 98, 67));

                AButtonTC5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                AButtonTC5.setText("A");
                AButtonTC5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AButtonTC5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5.add(AButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 98, 67));

                TButtonTC5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                TButtonTC5.setText("T");
                TButtonTC5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TButtonTC5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5.add(TButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 98, 67));

                LButtonTC5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                LButtonTC5.setText("L");
                LButtonTC5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LButtonTC5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5.add(LButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 98, 67));

                nextButtonTC5.setText("Next");
                nextButtonTC5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonTC5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5.add(nextButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                BButtonTC5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                BButtonTC5.setText("B");
                BButtonTC5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BButtonTC5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5.add(BButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 98, 67));

                textAreaTC5.setEditable(false);
                textAreaTC5.setColumns(20);
                textAreaTC5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaTC5.setRows(5);
                TCtabbedPane5.add(textAreaTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 240, 70));

                soundToggleButtonTC5.setText("Sound");
                soundToggleButtonTC5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonTC5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5.add(soundToggleButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                returnButtonTC5.setText("Return");
                returnButtonTC5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                returnButtonTC5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5.add(returnButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 485, 73, -1));

                iconT5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/TABLE.png"))); // NOI18N
                iconT5.setPreferredSize(new java.awt.Dimension(50, 15));
                TCtabbedPane5.add(iconT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 439, 209));

                takeChallengeJTabbedPane.addTab("tab5", TCtabbedPane5);

                getContentPane().add(takeChallengeJTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, -30, 780, 590));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    String[] word1 = {"T", "I", "G", "E", "R"};
    String[] word2 = {"C", "H", "A", "I", "R"};
    String[] word3 = {"P", "H", "O", "N", "E"};
    String[] word4 = {"Z", "E", "B", "R", "A"};
    String[] word5 = {"T", "A", "B", "L", "E"};

    private void GButtonTC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GButtonTC1ActionPerformed
        // TODO add your handling code here:
        textAreaTC1.append(word1[2]);
        ButtonActions.speak(word1[2], soundToggleButtonTC1);
    }//GEN-LAST:event_GButtonTC1ActionPerformed

    private void IButtonTC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IButtonTC1ActionPerformed
        // TODO add your handling code here:
        textAreaTC1.append(word1[1]);
        ButtonActions.speak(word1[1], soundToggleButtonTC1);
    }//GEN-LAST:event_IButtonTC1ActionPerformed

    private void EButtonTC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonTC1ActionPerformed
        // TODO add your handling code here:
        textAreaTC1.append(word1[3]);
        ButtonActions.speak(word1[3], soundToggleButtonTC1);
    }//GEN-LAST:event_EButtonTC1ActionPerformed

    private void RButtonTC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonTC1ActionPerformed
        // TODO add your handling code here:
        textAreaTC1.append(word1[4]);
        ButtonActions.speak(word1[4], soundToggleButtonTC1);
    }//GEN-LAST:event_RButtonTC1ActionPerformed

    private void soundToggleButtonTC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonTC1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonTC1);
    }//GEN-LAST:event_soundToggleButtonTC1ActionPerformed

    private void clearButtonTC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonTC1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaTC1);
    }//GEN-LAST:event_clearButtonTC1ActionPerformed

    private void readButtonTC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonTC1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaTC1);
    }//GEN-LAST:event_readButtonTC1ActionPerformed

    private void nextButtonTC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonTC1ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaTC1.getText().trim();
        ButtonActions.checkAnswerAndNext(word1, userAnswer, takeChallengeJTabbedPane, textAreaTC1, false);
    }//GEN-LAST:event_nextButtonTC1ActionPerformed

    private void TButtonTC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TButtonTC1ActionPerformed
        // TODO add your handling code here:
        textAreaTC1.append(word1[0]);
        ButtonActions.speak(word1[0], soundToggleButtonTC1);
    }//GEN-LAST:event_TButtonTC1ActionPerformed

    private void readButtonTC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonTC2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaTC2);
    }//GEN-LAST:event_readButtonTC2ActionPerformed

    private void clearButtonTC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonTC2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaTC2);
    }//GEN-LAST:event_clearButtonTC2ActionPerformed

    private void RButtonTC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonTC2ActionPerformed
        // TODO add your handling code here:
        textAreaTC2.append(word2[4]);
        ButtonActions.speak(word2[4], soundToggleButtonTC2);
    }//GEN-LAST:event_RButtonTC2ActionPerformed

    private void CButtonTC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CButtonTC2ActionPerformed
        // TODO add your handling code here:
        textAreaTC2.append(word2[0]);
        ButtonActions.speak(word2[0], soundToggleButtonTC2);
    }//GEN-LAST:event_CButtonTC2ActionPerformed

    private void IButtonTC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IButtonTC2ActionPerformed
        // TODO add your handling code here:
        textAreaTC2.append(word2[3]);
        ButtonActions.speak(word2[3], soundToggleButtonTC2);
    }//GEN-LAST:event_IButtonTC2ActionPerformed

    private void AButtonTC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonTC2ActionPerformed
        // TODO add your handling code here:
        textAreaTC2.append(word2[2]);
        ButtonActions.speak(word2[2], soundToggleButtonTC2);
    }//GEN-LAST:event_AButtonTC2ActionPerformed

    private void nextButtonTC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonTC2ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaTC2.getText().trim();
        ButtonActions.checkAnswerAndNext(word2, userAnswer, takeChallengeJTabbedPane, textAreaTC2, false);
    }//GEN-LAST:event_nextButtonTC2ActionPerformed

    private void HButtonTC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HButtonTC2ActionPerformed
        // TODO add your handling code here:
        textAreaTC2.append(word2[1]);
        ButtonActions.speak(word2[1], soundToggleButtonTC2);
    }//GEN-LAST:event_HButtonTC2ActionPerformed

    private void soundToggleButtonTC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonTC2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonTC2);
    }//GEN-LAST:event_soundToggleButtonTC2ActionPerformed

    private void returnButtonTC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonTC1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TakeChallengeAssessment().setVisible(true);
    }//GEN-LAST:event_returnButtonTC1ActionPerformed

    private void readButtonTC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonTC3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaTC3);
    }//GEN-LAST:event_readButtonTC3ActionPerformed

    private void clearButtonTC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonTC3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaTC3);
    }//GEN-LAST:event_clearButtonTC3ActionPerformed

    private void PButtonTC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PButtonTC3ActionPerformed
        // TODO add your handling code here:
        textAreaTC3.append(word3[0]);
        ButtonActions.speak(word3[0], soundToggleButtonTC3);
    }//GEN-LAST:event_PButtonTC3ActionPerformed

    private void HButtonTC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HButtonTC3ActionPerformed
        // TODO add your handling code here:
        textAreaTC3.append(word3[1]);
        ButtonActions.speak(word3[1], soundToggleButtonTC3);
    }//GEN-LAST:event_HButtonTC3ActionPerformed

    private void OButtonTC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OButtonTC3ActionPerformed
        // TODO add your handling code here:
        textAreaTC3.append(word3[2]);
        ButtonActions.speak(word3[2], soundToggleButtonTC3);
    }//GEN-LAST:event_OButtonTC3ActionPerformed

    private void EButtonTC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonTC3ActionPerformed
        // TODO add your handling code here:
        textAreaTC3.append(word3[4]);
        ButtonActions.speak(word3[4], soundToggleButtonTC3);
    }//GEN-LAST:event_EButtonTC3ActionPerformed

    private void nextButtonTC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonTC3ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaTC3.getText().trim();
        ButtonActions.checkAnswerAndNext(word3, userAnswer, takeChallengeJTabbedPane, textAreaTC3, false);
    }//GEN-LAST:event_nextButtonTC3ActionPerformed

    private void NButtonTC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NButtonTC3ActionPerformed
        // TODO add your handling code here:
        textAreaTC3.append(word3[3]);
        ButtonActions.speak(word3[3], soundToggleButtonTC3);
    }//GEN-LAST:event_NButtonTC3ActionPerformed

    private void soundToggleButtonTC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonTC3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonTC3);
    }//GEN-LAST:event_soundToggleButtonTC3ActionPerformed

    private void readButtonTC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonTC4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaTC4);
    }//GEN-LAST:event_readButtonTC4ActionPerformed

    private void clearButtonTC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonTC4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaTC4);
    }//GEN-LAST:event_clearButtonTC4ActionPerformed

    private void EButtonTC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonTC4ActionPerformed
        // TODO add your handling code here:
        textAreaTC4.append(word4[1]);
        ButtonActions.speak(word4[1], soundToggleButtonTC4);
    }//GEN-LAST:event_EButtonTC4ActionPerformed

    private void BButtonTC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BButtonTC4ActionPerformed
        // TODO add your handling code here:
        textAreaTC4.append(word4[2]);
        ButtonActions.speak(word4[2], soundToggleButtonTC4);
    }//GEN-LAST:event_BButtonTC4ActionPerformed

    private void AButtonTC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonTC4ActionPerformed
        // TODO add your handling code here:
        textAreaTC4.append(word4[4]);
        ButtonActions.speak(word4[4], soundToggleButtonTC4);
    }//GEN-LAST:event_AButtonTC4ActionPerformed

    private void RButtonTC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonTC4ActionPerformed
        // TODO add your handling code here:
        textAreaTC4.append(word4[3]);
        ButtonActions.speak(word4[3], soundToggleButtonTC4);
    }//GEN-LAST:event_RButtonTC4ActionPerformed

    private void nextButtonTC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonTC4ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaTC4.getText().trim();
        ButtonActions.checkAnswerAndNext(word4, userAnswer, takeChallengeJTabbedPane, textAreaTC4, false);
    }//GEN-LAST:event_nextButtonTC4ActionPerformed

    private void ZButtonTC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZButtonTC4ActionPerformed
        // TODO add your handling code here:
        textAreaTC4.append(word4[0]);
        ButtonActions.speak(word4[0], soundToggleButtonTC4);
    }//GEN-LAST:event_ZButtonTC4ActionPerformed

    private void soundToggleButtonTC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonTC4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonTC4);
    }//GEN-LAST:event_soundToggleButtonTC4ActionPerformed

    private void readButtonTC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonTC5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaTC5);
    }//GEN-LAST:event_readButtonTC5ActionPerformed

    private void clearButtonTC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonTC5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaTC5);
    }//GEN-LAST:event_clearButtonTC5ActionPerformed

    private void EButtonTC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonTC5ActionPerformed
        // TODO add your handling code here:
        textAreaTC5.append(word5[4]);
        ButtonActions.speak(word5[4], soundToggleButtonTC5);
    }//GEN-LAST:event_EButtonTC5ActionPerformed

    private void AButtonTC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonTC5ActionPerformed
        // TODO add your handling code here:
        textAreaTC5.append(word5[1]);
        ButtonActions.speak(word5[1], soundToggleButtonTC5);
    }//GEN-LAST:event_AButtonTC5ActionPerformed

    private void TButtonTC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TButtonTC5ActionPerformed
        // TODO add your handling code here:
        textAreaTC5.append(word5[0]);
        ButtonActions.speak(word5[0], soundToggleButtonTC5);
    }//GEN-LAST:event_TButtonTC5ActionPerformed

    private void LButtonTC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButtonTC5ActionPerformed
        // TODO add your handling code here:
        textAreaTC5.append(word5[3]);
        ButtonActions.speak(word5[3], soundToggleButtonTC5);
    }//GEN-LAST:event_LButtonTC5ActionPerformed

    private void nextButtonTC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonTC5ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaTC5.getText().trim();
        ButtonActions.checkAnswerAndNext(word5, userAnswer, takeChallengeJTabbedPane, textAreaTC5, false);
    }//GEN-LAST:event_nextButtonTC5ActionPerformed

    private void BButtonTC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BButtonTC5ActionPerformed
        // TODO add your handling code here:
        textAreaTC5.append(word5[2]);
        ButtonActions.speak(word5[2], soundToggleButtonTC5);
    }//GEN-LAST:event_BButtonTC5ActionPerformed

    private void soundToggleButtonTC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonTC5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonTC5);
    }//GEN-LAST:event_soundToggleButtonTC5ActionPerformed

        private void returnButtonTC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonTC5ActionPerformed
                // TODO add your handling code here:
		TakeChallengeAssessment takeChallengeAssessment = new TakeChallengeAssessment();
		takeChallengeAssessment.setVisible(true);
		this.dispose();
        }//GEN-LAST:event_returnButtonTC5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyTakeChallenge().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton AButtonTC2;
        private javax.swing.JButton AButtonTC4;
        private javax.swing.JButton AButtonTC5;
        private javax.swing.JButton BButtonTC4;
        private javax.swing.JButton BButtonTC5;
        private javax.swing.JButton CButtonTC2;
        private javax.swing.JButton EButtonTC1;
        private javax.swing.JButton EButtonTC3;
        private javax.swing.JButton EButtonTC4;
        private javax.swing.JButton EButtonTC5;
        private javax.swing.JButton GButtonTC1;
        private javax.swing.JButton HButtonTC2;
        private javax.swing.JButton HButtonTC3;
        private javax.swing.JButton IButtonTC1;
        private javax.swing.JButton IButtonTC2;
        private javax.swing.JButton LButtonTC5;
        private javax.swing.JButton NButtonTC3;
        private javax.swing.JButton OButtonTC3;
        private javax.swing.JButton PButtonTC3;
        private javax.swing.JButton RButtonTC1;
        private javax.swing.JButton RButtonTC2;
        private javax.swing.JButton RButtonTC4;
        private javax.swing.JButton TButtonTC1;
        private javax.swing.JButton TButtonTC5;
        private javax.swing.JPanel TCtabbedPane1;
        private javax.swing.JPanel TCtabbedPane2;
        private javax.swing.JPanel TCtabbedPane3;
        private javax.swing.JPanel TCtabbedPane4;
        private javax.swing.JPanel TCtabbedPane5;
        private javax.swing.JButton ZButtonTC4;
        private javax.swing.JButton clearButtonTC1;
        private javax.swing.JButton clearButtonTC2;
        private javax.swing.JButton clearButtonTC3;
        private javax.swing.JButton clearButtonTC4;
        private javax.swing.JButton clearButtonTC5;
        private javax.swing.JButton hintButtonTC1;
        private javax.swing.JButton hintButtonTC2;
        private javax.swing.JButton hintButtonTC3;
        private javax.swing.JButton hintButtonTC4;
        private javax.swing.JButton hintButtonTC5;
        private javax.swing.JLabel iconT1;
        private javax.swing.JLabel iconT2;
        private javax.swing.JLabel iconT3;
        private javax.swing.JLabel iconT4;
        private javax.swing.JLabel iconT5;
        private javax.swing.JLabel instructionLabelTC1;
        private javax.swing.JLabel instructionLabelTC2;
        private javax.swing.JLabel instructionLabelTC3;
        private javax.swing.JLabel instructionLabelTC4;
        private javax.swing.JLabel instructionLabelTC5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel jPanel9;
        private javax.swing.JButton nextButtonTC1;
        private javax.swing.JButton nextButtonTC2;
        private javax.swing.JButton nextButtonTC3;
        private javax.swing.JButton nextButtonTC4;
        private javax.swing.JButton nextButtonTC5;
        private javax.swing.JButton readButtonTC1;
        private javax.swing.JButton readButtonTC2;
        private javax.swing.JButton readButtonTC3;
        private javax.swing.JButton readButtonTC4;
        private javax.swing.JButton readButtonTC5;
        private javax.swing.JButton returnButtonTC1;
        private javax.swing.JButton returnButtonTC5;
        private javax.swing.JToggleButton soundToggleButtonTC1;
        private javax.swing.JToggleButton soundToggleButtonTC2;
        private javax.swing.JToggleButton soundToggleButtonTC3;
        private javax.swing.JToggleButton soundToggleButtonTC4;
        private javax.swing.JToggleButton soundToggleButtonTC5;
        private javax.swing.JTabbedPane takeChallengeJTabbedPane;
        private javax.swing.JTextArea textAreaTC1;
        private javax.swing.JTextArea textAreaTC2;
        private javax.swing.JTextArea textAreaTC3;
        private javax.swing.JTextArea textAreaTC4;
        private javax.swing.JTextArea textAreaTC5;
        // End of variables declaration//GEN-END:variables
}
