/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Core.AssessmentPage.TakeChallengeModeOfDifficulty;

import Core.Actions.ButtonActions;
import Core.AssessmentPage.TakeChallengeAssessment;
import Utilities.MusicPlayer;

import javax.swing.*;
import java.awt.*;

/**
 * @author Marc
 */
public class EasyTakeChallenge extends javax.swing.JFrame {

    private MusicPlayer musicPlayer;

    /**
     * Creates new form EasyTakeChallenge
     */
    public EasyTakeChallenge() {
        initComponents();

        musicPlayer = MusicPlayer.getInstance();

        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/TIGER.png"));
        ImageIcon icon = new ImageIcon(originalIcon.getImage().getScaledInstance(iconT1.getWidth(), iconT1.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT1.setIcon(icon);

        originalIcon = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/CHAIR.png"));
        icon = new ImageIcon(originalIcon.getImage().getScaledInstance(iconT2.getWidth(), iconT2.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT2.setIcon(icon);

        originalIcon = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/PHONE.png"));
        icon = new ImageIcon(originalIcon.getImage().getScaledInstance(iconT3.getWidth(), iconT3.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT3.setIcon(icon);

        originalIcon = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/ZEBRA.png"));
        icon = new ImageIcon(originalIcon.getImage().getScaledInstance(iconT4.getWidth(), iconT4.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT4.setIcon(icon);

        originalIcon = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/TABLE.png"));
        icon = new ImageIcon(originalIcon.getImage().getScaledInstance(iconT5.getWidth(), iconT5.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT5.setIcon(icon);

        ButtonActions.setCursorForButtons(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR),
                TButtonTC1, IButtonTC1, GButtonTC1, EButtonTC1, RButtonTC1, nextButtonTC1, returnButtonTC1,
                CButtonTC2, HButtonTC2, AButtonTC2, IButtonTC2, RButtonTC2, nextButtonTC2,
                PButtonTC3, HButtonTC3, OButtonTC3, NButtonTC3, EButtonTC3, nextButtonTC3,
                ZButtonTC4, EButtonTC4, BButtonTC4, RButtonTC4, AButtonTC4, nextButtonTC4,
                TButtonTC5, AButtonTC5, BButtonTC5, LButtonTC5, EButtonTC5, nextButtonTC5, returnButtonTC5
        );
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        takeChallengeJTabbedPane = new javax.swing.JTabbedPane();
        TCtabbedPane1 = new javax.swing.JPanel();
        instructionLabelTC1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        readButtonTC1 = new javax.swing.JButton();
        clearButtonTC1 = new javax.swing.JButton();
        hintButtonTC1 = new javax.swing.JButton();
        RButtonTC1 = new javax.swing.JLabel();
        EButtonTC1 = new javax.swing.JLabel();
        GButtonTC1 = new javax.swing.JLabel();
        IButtonTC1 = new javax.swing.JLabel();
        TButtonTC1 = new javax.swing.JLabel();
        textAreaTC1 = new javax.swing.JTextArea();
        soundToggleButtonTC1 = new javax.swing.JToggleButton();
        nextButtonTC1 = new javax.swing.JLabel();
        returnButtonTC1 = new javax.swing.JLabel();
        iconT1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        TCtabbedPane2 = new javax.swing.JPanel();
        instructionLabelTC2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        readButtonTC2 = new javax.swing.JButton();
        clearButtonTC2 = new javax.swing.JButton();
        hintButtonTC2 = new javax.swing.JButton();
        nextButtonTC2 = new javax.swing.JLabel();
        RButtonTC2 = new javax.swing.JLabel();
        IButtonTC2 = new javax.swing.JLabel();
        AButtonTC2 = new javax.swing.JLabel();
        HButtonTC2 = new javax.swing.JLabel();
        CButtonTC2 = new javax.swing.JLabel();
        textAreaTC2 = new javax.swing.JTextArea();
        soundToggleButtonTC2 = new javax.swing.JToggleButton();
        iconT2 = new javax.swing.JLabel();
        background4 = new javax.swing.JLabel();
        TCtabbedPane3 = new javax.swing.JPanel();
        instructionLabelTC3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        readButtonTC3 = new javax.swing.JButton();
        clearButtonTC3 = new javax.swing.JButton();
        hintButtonTC3 = new javax.swing.JButton();
        nextButtonTC3 = new javax.swing.JLabel();
        EButtonTC3 = new javax.swing.JLabel();
        NButtonTC3 = new javax.swing.JLabel();
        OButtonTC3 = new javax.swing.JLabel();
        HButtonTC3 = new javax.swing.JLabel();
        PButtonTC3 = new javax.swing.JLabel();
        textAreaTC3 = new javax.swing.JTextArea();
        soundToggleButtonTC3 = new javax.swing.JToggleButton();
        iconT3 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();
        TCtabbedPane4 = new javax.swing.JPanel();
        instructionLabelTC4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        readButtonTC4 = new javax.swing.JButton();
        clearButtonTC4 = new javax.swing.JButton();
        hintButtonTC4 = new javax.swing.JButton();
        nextButtonTC4 = new javax.swing.JLabel();
        AButtonTC4 = new javax.swing.JLabel();
        RButtonTC4 = new javax.swing.JLabel();
        BButtonTC4 = new javax.swing.JLabel();
        EButtonTC4 = new javax.swing.JLabel();
        ZButtonTC4 = new javax.swing.JLabel();
        textAreaTC4 = new javax.swing.JTextArea();
        soundToggleButtonTC4 = new javax.swing.JToggleButton();
        iconT4 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        TCtabbedPane5 = new javax.swing.JPanel();
        instructionLabelTC5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        readButtonTC5 = new javax.swing.JButton();
        clearButtonTC5 = new javax.swing.JButton();
        hintButtonTC5 = new javax.swing.JButton();
        EButtonTC5 = new javax.swing.JLabel();
        LButtonTC5 = new javax.swing.JLabel();
        BButtonTC5 = new javax.swing.JLabel();
        AButtonTC5 = new javax.swing.JLabel();
        TButtonTC5 = new javax.swing.JLabel();
        textAreaTC5 = new javax.swing.JTextArea();
        soundToggleButtonTC5 = new javax.swing.JToggleButton();
        returnButtonTC5 = new javax.swing.JLabel();
        nextButtonTC5 = new javax.swing.JLabel();
        iconT5 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TCtabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        TCtabbedPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabelTC1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        instructionLabelTC1.setForeground(new java.awt.Color(0, 0, 0));
        instructionLabelTC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabelTC1.setText("Guess the Word");
        TCtabbedPane1.add(instructionLabelTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        TCtabbedPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        readButtonTC1.setText("Read");
        readButtonTC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonTC1ActionPerformed(evt);
            }
        });
        TCtabbedPane1.add(readButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

        clearButtonTC1.setText("Clear");
        clearButtonTC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonTC1ActionPerformed(evt);
            }
        });
        TCtabbedPane1.add(clearButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

        hintButtonTC1.setText("Hint");
        TCtabbedPane1.add(hintButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

        RButtonTC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/R button.png"))); // NOI18N
        RButtonTC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RButtonTC1MouseClicked(evt);
            }
        });
        TCtabbedPane1.add(RButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, -1));

        EButtonTC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/E button.png"))); // NOI18N
        EButtonTC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EButtonTC1MouseClicked(evt);
            }
        });
        TCtabbedPane1.add(EButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        GButtonTC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/G button.png"))); // NOI18N
        GButtonTC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GButtonTC1MouseClicked(evt);
            }
        });
        TCtabbedPane1.add(GButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, -1, -1));

        IButtonTC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/I button.png"))); // NOI18N
        IButtonTC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IButtonTC1MouseClicked(evt);
            }
        });
        TCtabbedPane1.add(IButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        TButtonTC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/T button.png"))); // NOI18N
        TButtonTC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TButtonTC1MouseClicked(evt);
            }
        });
        TCtabbedPane1.add(TButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, -1));

        textAreaTC1.setEditable(false);
        textAreaTC1.setColumns(20);
        textAreaTC1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textAreaTC1.setRows(5);
        TCtabbedPane1.add(textAreaTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 250, 80));

        soundToggleButtonTC1.setText("Sound");
        soundToggleButtonTC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonTC1ActionPerformed(evt);
            }
        });
        TCtabbedPane1.add(soundToggleButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        nextButtonTC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/next button.png"))); // NOI18N
        nextButtonTC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonTC1MouseClicked(evt);
            }
        });
        TCtabbedPane1.add(nextButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, -1, -1));

        returnButtonTC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/back button.png"))); // NOI18N
        returnButtonTC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonTC1MouseClicked(evt);
            }
        });
        TCtabbedPane1.add(returnButtonTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        iconT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/TIGER.png"))); // NOI18N
        iconT1.setPreferredSize(new java.awt.Dimension(50, 15));
        TCtabbedPane1.add(iconT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgbgbg.gif"))); // NOI18N
        TCtabbedPane1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 590));

        takeChallengeJTabbedPane.addTab("tab1", TCtabbedPane1);

        TCtabbedPane2.setBackground(new java.awt.Color(204, 204, 204));
        TCtabbedPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabelTC2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        instructionLabelTC2.setForeground(new java.awt.Color(0, 0, 0));
        instructionLabelTC2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabelTC2.setText("Guess the Word");
        TCtabbedPane2.add(instructionLabelTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        TCtabbedPane2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        readButtonTC2.setText("Read");
        readButtonTC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonTC2ActionPerformed(evt);
            }
        });
        TCtabbedPane2.add(readButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

        clearButtonTC2.setText("Clear");
        clearButtonTC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonTC2ActionPerformed(evt);
            }
        });
        TCtabbedPane2.add(clearButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

        hintButtonTC2.setText("Hint");
        TCtabbedPane2.add(hintButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

        nextButtonTC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/next button.png"))); // NOI18N
        nextButtonTC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonTC2MouseClicked(evt);
            }
        });
        TCtabbedPane2.add(nextButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, -1, -1));

        RButtonTC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/R button.png"))); // NOI18N
        RButtonTC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RButtonTC2MouseClicked(evt);
            }
        });
        TCtabbedPane2.add(RButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        IButtonTC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/I button.png"))); // NOI18N
        IButtonTC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IButtonTC2MouseClicked(evt);
            }
        });
        TCtabbedPane2.add(IButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        AButtonTC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/A button.png"))); // NOI18N
        AButtonTC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AButtonTC2MouseClicked(evt);
            }
        });
        TCtabbedPane2.add(AButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        HButtonTC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/H button.png"))); // NOI18N
        HButtonTC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HButtonTC2MouseClicked(evt);
            }
        });
        TCtabbedPane2.add(HButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        CButtonTC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/C button.png"))); // NOI18N
        CButtonTC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CButtonTC2MouseClicked(evt);
            }
        });
        TCtabbedPane2.add(CButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, -1));

        textAreaTC2.setEditable(false);
        textAreaTC2.setColumns(20);
        textAreaTC2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textAreaTC2.setRows(5);
        TCtabbedPane2.add(textAreaTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 240, 80));

        soundToggleButtonTC2.setText("Sound");
        soundToggleButtonTC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonTC2ActionPerformed(evt);
            }
        });
        TCtabbedPane2.add(soundToggleButtonTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        iconT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/CHAIR.png"))); // NOI18N
        iconT2.setPreferredSize(new java.awt.Dimension(50, 15));
        TCtabbedPane2.add(iconT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgbgbg.gif"))); // NOI18N
        TCtabbedPane2.add(background4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 590));

        takeChallengeJTabbedPane.addTab("tab2", TCtabbedPane2);

        TCtabbedPane3.setBackground(new java.awt.Color(204, 204, 204));
        TCtabbedPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabelTC3.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        instructionLabelTC3.setForeground(new java.awt.Color(0, 0, 0));
        instructionLabelTC3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabelTC3.setText("Guess the Word");
        TCtabbedPane3.add(instructionLabelTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        TCtabbedPane3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        readButtonTC3.setText("Read");
        readButtonTC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonTC3ActionPerformed(evt);
            }
        });
        TCtabbedPane3.add(readButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

        clearButtonTC3.setText("Clear");
        clearButtonTC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonTC3ActionPerformed(evt);
            }
        });
        TCtabbedPane3.add(clearButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

        hintButtonTC3.setText("Hint");
        TCtabbedPane3.add(hintButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

        nextButtonTC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/next button.png"))); // NOI18N
        nextButtonTC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonTC3MouseClicked(evt);
            }
        });
        TCtabbedPane3.add(nextButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, -1, -1));

        EButtonTC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/E button.png"))); // NOI18N
        EButtonTC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EButtonTC3MouseClicked(evt);
            }
        });
        TCtabbedPane3.add(EButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, -1));

        NButtonTC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/N button.png"))); // NOI18N
        NButtonTC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NButtonTC3MouseClicked(evt);
            }
        });
        TCtabbedPane3.add(NButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        OButtonTC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/O button.png"))); // NOI18N
        OButtonTC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OButtonTC3MouseClicked(evt);
            }
        });
        TCtabbedPane3.add(OButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        HButtonTC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/H button.png"))); // NOI18N
        HButtonTC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HButtonTC3MouseClicked(evt);
            }
        });
        TCtabbedPane3.add(HButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        PButtonTC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/P button.png"))); // NOI18N
        PButtonTC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PButtonTC3MouseClicked(evt);
            }
        });
        TCtabbedPane3.add(PButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        textAreaTC3.setEditable(false);
        textAreaTC3.setColumns(20);
        textAreaTC3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textAreaTC3.setRows(5);
        TCtabbedPane3.add(textAreaTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 240, 70));

        soundToggleButtonTC3.setText("Sound");
        soundToggleButtonTC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonTC3ActionPerformed(evt);
            }
        });
        TCtabbedPane3.add(soundToggleButtonTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        iconT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/PHONE.png"))); // NOI18N
        iconT3.setPreferredSize(new java.awt.Dimension(50, 15));
        TCtabbedPane3.add(iconT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 439, 209));

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgbgbg.gif"))); // NOI18N
        TCtabbedPane3.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 590));

        takeChallengeJTabbedPane.addTab("tab3", TCtabbedPane3);

        TCtabbedPane4.setBackground(new java.awt.Color(204, 204, 204));
        TCtabbedPane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabelTC4.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        instructionLabelTC4.setForeground(new java.awt.Color(0, 0, 0));
        instructionLabelTC4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabelTC4.setText("Guess the Word");
        TCtabbedPane4.add(instructionLabelTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        TCtabbedPane4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        readButtonTC4.setText("Read");
        readButtonTC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonTC4ActionPerformed(evt);
            }
        });
        TCtabbedPane4.add(readButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

        clearButtonTC4.setText("Clear");
        clearButtonTC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonTC4ActionPerformed(evt);
            }
        });
        TCtabbedPane4.add(clearButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

        hintButtonTC4.setText("Hint");
        TCtabbedPane4.add(hintButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

        nextButtonTC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/next button.png"))); // NOI18N
        nextButtonTC4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonTC4MouseClicked(evt);
            }
        });
        TCtabbedPane4.add(nextButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, -1, -1));

        AButtonTC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/A button.png"))); // NOI18N
        AButtonTC4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AButtonTC4MouseClicked(evt);
            }
        });
        TCtabbedPane4.add(AButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        RButtonTC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/R button.png"))); // NOI18N
        RButtonTC4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RButtonTC4MouseClicked(evt);
            }
        });
        TCtabbedPane4.add(RButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, -1, -1));

        BButtonTC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/B button.png"))); // NOI18N
        BButtonTC4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BButtonTC4MouseClicked(evt);
            }
        });
        TCtabbedPane4.add(BButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        EButtonTC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/E button.png"))); // NOI18N
        EButtonTC4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EButtonTC4MouseClicked(evt);
            }
        });
        TCtabbedPane4.add(EButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        ZButtonTC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/Z button.png"))); // NOI18N
        ZButtonTC4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZButtonTC4MouseClicked(evt);
            }
        });
        TCtabbedPane4.add(ZButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));

        textAreaTC4.setEditable(false);
        textAreaTC4.setColumns(20);
        textAreaTC4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textAreaTC4.setRows(5);
        TCtabbedPane4.add(textAreaTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 240, 70));

        soundToggleButtonTC4.setText("Sound");
        soundToggleButtonTC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonTC4ActionPerformed(evt);
            }
        });
        TCtabbedPane4.add(soundToggleButtonTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        iconT4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/ZEBRA.png"))); // NOI18N
        iconT4.setPreferredSize(new java.awt.Dimension(50, 15));
        TCtabbedPane4.add(iconT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 439, 209));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgbgbg.gif"))); // NOI18N
        TCtabbedPane4.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 590));

        takeChallengeJTabbedPane.addTab("tab4", TCtabbedPane4);

        TCtabbedPane5.setBackground(new java.awt.Color(204, 204, 204));
        TCtabbedPane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabelTC5.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        instructionLabelTC5.setForeground(new java.awt.Color(0, 0, 0));
        instructionLabelTC5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabelTC5.setText("Guess the Word");
        TCtabbedPane5.add(instructionLabelTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        TCtabbedPane5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        readButtonTC5.setText("Read");
        readButtonTC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonTC5ActionPerformed(evt);
            }
        });
        TCtabbedPane5.add(readButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

        clearButtonTC5.setText("Clear");
        clearButtonTC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonTC5ActionPerformed(evt);
            }
        });
        TCtabbedPane5.add(clearButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

        hintButtonTC5.setText("Hint");
        TCtabbedPane5.add(hintButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

        EButtonTC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/E button.png"))); // NOI18N
        EButtonTC5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EButtonTC5MouseClicked(evt);
            }
        });
        TCtabbedPane5.add(EButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        LButtonTC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/L button.png"))); // NOI18N
        LButtonTC5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LButtonTC5MouseClicked(evt);
            }
        });
        TCtabbedPane5.add(LButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        BButtonTC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/B button.png"))); // NOI18N
        BButtonTC5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BButtonTC5MouseClicked(evt);
            }
        });
        TCtabbedPane5.add(BButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));

        AButtonTC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/A button.png"))); // NOI18N
        AButtonTC5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AButtonTC5MouseClicked(evt);
            }
        });
        TCtabbedPane5.add(AButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        TButtonTC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/T button.png"))); // NOI18N
        TButtonTC5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TButtonTC5MouseClicked(evt);
            }
        });
        TCtabbedPane5.add(TButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        textAreaTC5.setEditable(false);
        textAreaTC5.setColumns(20);
        textAreaTC5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textAreaTC5.setRows(5);
        TCtabbedPane5.add(textAreaTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 240, 70));

        soundToggleButtonTC5.setText("Sound");
        soundToggleButtonTC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonTC5ActionPerformed(evt);
            }
        });
        TCtabbedPane5.add(soundToggleButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        returnButtonTC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/back button.png"))); // NOI18N
        returnButtonTC5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonTC5MouseClicked(evt);
            }
        });
        TCtabbedPane5.add(returnButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        nextButtonTC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/next button.png"))); // NOI18N
        nextButtonTC5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonTC5MouseClicked(evt);
            }
        });
        TCtabbedPane5.add(nextButtonTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, -1, -1));

        iconT5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/TABLE.png"))); // NOI18N
        iconT5.setPreferredSize(new java.awt.Dimension(50, 15));
        TCtabbedPane5.add(iconT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 439, 209));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgbgbg.gif"))); // NOI18N
        TCtabbedPane5.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 590));

        takeChallengeJTabbedPane.addTab("tab5", TCtabbedPane5);

        getContentPane().add(takeChallengeJTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 780, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    String[] word1 = {"T", "I", "G", "E", "R"};
    String[] word2 = {"C", "H", "A", "I", "R"};
    String[] word3 = {"P", "H", "O", "N", "E"};
    String[] word4 = {"Z", "E", "B", "R", "A"};
    String[] word5 = {"T", "A", "B", "L", "E"};

    private void soundToggleButtonTC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonTC1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonTC1);
    }//GEN-LAST:event_soundToggleButtonTC1ActionPerformed

    private void clearButtonTC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonTC1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaTC1);
    }//GEN-LAST:event_clearButtonTC1ActionPerformed

    private void readButtonTC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonTC1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaTC1, musicPlayer);
    }//GEN-LAST:event_readButtonTC1ActionPerformed

    private void readButtonTC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonTC2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaTC2, musicPlayer);
    }//GEN-LAST:event_readButtonTC2ActionPerformed

    private void clearButtonTC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonTC2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaTC2);
    }//GEN-LAST:event_clearButtonTC2ActionPerformed

    private void soundToggleButtonTC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonTC2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonTC2);
    }//GEN-LAST:event_soundToggleButtonTC2ActionPerformed

    private void readButtonTC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonTC3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaTC3, musicPlayer);
    }//GEN-LAST:event_readButtonTC3ActionPerformed

    private void clearButtonTC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonTC3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaTC3);
    }//GEN-LAST:event_clearButtonTC3ActionPerformed

    private void soundToggleButtonTC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonTC3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonTC3);
    }//GEN-LAST:event_soundToggleButtonTC3ActionPerformed

    private void readButtonTC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonTC4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaTC4, musicPlayer);
    }//GEN-LAST:event_readButtonTC4ActionPerformed

    private void clearButtonTC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonTC4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaTC4);
    }//GEN-LAST:event_clearButtonTC4ActionPerformed

    private void soundToggleButtonTC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonTC4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonTC4);
    }//GEN-LAST:event_soundToggleButtonTC4ActionPerformed

    private void readButtonTC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonTC5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaTC5, musicPlayer);
    }//GEN-LAST:event_readButtonTC5ActionPerformed

    private void clearButtonTC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonTC5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaTC5);
    }//GEN-LAST:event_clearButtonTC5ActionPerformed

    private void soundToggleButtonTC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonTC5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonTC5);
    }//GEN-LAST:event_soundToggleButtonTC5ActionPerformed

    private void TButtonTC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TButtonTC1MouseClicked
        // TODO add your handling code here:
        textAreaTC1.append(word1[0]);
        ButtonActions.speak(word1[0], soundToggleButtonTC1);
    }//GEN-LAST:event_TButtonTC1MouseClicked

    private void IButtonTC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IButtonTC1MouseClicked
        // TODO add your handling code here:
        textAreaTC1.append(word1[1]);
        ButtonActions.speak(word1[1], soundToggleButtonTC1);
    }//GEN-LAST:event_IButtonTC1MouseClicked

    private void GButtonTC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GButtonTC1MouseClicked
        // TODO add your handling code here:
        textAreaTC1.append(word1[2]);
        ButtonActions.speak(word1[2], soundToggleButtonTC1);
    }//GEN-LAST:event_GButtonTC1MouseClicked

    private void EButtonTC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EButtonTC1MouseClicked
        // TODO add your handling code here:
        textAreaTC1.append(word1[3]);
        ButtonActions.speak(word1[3], soundToggleButtonTC1);

    }//GEN-LAST:event_EButtonTC1MouseClicked

    private void RButtonTC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RButtonTC1MouseClicked
        // TODO add your handling code here:
        textAreaTC1.append(word1[4]);
        ButtonActions.speak(word1[4], soundToggleButtonTC1);
    }//GEN-LAST:event_RButtonTC1MouseClicked

    private void CButtonTC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CButtonTC2MouseClicked
        // TODO add your handling code here:
        textAreaTC2.append(word2[0]);
        ButtonActions.speak(word2[0], soundToggleButtonTC2);
    }//GEN-LAST:event_CButtonTC2MouseClicked

    private void HButtonTC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HButtonTC2MouseClicked
        // TODO add your handling code here:
        textAreaTC2.append(word2[1]);
        ButtonActions.speak(word2[1], soundToggleButtonTC2);
    }//GEN-LAST:event_HButtonTC2MouseClicked

    private void AButtonTC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AButtonTC2MouseClicked
        // TODO add your handling code here:
        textAreaTC2.append(word2[2]);
        ButtonActions.speak(word2[2], soundToggleButtonTC2);
    }//GEN-LAST:event_AButtonTC2MouseClicked

    private void IButtonTC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IButtonTC2MouseClicked
        // TODO add your handling code here:
        textAreaTC2.append(word2[3]);
        ButtonActions.speak(word2[3], soundToggleButtonTC2);
    }//GEN-LAST:event_IButtonTC2MouseClicked

    private void RButtonTC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RButtonTC2MouseClicked
        // TODO add your handling code here:
        textAreaTC2.append(word2[4]);
        ButtonActions.speak(word2[4], soundToggleButtonTC2);
    }//GEN-LAST:event_RButtonTC2MouseClicked

    private void PButtonTC3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PButtonTC3MouseClicked
        // TODO add your handling code here:
        textAreaTC3.append(word3[0]);
        ButtonActions.speak(word3[0], soundToggleButtonTC3);

    }//GEN-LAST:event_PButtonTC3MouseClicked

    private void HButtonTC3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HButtonTC3MouseClicked
        // TODO add your handling code here:
        textAreaTC3.append(word3[1]);
        ButtonActions.speak(word3[1], soundToggleButtonTC3);
    }//GEN-LAST:event_HButtonTC3MouseClicked

    private void OButtonTC3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OButtonTC3MouseClicked
        // TODO add your handling code here:
        textAreaTC3.append(word3[2]);
        ButtonActions.speak(word3[2], soundToggleButtonTC3);

    }//GEN-LAST:event_OButtonTC3MouseClicked

    private void NButtonTC3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NButtonTC3MouseClicked
        // TODO add your handling code here:
        textAreaTC3.append(word3[3]);
        ButtonActions.speak(word3[3], soundToggleButtonTC3);

    }//GEN-LAST:event_NButtonTC3MouseClicked

    private void EButtonTC3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EButtonTC3MouseClicked
        // TODO add your handling code here:
        textAreaTC3.append(word3[4]);
        ButtonActions.speak(word3[4], soundToggleButtonTC3);
    }//GEN-LAST:event_EButtonTC3MouseClicked

    private void ZButtonTC4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZButtonTC4MouseClicked
        // TODO add your handling code here:
        textAreaTC4.append(word4[0]);
        ButtonActions.speak(word4[0], soundToggleButtonTC4);
    }//GEN-LAST:event_ZButtonTC4MouseClicked

    private void EButtonTC4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EButtonTC4MouseClicked
        // TODO add your handling code here:
        textAreaTC4.append(word4[1]);
        ButtonActions.speak(word4[1], soundToggleButtonTC4);
    }//GEN-LAST:event_EButtonTC4MouseClicked

    private void BButtonTC4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BButtonTC4MouseClicked
        // TODO add your handling code here:
        textAreaTC4.append(word4[2]);
        ButtonActions.speak(word4[2], soundToggleButtonTC4);
    }//GEN-LAST:event_BButtonTC4MouseClicked

    private void RButtonTC4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RButtonTC4MouseClicked
        // TODO add your handling code here:
        textAreaTC4.append(word4[3]);
        ButtonActions.speak(word4[3], soundToggleButtonTC4);
    }//GEN-LAST:event_RButtonTC4MouseClicked

    private void AButtonTC4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AButtonTC4MouseClicked
        // TODO add your handling code here:
        textAreaTC4.append(word4[4]);
        ButtonActions.speak(word4[4], soundToggleButtonTC4);
    }//GEN-LAST:event_AButtonTC4MouseClicked

    private void TButtonTC5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TButtonTC5MouseClicked
        // TODO add your handling code here:
        textAreaTC5.append(word5[0]);
        ButtonActions.speak(word5[0], soundToggleButtonTC5);
    }//GEN-LAST:event_TButtonTC5MouseClicked

    private void AButtonTC5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AButtonTC5MouseClicked
        // TODO add your handling code here:
        textAreaTC5.append(word5[1]);
        ButtonActions.speak(word5[1], soundToggleButtonTC5);
    }//GEN-LAST:event_AButtonTC5MouseClicked

    private void BButtonTC5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BButtonTC5MouseClicked
        // TODO add your handling code here:
        textAreaTC5.append(word5[2]);
        ButtonActions.speak(word5[2], soundToggleButtonTC5);
    }//GEN-LAST:event_BButtonTC5MouseClicked

    private void LButtonTC5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LButtonTC5MouseClicked
        // TODO add your handling code here:
        textAreaTC5.append(word5[3]);
        ButtonActions.speak(word5[3], soundToggleButtonTC5);
    }//GEN-LAST:event_LButtonTC5MouseClicked

    private void EButtonTC5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EButtonTC5MouseClicked
        // TODO add your handling code here:
        textAreaTC5.append(word5[4]);
        ButtonActions.speak(word5[4], soundToggleButtonTC5);
    }//GEN-LAST:event_EButtonTC5MouseClicked

    private void returnButtonTC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonTC1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new TakeChallengeAssessment().setVisible(true);
    }//GEN-LAST:event_returnButtonTC1MouseClicked

    private void nextButtonTC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonTC1MouseClicked
        // TODO add your handling code here:
        String userAnswer = textAreaTC1.getText().trim();
        ButtonActions.checkAnswerAndNext(word1, userAnswer, takeChallengeJTabbedPane, textAreaTC1, false);
    }//GEN-LAST:event_nextButtonTC1MouseClicked

    private void nextButtonTC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonTC2MouseClicked
        // TODO add your handling code here:
        String userAnswer = textAreaTC2.getText().trim();
        ButtonActions.checkAnswerAndNext(word2, userAnswer, takeChallengeJTabbedPane, textAreaTC2, false);
    }//GEN-LAST:event_nextButtonTC2MouseClicked

    private void nextButtonTC3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonTC3MouseClicked
        // TODO add your handling code here:
        String userAnswer = textAreaTC3.getText().trim();
        ButtonActions.checkAnswerAndNext(word3, userAnswer, takeChallengeJTabbedPane, textAreaTC3, false);
    }//GEN-LAST:event_nextButtonTC3MouseClicked

    private void nextButtonTC4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonTC4MouseClicked
        // TODO add your handling code here:
        String userAnswer = textAreaTC4.getText().trim();
        ButtonActions.checkAnswerAndNext(word4, userAnswer, takeChallengeJTabbedPane, textAreaTC4, false);
    }//GEN-LAST:event_nextButtonTC4MouseClicked

    private void nextButtonTC5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonTC5MouseClicked
        // TODO add your handling code here:
        String userAnswer = textAreaTC5.getText().trim();
        ButtonActions.checkAnswerAndNext(word5, userAnswer, takeChallengeJTabbedPane, textAreaTC5, false);
    }//GEN-LAST:event_nextButtonTC5MouseClicked

    private void returnButtonTC5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonTC5MouseClicked
        // TODO add your handling code here:
        TakeChallengeAssessment takeChallengeAssessment = new TakeChallengeAssessment();
        takeChallengeAssessment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnButtonTC5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyTakeChallenge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AButtonTC2;
    private javax.swing.JLabel AButtonTC4;
    private javax.swing.JLabel AButtonTC5;
    private javax.swing.JLabel BButtonTC4;
    private javax.swing.JLabel BButtonTC5;
    private javax.swing.JLabel CButtonTC2;
    private javax.swing.JLabel EButtonTC1;
    private javax.swing.JLabel EButtonTC3;
    private javax.swing.JLabel EButtonTC4;
    private javax.swing.JLabel EButtonTC5;
    private javax.swing.JLabel GButtonTC1;
    private javax.swing.JLabel HButtonTC2;
    private javax.swing.JLabel HButtonTC3;
    private javax.swing.JLabel IButtonTC1;
    private javax.swing.JLabel IButtonTC2;
    private javax.swing.JLabel LButtonTC5;
    private javax.swing.JLabel NButtonTC3;
    private javax.swing.JLabel OButtonTC3;
    private javax.swing.JLabel PButtonTC3;
    private javax.swing.JLabel RButtonTC1;
    private javax.swing.JLabel RButtonTC2;
    private javax.swing.JLabel RButtonTC4;
    private javax.swing.JLabel TButtonTC1;
    private javax.swing.JLabel TButtonTC5;
    private javax.swing.JPanel TCtabbedPane1;
    private javax.swing.JPanel TCtabbedPane2;
    private javax.swing.JPanel TCtabbedPane3;
    private javax.swing.JPanel TCtabbedPane4;
    private javax.swing.JPanel TCtabbedPane5;
    private javax.swing.JLabel ZButtonTC4;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JButton clearButtonTC1;
    private javax.swing.JButton clearButtonTC2;
    private javax.swing.JButton clearButtonTC3;
    private javax.swing.JButton clearButtonTC4;
    private javax.swing.JButton clearButtonTC5;
    private javax.swing.JButton hintButtonTC1;
    private javax.swing.JButton hintButtonTC2;
    private javax.swing.JButton hintButtonTC3;
    private javax.swing.JButton hintButtonTC4;
    private javax.swing.JButton hintButtonTC5;
    private javax.swing.JLabel iconT1;
    private javax.swing.JLabel iconT2;
    private javax.swing.JLabel iconT3;
    private javax.swing.JLabel iconT4;
    private javax.swing.JLabel iconT5;
    private javax.swing.JLabel instructionLabelTC1;
    private javax.swing.JLabel instructionLabelTC2;
    private javax.swing.JLabel instructionLabelTC3;
    private javax.swing.JLabel instructionLabelTC4;
    private javax.swing.JLabel instructionLabelTC5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel nextButtonTC1;
    private javax.swing.JLabel nextButtonTC2;
    private javax.swing.JLabel nextButtonTC3;
    private javax.swing.JLabel nextButtonTC4;
    private javax.swing.JLabel nextButtonTC5;
    private javax.swing.JButton readButtonTC1;
    private javax.swing.JButton readButtonTC2;
    private javax.swing.JButton readButtonTC3;
    private javax.swing.JButton readButtonTC4;
    private javax.swing.JButton readButtonTC5;
    private javax.swing.JLabel returnButtonTC1;
    private javax.swing.JLabel returnButtonTC5;
    private javax.swing.JToggleButton soundToggleButtonTC1;
    private javax.swing.JToggleButton soundToggleButtonTC2;
    private javax.swing.JToggleButton soundToggleButtonTC3;
    private javax.swing.JToggleButton soundToggleButtonTC4;
    private javax.swing.JToggleButton soundToggleButtonTC5;
    private javax.swing.JTabbedPane takeChallengeJTabbedPane;
    private javax.swing.JTextArea textAreaTC1;
    private javax.swing.JTextArea textAreaTC2;
    private javax.swing.JTextArea textAreaTC3;
    private javax.swing.JTextArea textAreaTC4;
    private javax.swing.JTextArea textAreaTC5;
    // End of variables declaration//GEN-END:variables
}
