/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Core.AssessmentPage.TakeChallengeModeOfDifficulty;

import Core.Actions.ButtonActions;
import Core.AssessmentPage.TakeChallengeAssessment;
import Utilities.MusicPlayer;

import javax.swing.*;
import java.awt.*;

/**
 * @author Marc
 */
public class HardTakeChallenge extends javax.swing.JFrame {

    private MusicPlayer musicPlayer;

    /**
     * Creates new form HardTakeChallenge
     */
    public HardTakeChallenge() {
        initComponents();

        musicPlayer = MusicPlayer.getInstance();

        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/ELEPHANT.png"));
        ImageIcon icon = new ImageIcon(originalIcon.getImage().getScaledInstance(iconT1.getWidth(), iconT1.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT1.setIcon(icon);

        ImageIcon originalIcon2 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/GIRAFFE.png"));
        ImageIcon icon2 = new ImageIcon(originalIcon2.getImage().getScaledInstance(iconT2.getWidth(), iconT2.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT2.setIcon(icon2);

        ImageIcon originalIcon3 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/GLASSES.png"));
        ImageIcon icon3 = new ImageIcon(originalIcon3.getImage().getScaledInstance(iconT3.getWidth(), iconT3.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT3.setIcon(icon3);

        ImageIcon originalIcon4 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/CAMERA.png"));
        ImageIcon icon4 = new ImageIcon(originalIcon4.getImage().getScaledInstance(iconT4.getWidth(), iconT4.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT4.setIcon(icon4);

        ImageIcon originalIcon5 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/PENGUIN.png"));
        ImageIcon icon5 = new ImageIcon(originalIcon5.getImage().getScaledInstance(iconT5.getWidth(), iconT5.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT5.setIcon(icon5);

        ButtonActions.setCursorForButtons(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR),
                EButtonH1, LButtonH1, E2ButtonH1, PButtonH1, HButtonH1, AButtonH1, NButtonH1, TButtonH1, returnButtonH1, nextButtonH1,
                GButtonH2, IButtonH2, RButtonH2, AButtonH2, F1ButtonH2, F2ButtonH2, EButtonH2, nextButtonH2,
                S1ButtonH3, S2ButtonH3, EButtonH3, GButtonH3, AButtonH3, LButtonH3, S3ButtonH3, nextButtonH3,
                A1ButtonH4, MButtonH4, EButtonH4, RButtonH4, A2ButtonH4, CButtonH4, nextButtonH4,
                N1ButtonH5, EButtonH5, UButtonH5, GButtonH5, IButtonH5, N2ButtonH5, PButtonH5, returnButtonH5, nextButtonH5
        );
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HTakeChallengeJTabbedPane = new javax.swing.JTabbedPane();
        TCtabbedPane1H = new javax.swing.JPanel();
        instructionLabelTC1 = new javax.swing.JLabel();
        readButtonH1 = new javax.swing.JButton();
        clearButtonH1 = new javax.swing.JButton();
        hintButtonH1 = new javax.swing.JButton();
        textAreaH1 = new javax.swing.JTextArea();
        TButtonH1 = new javax.swing.JLabel();
        NButtonH1 = new javax.swing.JLabel();
        AButtonH1 = new javax.swing.JLabel();
        HButtonH1 = new javax.swing.JLabel();
        PButtonH1 = new javax.swing.JLabel();
        E2ButtonH1 = new javax.swing.JLabel();
        LButtonH1 = new javax.swing.JLabel();
        EButtonH1 = new javax.swing.JLabel();
        soundToggleButtonH1 = new javax.swing.JToggleButton();
        returnButtonH1 = new javax.swing.JLabel();
        nextButtonH1 = new javax.swing.JLabel();
        iconT1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        TCtabbedPane2H = new javax.swing.JPanel();
        instructionLabelTC2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        readButtonH2 = new javax.swing.JButton();
        clearButtonH2 = new javax.swing.JButton();
        hintButtonH2 = new javax.swing.JButton();
        textAreaH2 = new javax.swing.JTextArea();
        soundToggleButtonH2 = new javax.swing.JToggleButton();
        EButtonH2 = new javax.swing.JLabel();
        F2ButtonH2 = new javax.swing.JLabel();
        F1ButtonH2 = new javax.swing.JLabel();
        AButtonH2 = new javax.swing.JLabel();
        RButtonH2 = new javax.swing.JLabel();
        IButtonH2 = new javax.swing.JLabel();
        GButtonH2 = new javax.swing.JLabel();
        nextButtonH2 = new javax.swing.JLabel();
        iconT2 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        TCtabbedPane3H = new javax.swing.JPanel();
        instructionLabelTC3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        readButtonH3 = new javax.swing.JButton();
        clearButtonH3 = new javax.swing.JButton();
        hintButtonH3 = new javax.swing.JButton();
        nextButtonH3 = new javax.swing.JLabel();
        textAreaH3 = new javax.swing.JTextArea();
        soundToggleButtonH3 = new javax.swing.JToggleButton();
        S3ButtonH3 = new javax.swing.JLabel();
        EButtonH3 = new javax.swing.JLabel();
        S2ButtonH3 = new javax.swing.JLabel();
        S1ButtonH3 = new javax.swing.JLabel();
        AButtonH3 = new javax.swing.JLabel();
        LButtonH3 = new javax.swing.JLabel();
        GButtonH3 = new javax.swing.JLabel();
        iconT3 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        TCtabbedPane4H = new javax.swing.JPanel();
        instructionLabelTC4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        readButtonH4 = new javax.swing.JButton();
        clearButtonH4 = new javax.swing.JButton();
        hintButtonH4 = new javax.swing.JButton();
        nextButtonH4 = new javax.swing.JLabel();
        textAreaH4 = new javax.swing.JTextArea();
        soundToggleButtonH4 = new javax.swing.JToggleButton();
        A2ButtonH4 = new javax.swing.JLabel();
        RButtonH4 = new javax.swing.JLabel();
        EButtonH4 = new javax.swing.JLabel();
        MButtonH4 = new javax.swing.JLabel();
        A1ButtonH4 = new javax.swing.JLabel();
        CButtonH4 = new javax.swing.JLabel();
        iconT4 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();
        TCtabbedPane5H = new javax.swing.JPanel();
        instructionLabelTC5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        readButtonH5 = new javax.swing.JButton();
        clearButtonH5 = new javax.swing.JButton();
        hintButtonH5 = new javax.swing.JButton();
        textAreaH5 = new javax.swing.JTextArea();
        soundToggleButtonH5 = new javax.swing.JToggleButton();
        N2ButtonH5 = new javax.swing.JLabel();
        IButtonH5 = new javax.swing.JLabel();
        UButtonH5 = new javax.swing.JLabel();
        GButtonH5 = new javax.swing.JLabel();
        N1ButtonH5 = new javax.swing.JLabel();
        EButtonH5 = new javax.swing.JLabel();
        PButtonH5 = new javax.swing.JLabel();
        returnButtonH5 = new javax.swing.JLabel();
        nextButtonH5 = new javax.swing.JLabel();
        iconT5 = new javax.swing.JLabel();
        background4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TCtabbedPane1H.setBackground(new java.awt.Color(204, 204, 204));
        TCtabbedPane1H.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabelTC1.setFont(new java.awt.Font("Comic Sans MS", 0, 50)); // NOI18N
        instructionLabelTC1.setForeground(new java.awt.Color(0, 0, 0));
        instructionLabelTC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabelTC1.setText("Guess the Word");
        TCtabbedPane1H.add(instructionLabelTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

        readButtonH1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        readButtonH1.setText("Read");
        readButtonH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonH1ActionPerformed(evt);
            }
        });
        TCtabbedPane1H.add(readButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

        clearButtonH1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        clearButtonH1.setText("Clear");
        clearButtonH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonH1ActionPerformed(evt);
            }
        });
        TCtabbedPane1H.add(clearButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

        hintButtonH1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hintButtonH1.setText("Hint");
        hintButtonH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonH1ActionPerformed(evt);
            }
        });
        TCtabbedPane1H.add(hintButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

        textAreaH1.setEditable(false);
        textAreaH1.setColumns(20);
        textAreaH1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        textAreaH1.setRows(5);
        TCtabbedPane1H.add(textAreaH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 240, 80));

        TButtonH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/T button.png"))); // NOI18N
        TButtonH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TButtonH1MouseClicked(evt);
            }
        });
        TCtabbedPane1H.add(TButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        NButtonH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/N button.png"))); // NOI18N
        NButtonH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NButtonH1MouseClicked(evt);
            }
        });
        TCtabbedPane1H.add(NButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, -1, -1));

        AButtonH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/A button.png"))); // NOI18N
        AButtonH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AButtonH1MouseClicked(evt);
            }
        });
        TCtabbedPane1H.add(AButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        HButtonH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/H button.png"))); // NOI18N
        HButtonH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HButtonH1MouseClicked(evt);
            }
        });
        TCtabbedPane1H.add(HButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        PButtonH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/P button.png"))); // NOI18N
        PButtonH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PButtonH1MouseClicked(evt);
            }
        });
        TCtabbedPane1H.add(PButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, -1));

        E2ButtonH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/E button.png"))); // NOI18N
        E2ButtonH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E2ButtonH1MouseClicked(evt);
            }
        });
        TCtabbedPane1H.add(E2ButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        LButtonH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/L button.png"))); // NOI18N
        LButtonH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LButtonH1MouseClicked(evt);
            }
        });
        TCtabbedPane1H.add(LButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        EButtonH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/E button.png"))); // NOI18N
        EButtonH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EButtonH1MouseClicked(evt);
            }
        });
        TCtabbedPane1H.add(EButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        soundToggleButtonH1.setText("Sound");
        soundToggleButtonH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonH1ActionPerformed(evt);
            }
        });
        TCtabbedPane1H.add(soundToggleButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        returnButtonH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/back button.png"))); // NOI18N
        returnButtonH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonH1MouseClicked(evt);
            }
        });
        TCtabbedPane1H.add(returnButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        nextButtonH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/next button.png"))); // NOI18N
        nextButtonH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonH1MouseClicked(evt);
            }
        });
        TCtabbedPane1H.add(nextButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        iconT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/ELEPHANT.png"))); // NOI18N
        iconT1.setPreferredSize(new java.awt.Dimension(50, 15));
        TCtabbedPane1H.add(iconT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgbgbg.gif"))); // NOI18N
        TCtabbedPane1H.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 540));

        HTakeChallengeJTabbedPane.addTab("tab1", TCtabbedPane1H);

        TCtabbedPane2H.setBackground(new java.awt.Color(204, 204, 204));
        TCtabbedPane2H.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabelTC2.setFont(new java.awt.Font("Comic Sans MS", 0, 50)); // NOI18N
        instructionLabelTC2.setForeground(new java.awt.Color(0, 0, 0));
        instructionLabelTC2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabelTC2.setText("Guess the Word");
        TCtabbedPane2H.add(instructionLabelTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TCtabbedPane2H.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        readButtonH2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        readButtonH2.setText("Read");
        readButtonH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonH2ActionPerformed(evt);
            }
        });
        TCtabbedPane2H.add(readButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

        clearButtonH2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        clearButtonH2.setText("Clear");
        clearButtonH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonH2ActionPerformed(evt);
            }
        });
        TCtabbedPane2H.add(clearButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

        hintButtonH2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hintButtonH2.setText("Hint");
        hintButtonH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonH2ActionPerformed(evt);
            }
        });
        TCtabbedPane2H.add(hintButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

        textAreaH2.setEditable(false);
        textAreaH2.setColumns(20);
        textAreaH2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        textAreaH2.setRows(5);
        TCtabbedPane2H.add(textAreaH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

        soundToggleButtonH2.setText("Sound");
        soundToggleButtonH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonH2ActionPerformed(evt);
            }
        });
        TCtabbedPane2H.add(soundToggleButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        EButtonH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/E button.png"))); // NOI18N
        EButtonH2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EButtonH2MouseClicked(evt);
            }
        });
        TCtabbedPane2H.add(EButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, -1, -1));

        F2ButtonH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/F button.png"))); // NOI18N
        F2ButtonH2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F2ButtonH2MouseClicked(evt);
            }
        });
        TCtabbedPane2H.add(F2ButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        F1ButtonH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/F button.png"))); // NOI18N
        F1ButtonH2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F1ButtonH2MouseClicked(evt);
            }
        });
        TCtabbedPane2H.add(F1ButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));

        AButtonH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/A button.png"))); // NOI18N
        AButtonH2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AButtonH2MouseClicked(evt);
            }
        });
        TCtabbedPane2H.add(AButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        RButtonH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/R button.png"))); // NOI18N
        RButtonH2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RButtonH2MouseClicked(evt);
            }
        });
        TCtabbedPane2H.add(RButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        IButtonH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/I button.png"))); // NOI18N
        IButtonH2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IButtonH2MouseClicked(evt);
            }
        });
        TCtabbedPane2H.add(IButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        GButtonH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/G button.png"))); // NOI18N
        GButtonH2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GButtonH2MouseClicked(evt);
            }
        });
        TCtabbedPane2H.add(GButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        nextButtonH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/next button.png"))); // NOI18N
        nextButtonH2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonH2MouseClicked(evt);
            }
        });
        TCtabbedPane2H.add(nextButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        iconT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/GIRAFFE.png"))); // NOI18N
        iconT2.setPreferredSize(new java.awt.Dimension(50, 15));
        TCtabbedPane2H.add(iconT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgbgbg.gif"))); // NOI18N
        TCtabbedPane2H.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 590));

        HTakeChallengeJTabbedPane.addTab("tab2", TCtabbedPane2H);

        TCtabbedPane3H.setBackground(new java.awt.Color(204, 204, 204));
        TCtabbedPane3H.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabelTC3.setFont(new java.awt.Font("Comic Sans MS", 0, 50)); // NOI18N
        instructionLabelTC3.setForeground(new java.awt.Color(0, 0, 0));
        instructionLabelTC3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabelTC3.setText("Guess the Word");
        TCtabbedPane3H.add(instructionLabelTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TCtabbedPane3H.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        readButtonH3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        readButtonH3.setText("Read");
        readButtonH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonH3ActionPerformed(evt);
            }
        });
        TCtabbedPane3H.add(readButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

        clearButtonH3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        clearButtonH3.setText("Clear");
        clearButtonH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonH3ActionPerformed(evt);
            }
        });
        TCtabbedPane3H.add(clearButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

        hintButtonH3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hintButtonH3.setText("Hint");
        hintButtonH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonH3ActionPerformed(evt);
            }
        });
        TCtabbedPane3H.add(hintButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

        nextButtonH3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/next button.png"))); // NOI18N
        nextButtonH3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonH3MouseClicked(evt);
            }
        });
        TCtabbedPane3H.add(nextButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        textAreaH3.setEditable(false);
        textAreaH3.setColumns(20);
        textAreaH3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        textAreaH3.setRows(5);
        TCtabbedPane3H.add(textAreaH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

        soundToggleButtonH3.setText("Sound");
        soundToggleButtonH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonH3ActionPerformed(evt);
            }
        });
        TCtabbedPane3H.add(soundToggleButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        S3ButtonH3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/S button.png"))); // NOI18N
        S3ButtonH3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S3ButtonH3MouseClicked(evt);
            }
        });
        TCtabbedPane3H.add(S3ButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        EButtonH3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/E button.png"))); // NOI18N
        EButtonH3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EButtonH3MouseClicked(evt);
            }
        });
        TCtabbedPane3H.add(EButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        S2ButtonH3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/S button.png"))); // NOI18N
        S2ButtonH3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S2ButtonH3MouseClicked(evt);
            }
        });
        TCtabbedPane3H.add(S2ButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        S1ButtonH3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/S button.png"))); // NOI18N
        S1ButtonH3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S1ButtonH3MouseClicked(evt);
            }
        });
        TCtabbedPane3H.add(S1ButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, -1));

        AButtonH3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/A button.png"))); // NOI18N
        AButtonH3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AButtonH3MouseClicked(evt);
            }
        });
        TCtabbedPane3H.add(AButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        LButtonH3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/L button.png"))); // NOI18N
        LButtonH3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LButtonH3MouseClicked(evt);
            }
        });
        TCtabbedPane3H.add(LButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, -1, -1));

        GButtonH3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/G button.png"))); // NOI18N
        GButtonH3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GButtonH3MouseClicked(evt);
            }
        });
        TCtabbedPane3H.add(GButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        iconT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/GLASSES.png"))); // NOI18N
        iconT3.setPreferredSize(new java.awt.Dimension(50, 15));
        TCtabbedPane3H.add(iconT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgbgbg.gif"))); // NOI18N
        TCtabbedPane3H.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 590));

        HTakeChallengeJTabbedPane.addTab("tab3", TCtabbedPane3H);

        TCtabbedPane4H.setBackground(new java.awt.Color(204, 204, 204));
        TCtabbedPane4H.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabelTC4.setFont(new java.awt.Font("Comic Sans MS", 0, 50)); // NOI18N
        instructionLabelTC4.setForeground(new java.awt.Color(0, 0, 0));
        instructionLabelTC4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabelTC4.setText("Guess the Word");
        TCtabbedPane4H.add(instructionLabelTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TCtabbedPane4H.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        readButtonH4.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        readButtonH4.setText("Read");
        readButtonH4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonH4ActionPerformed(evt);
            }
        });
        TCtabbedPane4H.add(readButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

        clearButtonH4.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        clearButtonH4.setText("Clear");
        clearButtonH4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonH4ActionPerformed(evt);
            }
        });
        TCtabbedPane4H.add(clearButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

        hintButtonH4.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hintButtonH4.setText("Hint");
        hintButtonH4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonH4ActionPerformed(evt);
            }
        });
        TCtabbedPane4H.add(hintButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

        nextButtonH4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/next button.png"))); // NOI18N
        nextButtonH4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonH4MouseClicked(evt);
            }
        });
        TCtabbedPane4H.add(nextButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        textAreaH4.setEditable(false);
        textAreaH4.setColumns(20);
        textAreaH4.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        textAreaH4.setRows(5);
        TCtabbedPane4H.add(textAreaH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

        soundToggleButtonH4.setText("Sound");
        soundToggleButtonH4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonH4ActionPerformed(evt);
            }
        });
        TCtabbedPane4H.add(soundToggleButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        A2ButtonH4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/A button.png"))); // NOI18N
        A2ButtonH4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A2ButtonH4MouseClicked(evt);
            }
        });
        TCtabbedPane4H.add(A2ButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        RButtonH4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/R button.png"))); // NOI18N
        RButtonH4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RButtonH4MouseClicked(evt);
            }
        });
        TCtabbedPane4H.add(RButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        EButtonH4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/E button.png"))); // NOI18N
        EButtonH4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EButtonH4MouseClicked(evt);
            }
        });
        TCtabbedPane4H.add(EButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        MButtonH4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/M button.png"))); // NOI18N
        MButtonH4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MButtonH4MouseClicked(evt);
            }
        });
        TCtabbedPane4H.add(MButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        A1ButtonH4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/A button.png"))); // NOI18N
        A1ButtonH4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A1ButtonH4MouseClicked(evt);
            }
        });
        TCtabbedPane4H.add(A1ButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        CButtonH4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/C button.png"))); // NOI18N
        CButtonH4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CButtonH4MouseClicked(evt);
            }
        });
        TCtabbedPane4H.add(CButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        iconT4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/CAMERA.png"))); // NOI18N
        iconT4.setPreferredSize(new java.awt.Dimension(50, 15));
        TCtabbedPane4H.add(iconT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgbgbg.gif"))); // NOI18N
        TCtabbedPane4H.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 590));

        HTakeChallengeJTabbedPane.addTab("tab4", TCtabbedPane4H);

        TCtabbedPane5H.setBackground(new java.awt.Color(204, 204, 204));
        TCtabbedPane5H.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabelTC5.setFont(new java.awt.Font("Comic Sans MS", 0, 50)); // NOI18N
        instructionLabelTC5.setForeground(new java.awt.Color(0, 0, 0));
        instructionLabelTC5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabelTC5.setText("Guess the Word");
        TCtabbedPane5H.add(instructionLabelTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TCtabbedPane5H.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        readButtonH5.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        readButtonH5.setText("Read");
        readButtonH5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonH5ActionPerformed(evt);
            }
        });
        TCtabbedPane5H.add(readButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

        clearButtonH5.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        clearButtonH5.setText("Clear");
        clearButtonH5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonH5ActionPerformed(evt);
            }
        });
        TCtabbedPane5H.add(clearButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

        hintButtonH5.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hintButtonH5.setText("Hint");
        hintButtonH5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonH5ActionPerformed(evt);
            }
        });
        TCtabbedPane5H.add(hintButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

        textAreaH5.setEditable(false);
        textAreaH5.setColumns(20);
        textAreaH5.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        textAreaH5.setRows(5);
        TCtabbedPane5H.add(textAreaH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

        soundToggleButtonH5.setText("Sound");
        soundToggleButtonH5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonH5ActionPerformed(evt);
            }
        });
        TCtabbedPane5H.add(soundToggleButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        N2ButtonH5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/N button.png"))); // NOI18N
        N2ButtonH5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N2ButtonH5MouseClicked(evt);
            }
        });
        TCtabbedPane5H.add(N2ButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        IButtonH5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/I button.png"))); // NOI18N
        IButtonH5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IButtonH5MouseClicked(evt);
            }
        });
        TCtabbedPane5H.add(IButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, -1, -1));

        UButtonH5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/U button.png"))); // NOI18N
        UButtonH5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UButtonH5MouseClicked(evt);
            }
        });
        TCtabbedPane5H.add(UButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        GButtonH5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/G button.png"))); // NOI18N
        GButtonH5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GButtonH5MouseClicked(evt);
            }
        });
        TCtabbedPane5H.add(GButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        N1ButtonH5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/N button.png"))); // NOI18N
        N1ButtonH5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N1ButtonH5MouseClicked(evt);
            }
        });
        TCtabbedPane5H.add(N1ButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 110, -1));

        EButtonH5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/E button.png"))); // NOI18N
        EButtonH5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EButtonH5MouseClicked(evt);
            }
        });
        TCtabbedPane5H.add(EButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        PButtonH5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/P button.png"))); // NOI18N
        PButtonH5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PButtonH5MouseClicked(evt);
            }
        });
        TCtabbedPane5H.add(PButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        returnButtonH5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/back button.png"))); // NOI18N
        returnButtonH5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonH5MouseClicked(evt);
            }
        });
        TCtabbedPane5H.add(returnButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        nextButtonH5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/next button.png"))); // NOI18N
        nextButtonH5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonH5MouseClicked(evt);
            }
        });
        TCtabbedPane5H.add(nextButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        iconT5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/PENGUIN.png"))); // NOI18N
        iconT5.setPreferredSize(new java.awt.Dimension(50, 15));
        TCtabbedPane5H.add(iconT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgbgbg.gif"))); // NOI18N
        TCtabbedPane5H.add(background4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 590));

        HTakeChallengeJTabbedPane.addTab("tab5", TCtabbedPane5H);

        getContentPane().add(HTakeChallengeJTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -22, 780, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    String[] wordH1 = {"E", "L", "E", "P", "H", "A", "N", "T"};
    String[] wordH2 = {"G", "I", "R", "A", "F", "F", "E"};
    String[] wordH3 = {"G", "L", "A", "S", "S", "E", "S"};
    String[] wordH4 = {"C", "A", "M", "E", "R", "A"};
    String[] wordH5 = {"P", "E", "N", "G", "U", "I", "N"};

    //    Array of hint for each word
    String[] hints = {
            "It's the king of the jungle, with a long trunk and big ears.",
            "This animal has a neck as tall as a tree and loves munching on leaves.",
            "Put these on your face to help you see better.",
            "Capture memories with this device, whether in photos or videos!",
            "This bird might not fly, but it's a fantastic swimmer and loves the ocean."
    };


    private void readButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonH1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaH1, musicPlayer);
    }//GEN-LAST:event_readButtonH1ActionPerformed

    private void clearButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonH1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaH1);
    }//GEN-LAST:event_clearButtonH1ActionPerformed

    private void soundToggleButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonH1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonH1);
    }//GEN-LAST:event_soundToggleButtonH1ActionPerformed

    private void readButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonH2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaH2, musicPlayer);
    }//GEN-LAST:event_readButtonH2ActionPerformed

    private void clearButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonH2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaH2);
    }//GEN-LAST:event_clearButtonH2ActionPerformed

    private void IButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH2.append(wordH2[1]);
        ButtonActions.speak(wordH2[1], soundToggleButtonH2);
    }//GEN-LAST:event_PButtonH2ActionPerformed

    private void soundToggleButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonH2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonH2);
    }//GEN-LAST:event_soundToggleButtonH2ActionPerformed

    private void readButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonH3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaH3, musicPlayer);
    }//GEN-LAST:event_readButtonH3ActionPerformed

    private void clearButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonH3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaH3);
    }//GEN-LAST:event_clearButtonH3ActionPerformed

    private void soundToggleButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonH3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonH3);
    }//GEN-LAST:event_soundToggleButtonH3ActionPerformed

    private void readButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonH4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaH4, musicPlayer);
    }//GEN-LAST:event_readButtonH4ActionPerformed

    private void clearButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonH4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaH4);
    }//GEN-LAST:event_clearButtonH4ActionPerformed

    private void soundToggleButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonH4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonH4);
    }//GEN-LAST:event_soundToggleButtonH4ActionPerformed

    private void readButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonH5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaH5, musicPlayer);
    }//GEN-LAST:event_readButtonH5ActionPerformed

    private void clearButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonH5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaH5);
    }//GEN-LAST:event_clearButtonH5ActionPerformed

    private void soundToggleButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonH5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonH5);
    }//GEN-LAST:event_soundToggleButtonH5ActionPerformed

    private void EButtonH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EButtonH1MouseClicked
        // TODO add your handling code here:
        textAreaH1.append(wordH1[0]);
        ButtonActions.speak(wordH1[0], soundToggleButtonH1);
    }//GEN-LAST:event_EButtonH1MouseClicked

    private void LButtonH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LButtonH1MouseClicked
        // TODO add your handling code here:
        textAreaH1.append(wordH1[1]);
        ButtonActions.speak(wordH1[1], soundToggleButtonH1);
    }//GEN-LAST:event_LButtonH1MouseClicked

    private void E2ButtonH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E2ButtonH1MouseClicked
        // TODO add your handling code here:
        textAreaH1.append(wordH1[2]);
        ButtonActions.speak(wordH1[2], soundToggleButtonH1);
    }//GEN-LAST:event_E2ButtonH1MouseClicked

    private void PButtonH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PButtonH1MouseClicked
        // TODO add your handling code here:
        textAreaH1.append(wordH1[3]);
        ButtonActions.speak(wordH1[3], soundToggleButtonH1);
    }//GEN-LAST:event_PButtonH1MouseClicked

    private void HButtonH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HButtonH1MouseClicked
        // TODO add your handling code here:
        textAreaH1.append(wordH1[4]);
        ButtonActions.speak(wordH1[4], soundToggleButtonH1);
    }//GEN-LAST:event_HButtonH1MouseClicked

    private void AButtonH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AButtonH1MouseClicked
        // TODO add your handling code here:
        textAreaH1.append(wordH1[5]);
        ButtonActions.speak(wordH1[5], soundToggleButtonH1);
    }//GEN-LAST:event_AButtonH1MouseClicked

    private void NButtonH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NButtonH1MouseClicked
        // TODO add your handling code here:
        textAreaH1.append(wordH1[6]);
        ButtonActions.speak(wordH1[6], soundToggleButtonH1);
    }//GEN-LAST:event_NButtonH1MouseClicked

    private void TButtonH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TButtonH1MouseClicked
        // TODO add your handling code here:
        textAreaH1.append(wordH1[7]);
        ButtonActions.speak(wordH1[7], soundToggleButtonH1);
    }//GEN-LAST:event_TButtonH1MouseClicked

    private void returnButtonH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonH1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new TakeChallengeAssessment().setVisible(true);
    }//GEN-LAST:event_returnButtonH1MouseClicked

    private void nextButtonH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonH1MouseClicked
        // TODO add your handling code here:
        String userAnswer = textAreaH1.getText().trim();
        ButtonActions.checkAnswerAndNext(wordH1, userAnswer, HTakeChallengeJTabbedPane, textAreaH1, false);
    }//GEN-LAST:event_nextButtonH1MouseClicked

    private void GButtonH2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GButtonH2MouseClicked
        // TODO add your handling code here:
        textAreaH2.append(wordH2[0]);
        ButtonActions.speak(wordH2[0], soundToggleButtonH2);
    }//GEN-LAST:event_GButtonH2MouseClicked

    private void IButtonH2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IButtonH2MouseClicked
        // TODO add your handling code here:
        textAreaH2.append(wordH2[1]);
        ButtonActions.speak(wordH2[1], soundToggleButtonH2);
    }//GEN-LAST:event_IButtonH2MouseClicked

    private void RButtonH2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RButtonH2MouseClicked
        // TODO add your handling code here:
        textAreaH2.append(wordH2[2]);
        ButtonActions.speak(wordH2[2], soundToggleButtonH2);
    }//GEN-LAST:event_RButtonH2MouseClicked

    private void AButtonH2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AButtonH2MouseClicked
        // TODO add your handling code here:
        textAreaH2.append(wordH2[3]);
        ButtonActions.speak(wordH2[3], soundToggleButtonH2);
    }//GEN-LAST:event_AButtonH2MouseClicked

    private void F1ButtonH2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F1ButtonH2MouseClicked
        // TODO add your handling code here:
        textAreaH2.append(wordH2[4]);
        ButtonActions.speak(wordH2[4], soundToggleButtonH2);
    }//GEN-LAST:event_F1ButtonH2MouseClicked

    private void F2ButtonH2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F2ButtonH2MouseClicked
        // TODO add your handling code here:
        textAreaH2.append(wordH2[5]);
        ButtonActions.speak(wordH2[5], soundToggleButtonH2);
    }//GEN-LAST:event_F2ButtonH2MouseClicked

    private void EButtonH2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EButtonH2MouseClicked
        // TODO add your handling code here:
        textAreaH2.append(wordH2[6]);
        ButtonActions.speak(wordH2[6], soundToggleButtonH2);
    }//GEN-LAST:event_EButtonH2MouseClicked

    private void nextButtonH2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonH2MouseClicked
        // TODO add your handling code here:
        String userAnswer = textAreaH2.getText().trim();
        ButtonActions.checkAnswerAndNext(wordH2, userAnswer, HTakeChallengeJTabbedPane, textAreaH2, false);
    }//GEN-LAST:event_nextButtonH2MouseClicked

    private void GButtonH3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GButtonH3MouseClicked
        // TODO add your handling code here:
        textAreaH3.append(wordH3[0]);
        ButtonActions.speak(wordH3[0], soundToggleButtonH3);
    }//GEN-LAST:event_GButtonH3MouseClicked

    private void LButtonH3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LButtonH3MouseClicked
        // TODO add your handling code here:
        textAreaH3.append(wordH3[1]);
        ButtonActions.speak(wordH3[1], soundToggleButtonH3);
    }//GEN-LAST:event_LButtonH3MouseClicked

    private void AButtonH3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AButtonH3MouseClicked
        // TODO add your handling code here:
        textAreaH3.append(wordH3[2]);
        ButtonActions.speak(wordH3[2], soundToggleButtonH3);
    }//GEN-LAST:event_AButtonH3MouseClicked

    private void S1ButtonH3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S1ButtonH3MouseClicked
        // TODO add your handling code here:
        textAreaH3.append(wordH3[3]);
        ButtonActions.speak(wordH3[3], soundToggleButtonH3);
    }//GEN-LAST:event_S1ButtonH3MouseClicked

    private void S2ButtonH3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S2ButtonH3MouseClicked
        // TODO add your handling code here:
        textAreaH3.append(wordH3[4]);
        ButtonActions.speak(wordH3[4], soundToggleButtonH3);
    }//GEN-LAST:event_S2ButtonH3MouseClicked

    private void EButtonH3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EButtonH3MouseClicked
        // TODO add your handling code here:
        textAreaH3.append(wordH3[5]);
        ButtonActions.speak(wordH3[5], soundToggleButtonH3);
    }//GEN-LAST:event_EButtonH3MouseClicked

    private void S3ButtonH3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S3ButtonH3MouseClicked
        // TODO add your handling code here:
        textAreaH3.append(wordH3[6]);
        ButtonActions.speak(wordH3[6], soundToggleButtonH3);
    }//GEN-LAST:event_S3ButtonH3MouseClicked

    private void nextButtonH3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonH3MouseClicked
        // TODO add your handling code here:
        String userAnswer = textAreaH3.getText().trim();
        ButtonActions.checkAnswerAndNext(wordH3, userAnswer, HTakeChallengeJTabbedPane, textAreaH3, false);
    }//GEN-LAST:event_nextButtonH3MouseClicked

    private void CButtonH4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CButtonH4MouseClicked
        // TODO add your handling code here:
        textAreaH4.append(wordH4[0]);
        ButtonActions.speak(wordH4[0], soundToggleButtonH4);
    }//GEN-LAST:event_CButtonH4MouseClicked

    private void A1ButtonH4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1ButtonH4MouseClicked
        // TODO add your handling code here:
        textAreaH4.append(wordH4[1]);
        ButtonActions.speak(wordH4[1], soundToggleButtonH4);
    }//GEN-LAST:event_A1ButtonH4MouseClicked

    private void MButtonH4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MButtonH4MouseClicked
        // TODO add your handling code here:
        textAreaH4.append(wordH4[2]);
        ButtonActions.speak(wordH4[2], soundToggleButtonH4);
    }//GEN-LAST:event_MButtonH4MouseClicked

    private void EButtonH4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EButtonH4MouseClicked
        // TODO add your handling code here:
        textAreaH4.append(wordH4[3]);
        ButtonActions.speak(wordH4[3], soundToggleButtonH4);
    }//GEN-LAST:event_EButtonH4MouseClicked

    private void RButtonH4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RButtonH4MouseClicked
        // TODO add your handling code here:
        textAreaH4.append(wordH4[4]);
        ButtonActions.speak(wordH4[4], soundToggleButtonH4);
    }//GEN-LAST:event_RButtonH4MouseClicked

    private void A2ButtonH4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2ButtonH4MouseClicked
        // TODO add your handling code here:
        textAreaH4.append(wordH4[5]);
        ButtonActions.speak(wordH4[5], soundToggleButtonH4);
    }//GEN-LAST:event_A2ButtonH4MouseClicked

    private void nextButtonH4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonH4MouseClicked
        // TODO add your handling code here:
        String userAnswer = textAreaH4.getText().trim();
        ButtonActions.checkAnswerAndNext(wordH4, userAnswer, HTakeChallengeJTabbedPane, textAreaH4, false);
    }//GEN-LAST:event_nextButtonH4MouseClicked

    private void nextButtonH5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonH5MouseClicked
        // TODO add your handling code here:
        String userAnswer = textAreaH5.getText().trim();
        ButtonActions.checkAnswerAndNext(wordH5, userAnswer, HTakeChallengeJTabbedPane, textAreaH5, false);
    }//GEN-LAST:event_nextButtonH5MouseClicked

    private void returnButtonH5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonH5MouseClicked
        // TODO add your handling code here:
        TakeChallengeAssessment takeChallengeAssessment = new TakeChallengeAssessment();
        takeChallengeAssessment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnButtonH5MouseClicked

    private void PButtonH5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PButtonH5MouseClicked
        // TODO add your handling code here:
        textAreaH5.append(wordH5[0]);
        ButtonActions.speak(wordH5[0], soundToggleButtonH5);
    }//GEN-LAST:event_PButtonH5MouseClicked

    private void EButtonH5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EButtonH5MouseClicked
        // TODO add your handling code here:
        textAreaH5.append(wordH5[1]);
        ButtonActions.speak(wordH5[1], soundToggleButtonH5);
    }//GEN-LAST:event_EButtonH5MouseClicked

    private void N1ButtonH5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N1ButtonH5MouseClicked
        // TODO add your handling code here:
        textAreaH5.append(wordH5[2]);
        ButtonActions.speak(wordH5[2], soundToggleButtonH5);
    }//GEN-LAST:event_N1ButtonH5MouseClicked

    private void GButtonH5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GButtonH5MouseClicked
        // TODO add your handling code here:
        textAreaH5.append(wordH5[3]);
        ButtonActions.speak(wordH5[3], soundToggleButtonH5);
    }//GEN-LAST:event_GButtonH5MouseClicked

    private void UButtonH5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UButtonH5MouseClicked
        // TODO add your handling code here:
        textAreaH5.append(wordH5[4]);
        ButtonActions.speak(wordH5[4], soundToggleButtonH5);
    }//GEN-LAST:event_UButtonH5MouseClicked

    private void IButtonH5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IButtonH5MouseClicked
        // TODO add your handling code here:
        textAreaH5.append(wordH5[5]);
        ButtonActions.speak(wordH5[5], soundToggleButtonH5);
    }//GEN-LAST:event_IButtonH5MouseClicked

    private void N2ButtonH5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N2ButtonH5MouseClicked
        // TODO add your handling code here:
        textAreaH5.append(wordH5[6]);
        ButtonActions.speak(wordH5[6], soundToggleButtonH5);
    }//GEN-LAST:event_N2ButtonH5MouseClicked

    private void hintButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonH1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, hints[0], "Hint", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_hintButtonH1ActionPerformed

    private void hintButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonH2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, hints[1], "Hint", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_hintButtonH2ActionPerformed

    private void hintButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonH3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, hints[2], "Hint", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_hintButtonH3ActionPerformed

    private void hintButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonH4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, hints[3], "Hint", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_hintButtonH4ActionPerformed

    private void hintButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonH5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, hints[4], "Hint", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_hintButtonH5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HardTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HardTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HardTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HardTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HardTakeChallenge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1ButtonH4;
    private javax.swing.JLabel A2ButtonH4;
    private javax.swing.JLabel AButtonH1;
    private javax.swing.JLabel AButtonH2;
    private javax.swing.JLabel AButtonH3;
    private javax.swing.JLabel CButtonH4;
    private javax.swing.JLabel E2ButtonH1;
    private javax.swing.JLabel EButtonH1;
    private javax.swing.JLabel EButtonH2;
    private javax.swing.JLabel EButtonH3;
    private javax.swing.JLabel EButtonH4;
    private javax.swing.JLabel EButtonH5;
    private javax.swing.JLabel F1ButtonH2;
    private javax.swing.JLabel F2ButtonH2;
    private javax.swing.JLabel GButtonH2;
    private javax.swing.JLabel GButtonH3;
    private javax.swing.JLabel GButtonH5;
    private javax.swing.JLabel HButtonH1;
    private javax.swing.JTabbedPane HTakeChallengeJTabbedPane;
    private javax.swing.JLabel IButtonH2;
    private javax.swing.JLabel IButtonH5;
    private javax.swing.JLabel LButtonH1;
    private javax.swing.JLabel LButtonH3;
    private javax.swing.JLabel MButtonH4;
    private javax.swing.JLabel N1ButtonH5;
    private javax.swing.JLabel N2ButtonH5;
    private javax.swing.JLabel NButtonH1;
    private javax.swing.JLabel PButtonH1;
    private javax.swing.JLabel PButtonH5;
    private javax.swing.JLabel RButtonH2;
    private javax.swing.JLabel RButtonH4;
    private javax.swing.JLabel S1ButtonH3;
    private javax.swing.JLabel S2ButtonH3;
    private javax.swing.JLabel S3ButtonH3;
    private javax.swing.JLabel TButtonH1;
    private javax.swing.JPanel TCtabbedPane1H;
    private javax.swing.JPanel TCtabbedPane2H;
    private javax.swing.JPanel TCtabbedPane3H;
    private javax.swing.JPanel TCtabbedPane4H;
    private javax.swing.JPanel TCtabbedPane5H;
    private javax.swing.JLabel UButtonH5;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JButton clearButtonH1;
    private javax.swing.JButton clearButtonH2;
    private javax.swing.JButton clearButtonH3;
    private javax.swing.JButton clearButtonH4;
    private javax.swing.JButton clearButtonH5;
    private javax.swing.JButton hintButtonH1;
    private javax.swing.JButton hintButtonH2;
    private javax.swing.JButton hintButtonH3;
    private javax.swing.JButton hintButtonH4;
    private javax.swing.JButton hintButtonH5;
    private javax.swing.JLabel iconT1;
    private javax.swing.JLabel iconT2;
    private javax.swing.JLabel iconT3;
    private javax.swing.JLabel iconT4;
    private javax.swing.JLabel iconT5;
    private javax.swing.JLabel instructionLabelTC1;
    private javax.swing.JLabel instructionLabelTC2;
    private javax.swing.JLabel instructionLabelTC3;
    private javax.swing.JLabel instructionLabelTC4;
    private javax.swing.JLabel instructionLabelTC5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel nextButtonH1;
    private javax.swing.JLabel nextButtonH2;
    private javax.swing.JLabel nextButtonH3;
    private javax.swing.JLabel nextButtonH4;
    private javax.swing.JLabel nextButtonH5;
    private javax.swing.JButton readButtonH1;
    private javax.swing.JButton readButtonH2;
    private javax.swing.JButton readButtonH3;
    private javax.swing.JButton readButtonH4;
    private javax.swing.JButton readButtonH5;
    private javax.swing.JLabel returnButtonH1;
    private javax.swing.JLabel returnButtonH5;
    private javax.swing.JToggleButton soundToggleButtonH1;
    private javax.swing.JToggleButton soundToggleButtonH2;
    private javax.swing.JToggleButton soundToggleButtonH3;
    private javax.swing.JToggleButton soundToggleButtonH4;
    private javax.swing.JToggleButton soundToggleButtonH5;
    private javax.swing.JTextArea textAreaH1;
    private javax.swing.JTextArea textAreaH2;
    private javax.swing.JTextArea textAreaH3;
    private javax.swing.JTextArea textAreaH4;
    private javax.swing.JTextArea textAreaH5;
    // End of variables declaration//GEN-END:variables
}
