/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Core.AssessmentPage.TakeChallengeModeOfDifficulty;

import Core.Actions.ButtonActions;
import Core.AssessmentPage.TakeChallengeAssessment;

import javax.swing.*;

/**
 * @author Marc
 */
public class HardTakeChallenge extends javax.swing.JFrame {

    /**
     * Creates new form HardTakeChallenge
     */
    public HardTakeChallenge() {
        initComponents();

            ImageIcon originalIcon = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/ELEPHANT.png"));
            ImageIcon icon = new ImageIcon(originalIcon.getImage().getScaledInstance(iconT1.getWidth(), iconT1.getHeight(), java.awt.Image.SCALE_SMOOTH));
            iconT1.setIcon(icon);

            ImageIcon originalIcon2 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/GIRAFFE.png"));
            ImageIcon icon2 = new ImageIcon(originalIcon2.getImage().getScaledInstance(iconT2.getWidth(), iconT2.getHeight(), java.awt.Image.SCALE_SMOOTH));
            iconT2.setIcon(icon2);

            ImageIcon originalIcon3 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/GLASSES.png"));
            ImageIcon icon3 = new ImageIcon(originalIcon3.getImage().getScaledInstance(iconT3.getWidth(), iconT3.getHeight(), java.awt.Image.SCALE_SMOOTH));
            iconT3.setIcon(icon3);

            ImageIcon originalIcon4 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/CAMERA.png"));
            ImageIcon icon4 = new ImageIcon(originalIcon4.getImage().getScaledInstance(iconT4.getWidth(), iconT4.getHeight(), java.awt.Image.SCALE_SMOOTH));
            iconT4.setIcon(icon4);

            ImageIcon originalIcon5 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/PENGUIN.png"));
            ImageIcon icon5 = new ImageIcon(originalIcon5.getImage().getScaledInstance(iconT5.getWidth(), iconT5.getHeight(), java.awt.Image.SCALE_SMOOTH));
            iconT5.setIcon(icon5);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                HTakeChallengeJTabbedPane = new javax.swing.JTabbedPane();
                TCtabbedPane1H = new javax.swing.JPanel();
                instructionLabelTC1 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                readButtonH1 = new javax.swing.JButton();
                clearButtonH1 = new javax.swing.JButton();
                hintButtonH1 = new javax.swing.JButton();
                AButtonH1 = new javax.swing.JButton();
                PButtonH1 = new javax.swing.JButton();
                LButtonH1 = new javax.swing.JButton();
                EButtonH1 = new javax.swing.JButton();
                nextButtonH1 = new javax.swing.JButton();
                TButtonH1 = new javax.swing.JButton();
                textAreaH1 = new javax.swing.JTextArea();
                soundToggleButtonH1 = new javax.swing.JToggleButton();
                returnButtonH1 = new javax.swing.JButton();
                E2ButtonH1 = new javax.swing.JButton();
                NButtonH1 = new javax.swing.JButton();
                HButtonH1 = new javax.swing.JButton();
                iconT1 = new javax.swing.JLabel();
                TCtabbedPane2H = new javax.swing.JPanel();
                instructionLabelTC2 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                readButtonH2 = new javax.swing.JButton();
                clearButtonH2 = new javax.swing.JButton();
                hintButtonH2 = new javax.swing.JButton();
                F2ButtonH2 = new javax.swing.JButton();
                IButtonH2 = new javax.swing.JButton();
                EButtonH2 = new javax.swing.JButton();
                RButtonH2 = new javax.swing.JButton();
                nextButtonH2 = new javax.swing.JButton();
                textAreaH2 = new javax.swing.JTextArea();
                soundToggleButtonH2 = new javax.swing.JToggleButton();
                F1ButtonH2 = new javax.swing.JButton();
                GButtonH2 = new javax.swing.JButton();
                AButtonH2 = new javax.swing.JButton();
                iconT2 = new javax.swing.JLabel();
                TCtabbedPane3H = new javax.swing.JPanel();
                instructionLabelTC3 = new javax.swing.JLabel();
                jPanel5 = new javax.swing.JPanel();
                readButtonH3 = new javax.swing.JButton();
                clearButtonH3 = new javax.swing.JButton();
                hintButtonH3 = new javax.swing.JButton();
                S2ButtonH3 = new javax.swing.JButton();
                GButtonH3 = new javax.swing.JButton();
                EButtonH3 = new javax.swing.JButton();
                S1ButtonH3 = new javax.swing.JButton();
                nextButtonH3 = new javax.swing.JButton();
                textAreaH3 = new javax.swing.JTextArea();
                soundToggleButtonH3 = new javax.swing.JToggleButton();
                S3ButtonH3 = new javax.swing.JButton();
                AButtonH3 = new javax.swing.JButton();
                LButtonH3 = new javax.swing.JButton();
                iconT3 = new javax.swing.JLabel();
                TCtabbedPane4H = new javax.swing.JPanel();
                instructionLabelTC4 = new javax.swing.JLabel();
                jPanel7 = new javax.swing.JPanel();
                readButtonH4 = new javax.swing.JButton();
                clearButtonH4 = new javax.swing.JButton();
                hintButtonH4 = new javax.swing.JButton();
                RButtonH4 = new javax.swing.JButton();
                CButtonH4 = new javax.swing.JButton();
                MButtonH4 = new javax.swing.JButton();
                EButtonH4 = new javax.swing.JButton();
                nextButtonH4 = new javax.swing.JButton();
                textAreaH4 = new javax.swing.JTextArea();
                soundToggleButtonH4 = new javax.swing.JToggleButton();
                A1ButtonH4 = new javax.swing.JButton();
                A2ButtonH4 = new javax.swing.JButton();
                iconT4 = new javax.swing.JLabel();
                TCtabbedPane5H = new javax.swing.JPanel();
                instructionLabelTC5 = new javax.swing.JLabel();
                jPanel9 = new javax.swing.JPanel();
                readButtonH5 = new javax.swing.JButton();
                clearButtonH5 = new javax.swing.JButton();
                hintButtonH5 = new javax.swing.JButton();
                GButtonH5 = new javax.swing.JButton();
                UButtonH5 = new javax.swing.JButton();
                PButtonH5 = new javax.swing.JButton();
                N1ButtonH5 = new javax.swing.JButton();
                nextButtonH5 = new javax.swing.JButton();
                textAreaH5 = new javax.swing.JTextArea();
                soundToggleButtonH5 = new javax.swing.JToggleButton();
                N2ButtonH5 = new javax.swing.JButton();
                IButtonH6 = new javax.swing.JButton();
                EButtonH6 = new javax.swing.JButton();
                returnButtonH5 = new javax.swing.JButton();
                iconT5 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                TCtabbedPane1H.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane1H.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC1.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC1.setText("Guess the Word");
                TCtabbedPane1H.add(instructionLabelTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane1H.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonH1.setText("Read");
                readButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(readButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonH1.setText("Clear");
                clearButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(clearButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonH1.setText("Hint");
                TCtabbedPane1H.add(hintButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                AButtonH1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                AButtonH1.setText("A");
                AButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(AButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 98, 67));

                PButtonH1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                PButtonH1.setText("P");
                PButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                PButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(PButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 98, 67));

                LButtonH1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                LButtonH1.setText("L");
                LButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(LButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 98, 67));

                EButtonH1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                EButtonH1.setText("E");
                EButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(EButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 98, 67));

                nextButtonH1.setText("Next");
                nextButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(nextButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                TButtonH1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                TButtonH1.setText("T");
                TButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(TButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 98, 67));

                textAreaH1.setEditable(false);
                textAreaH1.setColumns(20);
                textAreaH1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaH1.setRows(5);
                TCtabbedPane1H.add(textAreaH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 240, 80));

                soundToggleButtonH1.setText("Sound");
                soundToggleButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(soundToggleButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                returnButtonH1.setText("Return");
                returnButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                returnButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(returnButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 485, 73, -1));

                E2ButtonH1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                E2ButtonH1.setText("E");
                E2ButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                E2ButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(E2ButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 98, 67));

                NButtonH1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                NButtonH1.setText("N");
                NButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                NButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(NButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 98, 67));

                HButtonH1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                HButtonH1.setText("H");
                HButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                HButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(HButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 98, 67));

                iconT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/ELEPHANT.png"))); // NOI18N
                iconT1.setPreferredSize(new java.awt.Dimension(50, 15));
                TCtabbedPane1H.add(iconT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

                HTakeChallengeJTabbedPane.addTab("tab1", TCtabbedPane1H);

                TCtabbedPane2H.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane2H.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC2.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC2.setText("Guess the Word");
                TCtabbedPane2H.add(instructionLabelTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane2H.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonH2.setText("Read");
                readButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2H.add(readButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonH2.setText("Clear");
                clearButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2H.add(clearButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonH2.setText("Hint");
                TCtabbedPane2H.add(hintButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                F2ButtonH2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                F2ButtonH2.setText("F");
                F2ButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                F2ButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2H.add(F2ButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 98, 67));

                IButtonH2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                IButtonH2.setText("I");
                IButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                IButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2H.add(IButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 98, 67));

                EButtonH2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                EButtonH2.setText("E");
                EButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2H.add(EButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 98, 67));

                RButtonH2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                RButtonH2.setText("R");
                RButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                RButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2H.add(RButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 98, 67));

                nextButtonH2.setText("Next");
                nextButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2H.add(nextButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                textAreaH2.setEditable(false);
                textAreaH2.setColumns(20);
                textAreaH2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaH2.setRows(5);
                TCtabbedPane2H.add(textAreaH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

                soundToggleButtonH2.setText("Sound");
                soundToggleButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2H.add(soundToggleButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                F1ButtonH2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                F1ButtonH2.setText("F");
                F1ButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                F1ButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2H.add(F1ButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 98, 67));

                GButtonH2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                GButtonH2.setText("G");
                GButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                GButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2H.add(GButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 98, 67));

                AButtonH2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                AButtonH2.setText("A");
                AButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2H.add(AButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 98, 67));

                iconT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/GIRAFFE.png"))); // NOI18N
                iconT2.setPreferredSize(new java.awt.Dimension(50, 15));
                TCtabbedPane2H.add(iconT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

                HTakeChallengeJTabbedPane.addTab("tab2", TCtabbedPane2H);

                TCtabbedPane3H.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane3H.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC3.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC3.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC3.setText("Guess the Word");
                TCtabbedPane3H.add(instructionLabelTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane3H.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonH3.setText("Read");
                readButtonH3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonH3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3H.add(readButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonH3.setText("Clear");
                clearButtonH3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonH3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3H.add(clearButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonH3.setText("Hint");
                TCtabbedPane3H.add(hintButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                S2ButtonH3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                S2ButtonH3.setText("S");
                S2ButtonH3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                S2ButtonH3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3H.add(S2ButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 98, 67));

                GButtonH3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                GButtonH3.setText("G");
                GButtonH3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                GButtonH3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3H.add(GButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 98, 67));

                EButtonH3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                EButtonH3.setText("E");
                EButtonH3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EButtonH3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3H.add(EButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 98, 67));

                S1ButtonH3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                S1ButtonH3.setText("S");
                S1ButtonH3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                S1ButtonH3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3H.add(S1ButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 98, 67));

                nextButtonH3.setText("Next");
                nextButtonH3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonH3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3H.add(nextButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                textAreaH3.setEditable(false);
                textAreaH3.setColumns(20);
                textAreaH3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaH3.setRows(5);
                TCtabbedPane3H.add(textAreaH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

                soundToggleButtonH3.setText("Sound");
                soundToggleButtonH3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonH3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3H.add(soundToggleButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                S3ButtonH3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                S3ButtonH3.setText("S");
                S3ButtonH3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                S3ButtonH3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3H.add(S3ButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 98, 67));

                AButtonH3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                AButtonH3.setText("A");
                AButtonH3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AButtonH3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3H.add(AButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 98, 67));

                LButtonH3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                LButtonH3.setText("L");
                LButtonH3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LButtonH3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3H.add(LButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 98, 67));

                iconT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/GLASSES.png"))); // NOI18N
                iconT3.setPreferredSize(new java.awt.Dimension(50, 15));
                TCtabbedPane3H.add(iconT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

                HTakeChallengeJTabbedPane.addTab("tab3", TCtabbedPane3H);

                TCtabbedPane4H.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane4H.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC4.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC4.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC4.setText("Guess the Word");
                TCtabbedPane4H.add(instructionLabelTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel7Layout.setVerticalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane4H.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonH4.setText("Read");
                readButtonH4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonH4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4H.add(readButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonH4.setText("Clear");
                clearButtonH4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonH4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4H.add(clearButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonH4.setText("Hint");
                TCtabbedPane4H.add(hintButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                RButtonH4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                RButtonH4.setText("R");
                RButtonH4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                RButtonH4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4H.add(RButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 98, 67));

                CButtonH4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                CButtonH4.setText("C");
                CButtonH4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CButtonH4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4H.add(CButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 98, 67));

                MButtonH4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                MButtonH4.setText("M");
                MButtonH4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                MButtonH4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4H.add(MButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 98, 67));

                EButtonH4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                EButtonH4.setText("E");
                EButtonH4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EButtonH4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4H.add(EButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 98, 67));

                nextButtonH4.setText("Next");
                nextButtonH4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonH4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4H.add(nextButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                textAreaH4.setEditable(false);
                textAreaH4.setColumns(20);
                textAreaH4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaH4.setRows(5);
                TCtabbedPane4H.add(textAreaH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

                soundToggleButtonH4.setText("Sound");
                soundToggleButtonH4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonH4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4H.add(soundToggleButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                A1ButtonH4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                A1ButtonH4.setText("A");
                A1ButtonH4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                A1ButtonH4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4H.add(A1ButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 98, 67));

                A2ButtonH4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                A2ButtonH4.setText("A");
                A2ButtonH4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                A2ButtonH4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4H.add(A2ButtonH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 98, 67));

                iconT4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/CAMERA.png"))); // NOI18N
                iconT4.setPreferredSize(new java.awt.Dimension(50, 15));
                TCtabbedPane4H.add(iconT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

                HTakeChallengeJTabbedPane.addTab("tab4", TCtabbedPane4H);

                TCtabbedPane5H.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane5H.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC5.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC5.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC5.setText("Guess the Word");
                TCtabbedPane5H.add(instructionLabelTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
                jPanel9.setLayout(jPanel9Layout);
                jPanel9Layout.setHorizontalGroup(
                        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel9Layout.setVerticalGroup(
                        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane5H.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonH5.setText("Read");
                readButtonH5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonH5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5H.add(readButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonH5.setText("Clear");
                clearButtonH5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonH5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5H.add(clearButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonH5.setText("Hint");
                TCtabbedPane5H.add(hintButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                GButtonH5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                GButtonH5.setText("G");
                GButtonH5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                GButtonH5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5H.add(GButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 98, 67));

                UButtonH5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                UButtonH5.setText("U");
                UButtonH5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                UButtonH5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5H.add(UButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 98, 67));

                PButtonH5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                PButtonH5.setText("P");
                PButtonH5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                PButtonH5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5H.add(PButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 98, 67));

                N1ButtonH5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                N1ButtonH5.setText("N");
                N1ButtonH5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                N1ButtonH5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5H.add(N1ButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 98, 67));

                nextButtonH5.setText("Next");
                nextButtonH5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonH5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5H.add(nextButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                textAreaH5.setEditable(false);
                textAreaH5.setColumns(20);
                textAreaH5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaH5.setRows(5);
                TCtabbedPane5H.add(textAreaH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

                soundToggleButtonH5.setText("Sound");
                soundToggleButtonH5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonH5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5H.add(soundToggleButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                N2ButtonH5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                N2ButtonH5.setText("N");
                N2ButtonH5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                N2ButtonH5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5H.add(N2ButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 98, 67));

                IButtonH6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                IButtonH6.setText("I");
                IButtonH6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                IButtonH6ActionPerformed(evt);
                        }
                });
                TCtabbedPane5H.add(IButtonH6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 98, 67));

                EButtonH6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                EButtonH6.setText("E");
                EButtonH6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EButtonH6ActionPerformed(evt);
                        }
                });
                TCtabbedPane5H.add(EButtonH6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 98, 67));

                returnButtonH5.setText("Return");
                returnButtonH5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                returnButtonH5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5H.add(returnButtonH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 485, 73, -1));

                iconT5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/PENGUIN.png"))); // NOI18N
                iconT5.setPreferredSize(new java.awt.Dimension(50, 15));
                TCtabbedPane5H.add(iconT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

                HTakeChallengeJTabbedPane.addTab("tab5", TCtabbedPane5H);

                getContentPane().add(HTakeChallengeJTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -22, 780, 570));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    String[] wordH1 = {"E", "L", "E", "P", "H", "A", "N", "T"};
    String[] wordH2 = {"G", "I", "R", "A", "F", "F", "E"};
    String[] wordH3 = {"G", "L", "A", "S", "S", "E", "S"};
    String[] wordH4 = {"C", "A", "M", "E", "R", "A"};
    String[] wordH5 = {"P", "E", "N", "G", "U", "I", "N"};

    private void readButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonH1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaH1);
    }//GEN-LAST:event_readButtonH1ActionPerformed

    private void clearButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonH1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaH1);
    }//GEN-LAST:event_clearButtonH1ActionPerformed

    private void AButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonH1ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[5]);
        ButtonActions.speak(wordH1[5], soundToggleButtonH1);
    }//GEN-LAST:event_AButtonH1ActionPerformed

    private void PButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PButtonH1ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[3]);
        ButtonActions.speak(wordH1[3], soundToggleButtonH1);
    }//GEN-LAST:event_PButtonH1ActionPerformed

    private void LButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButtonH1ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[1]);
        ButtonActions.speak(wordH1[1], soundToggleButtonH1);
    }//GEN-LAST:event_LButtonH1ActionPerformed

    private void EButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonH1ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[0]);
        ButtonActions.speak(wordH1[0], soundToggleButtonH1);
    }//GEN-LAST:event_EButtonH1ActionPerformed

    private void nextButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonH1ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaH1.getText().trim();
        ButtonActions.checkAnswerAndNext(wordH1, userAnswer, HTakeChallengeJTabbedPane, textAreaH1, false);
    }//GEN-LAST:event_nextButtonH1ActionPerformed

    private void TButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TButtonH1ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[7]);
        ButtonActions.speak(wordH1[7], soundToggleButtonH1);
    }//GEN-LAST:event_TButtonH1ActionPerformed

    private void soundToggleButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonH1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonH1);
    }//GEN-LAST:event_soundToggleButtonH1ActionPerformed

    private void returnButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonH1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TakeChallengeAssessment().setVisible(true);
    }//GEN-LAST:event_returnButtonH1ActionPerformed

    private void E2ButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2ButtonH1ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[2]);
        ButtonActions.speak(wordH1[2], soundToggleButtonH1);
    }//GEN-LAST:event_E2ButtonH1ActionPerformed

    private void NButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NButtonH1ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[6]);
        ButtonActions.speak(wordH1[6], soundToggleButtonH1);
    }//GEN-LAST:event_NButtonH1ActionPerformed

    private void HButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HButtonH1ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[4]);
        ButtonActions.speak(wordH1[4], soundToggleButtonH1);
    }//GEN-LAST:event_HButtonH1ActionPerformed

    private void readButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonH2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaH2);
    }//GEN-LAST:event_readButtonH2ActionPerformed

    private void clearButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonH2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaH2);
    }//GEN-LAST:event_clearButtonH2ActionPerformed

    private void F2ButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F2ButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH2.append(wordH2[5]);
        ButtonActions.speak(wordH2[5], soundToggleButtonH2);
    }//GEN-LAST:event_F2ButtonH2ActionPerformed

    private void IButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH2.append(wordH2[1]);
        ButtonActions.speak(wordH2[1], soundToggleButtonH2);
    }//GEN-LAST:event_PButtonH2ActionPerformed

    private void EButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH2.append(wordH2[6]);
        ButtonActions.speak(wordH2[6], soundToggleButtonH2);
    }//GEN-LAST:event_EButtonH2ActionPerformed

    private void RButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH2.append(wordH2[2]);
        ButtonActions.speak(wordH2[2], soundToggleButtonH2);
    }//GEN-LAST:event_RButtonH2ActionPerformed

    private void nextButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonH2ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaH2.getText().trim();
        ButtonActions.checkAnswerAndNext(wordH2, userAnswer, HTakeChallengeJTabbedPane, textAreaH2, false);
    }//GEN-LAST:event_nextButtonH2ActionPerformed

    private void soundToggleButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonH2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonH2);
    }//GEN-LAST:event_soundToggleButtonH2ActionPerformed

    private void F1ButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH2.append(wordH2[4]);
        ButtonActions.speak(wordH2[4], soundToggleButtonH2);
    }//GEN-LAST:event_F1ButtonH2ActionPerformed

    private void GButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH2.append(wordH2[0]);
        ButtonActions.speak(wordH2[0], soundToggleButtonH2);
    }//GEN-LAST:event_GButtonH2ActionPerformed

    private void AButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH2.append(wordH2[3]);
        ButtonActions.speak(wordH2[3], soundToggleButtonH2);
    }//GEN-LAST:event_AButtonH2ActionPerformed

    private void readButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonH3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaH3);
    }//GEN-LAST:event_readButtonH3ActionPerformed

    private void clearButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonH3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaH3);
    }//GEN-LAST:event_clearButtonH3ActionPerformed

    private void S2ButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S2ButtonH3ActionPerformed
        // TODO add your handling code here:
        textAreaH3.append(wordH3[4]);
        ButtonActions.speak(wordH3[4], soundToggleButtonH3);
    }//GEN-LAST:event_S2ButtonH3ActionPerformed

    private void GButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GButtonH3ActionPerformed
        // TODO add your handling code here:
        textAreaH3.append(wordH3[0]);
        ButtonActions.speak(wordH3[0], soundToggleButtonH3);
    }//GEN-LAST:event_GButtonH3ActionPerformed

    private void EButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonH3ActionPerformed
        // TODO add your handling code here:
        textAreaH3.append(wordH3[5]);
        ButtonActions.speak(wordH3[5], soundToggleButtonH3);
    }//GEN-LAST:event_EButtonH3ActionPerformed

    private void S1ButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S1ButtonH3ActionPerformed
        // TODO add your handling code here:
        textAreaH3.append(wordH3[3]);
        ButtonActions.speak(wordH3[3], soundToggleButtonH3);
    }//GEN-LAST:event_S1ButtonH3ActionPerformed

    private void nextButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonH3ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaH3.getText().trim();
        ButtonActions.checkAnswerAndNext(wordH3, userAnswer, HTakeChallengeJTabbedPane, textAreaH3, false);
    }//GEN-LAST:event_nextButtonH3ActionPerformed

    private void soundToggleButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonH3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonH3);
    }//GEN-LAST:event_soundToggleButtonH3ActionPerformed

    private void S3ButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S3ButtonH3ActionPerformed
        // TODO add your handling code here:
        textAreaH3.append(wordH3[6]);
        ButtonActions.speak(wordH3[6], soundToggleButtonH3);
    }//GEN-LAST:event_S3ButtonH3ActionPerformed

    private void AButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonH3ActionPerformed
        // TODO add your handling code here:
        textAreaH3.append(wordH3[2]);
        ButtonActions.speak(wordH3[2], soundToggleButtonH3);
    }//GEN-LAST:event_AButtonH3ActionPerformed

    private void LButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButtonH3ActionPerformed
        // TODO add your handling code here:
        textAreaH3.append(wordH3[1]);
        ButtonActions.speak(wordH3[1], soundToggleButtonH3);
    }//GEN-LAST:event_LButtonH3ActionPerformed

    private void readButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonH4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaH4);
    }//GEN-LAST:event_readButtonH4ActionPerformed

    private void clearButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonH4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaH4);
    }//GEN-LAST:event_clearButtonH4ActionPerformed

    private void RButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonH4ActionPerformed
        // TODO add your handling code here:
        textAreaH4.append(wordH4[4]);
        ButtonActions.speak(wordH4[4], soundToggleButtonH4);
    }//GEN-LAST:event_RButtonH4ActionPerformed

    private void CButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CButtonH4ActionPerformed
        // TODO add your handling code here:
        textAreaH4.append(wordH4[0]);
        ButtonActions.speak(wordH4[0], soundToggleButtonH4);
    }//GEN-LAST:event_CButtonH4ActionPerformed

    private void MButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MButtonH4ActionPerformed
        // TODO add your handling code here:
        textAreaH4.append(wordH4[2]);
        ButtonActions.speak(wordH4[2], soundToggleButtonH4);
    }//GEN-LAST:event_MButtonH4ActionPerformed

    private void EButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonH4ActionPerformed
        // TODO add your handling code here:
        textAreaH4.append(wordH4[3]);
        ButtonActions.speak(wordH4[3], soundToggleButtonH4);
    }//GEN-LAST:event_EButtonH4ActionPerformed

    private void nextButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonH4ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaH4.getText().trim();
        ButtonActions.checkAnswerAndNext(wordH4, userAnswer, HTakeChallengeJTabbedPane, textAreaH4, false);
    }//GEN-LAST:event_nextButtonH4ActionPerformed

    private void soundToggleButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonH4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonH4);
    }//GEN-LAST:event_soundToggleButtonH4ActionPerformed

    private void A1ButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ButtonH4ActionPerformed
        // TODO add your handling code here:
        textAreaH4.append(wordH4[1]);
        ButtonActions.speak(wordH4[1], soundToggleButtonH4);
    }//GEN-LAST:event_A1ButtonH4ActionPerformed

    private void A2ButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ButtonH4ActionPerformed
        // TODO add your handling code here:
        textAreaH4.append(wordH4[5]);
        ButtonActions.speak(wordH4[5], soundToggleButtonH4);
    }//GEN-LAST:event_A2ButtonH4ActionPerformed

    private void readButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonH5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaH5);
    }//GEN-LAST:event_readButtonH5ActionPerformed

    private void clearButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonH5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaH5);
    }//GEN-LAST:event_clearButtonH5ActionPerformed

    private void GButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GButtonH5ActionPerformed
        // TODO add your handling code here:
        textAreaH5.append(wordH5[3]);
        ButtonActions.speak(wordH5[3], soundToggleButtonH5);
    }//GEN-LAST:event_GButtonH5ActionPerformed

    private void UButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UButtonH5ActionPerformed
        // TODO add your handling code here:
        textAreaH5.append(wordH5[4]);
        ButtonActions.speak(wordH5[4], soundToggleButtonH5);
    }//GEN-LAST:event_UButtonH5ActionPerformed

    private void PButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PButtonH5ActionPerformed
        // TODO add your handling code here:
        textAreaH5.append(wordH5[0]);
        ButtonActions.speak(wordH5[0], soundToggleButtonH5);
    }//GEN-LAST:event_PButtonH5ActionPerformed

    private void N1ButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N1ButtonH5ActionPerformed
        // TODO add your handling code here:
        textAreaH5.append(wordH5[2]);
        ButtonActions.speak(wordH5[2], soundToggleButtonH5);
    }//GEN-LAST:event_N1ButtonH5ActionPerformed

    private void nextButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonH5ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaH5.getText().trim();
        ButtonActions.checkAnswerAndNext(wordH5, userAnswer, HTakeChallengeJTabbedPane, textAreaH5, false);
    }//GEN-LAST:event_nextButtonH5ActionPerformed

    private void soundToggleButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonH5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonH5);
    }//GEN-LAST:event_soundToggleButtonH5ActionPerformed

    private void N2ButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N2ButtonH5ActionPerformed
        // TODO add your handling code here:
        textAreaH5.append(wordH5[6]);
        ButtonActions.speak(wordH5[6], soundToggleButtonH5);
    }//GEN-LAST:event_N2ButtonH5ActionPerformed

    private void IButtonH6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IButtonH6ActionPerformed
        // TODO add your handling code here:
        textAreaH5.append(wordH5[5]);
        ButtonActions.speak(wordH5[5], soundToggleButtonH5);
    }//GEN-LAST:event_IButtonH6ActionPerformed

    private void EButtonH6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonH6ActionPerformed
        // TODO add your handling code here:
        textAreaH5.append(wordH5[1]);
        ButtonActions.speak(wordH5[1], soundToggleButtonH5);
    }//GEN-LAST:event_EButtonH6ActionPerformed

        private void returnButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonH5ActionPerformed
                // TODO add your handling code here:
		TakeChallengeAssessment takeChallengeAssessment = new TakeChallengeAssessment();
		takeChallengeAssessment.setVisible(true);
		this.dispose();
        }//GEN-LAST:event_returnButtonH5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HardTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HardTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HardTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HardTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HardTakeChallenge().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton A1ButtonH4;
        private javax.swing.JButton A2ButtonH4;
        private javax.swing.JButton AButtonH1;
        private javax.swing.JButton AButtonH2;
        private javax.swing.JButton AButtonH3;
        private javax.swing.JButton CButtonH4;
        private javax.swing.JButton E2ButtonH1;
        private javax.swing.JButton EButtonH1;
        private javax.swing.JButton EButtonH2;
        private javax.swing.JButton EButtonH3;
        private javax.swing.JButton EButtonH4;
        private javax.swing.JButton EButtonH6;
        private javax.swing.JButton F1ButtonH2;
        private javax.swing.JButton F2ButtonH2;
        private javax.swing.JButton GButtonH2;
        private javax.swing.JButton GButtonH3;
        private javax.swing.JButton GButtonH5;
        private javax.swing.JButton HButtonH1;
        private javax.swing.JTabbedPane HTakeChallengeJTabbedPane;
        private javax.swing.JButton IButtonH2;
        private javax.swing.JButton IButtonH6;
        private javax.swing.JButton LButtonH1;
        private javax.swing.JButton LButtonH3;
        private javax.swing.JButton MButtonH4;
        private javax.swing.JButton N1ButtonH5;
        private javax.swing.JButton N2ButtonH5;
        private javax.swing.JButton NButtonH1;
        private javax.swing.JButton PButtonH1;
        private javax.swing.JButton PButtonH5;
        private javax.swing.JButton RButtonH2;
        private javax.swing.JButton RButtonH4;
        private javax.swing.JButton S1ButtonH3;
        private javax.swing.JButton S2ButtonH3;
        private javax.swing.JButton S3ButtonH3;
        private javax.swing.JButton TButtonH1;
        private javax.swing.JPanel TCtabbedPane1H;
        private javax.swing.JPanel TCtabbedPane2H;
        private javax.swing.JPanel TCtabbedPane3H;
        private javax.swing.JPanel TCtabbedPane4H;
        private javax.swing.JPanel TCtabbedPane5H;
        private javax.swing.JButton UButtonH5;
        private javax.swing.JButton clearButtonH1;
        private javax.swing.JButton clearButtonH2;
        private javax.swing.JButton clearButtonH3;
        private javax.swing.JButton clearButtonH4;
        private javax.swing.JButton clearButtonH5;
        private javax.swing.JButton hintButtonH1;
        private javax.swing.JButton hintButtonH2;
        private javax.swing.JButton hintButtonH3;
        private javax.swing.JButton hintButtonH4;
        private javax.swing.JButton hintButtonH5;
        private javax.swing.JLabel iconT1;
        private javax.swing.JLabel iconT2;
        private javax.swing.JLabel iconT3;
        private javax.swing.JLabel iconT4;
        private javax.swing.JLabel iconT5;
        private javax.swing.JLabel instructionLabelTC1;
        private javax.swing.JLabel instructionLabelTC2;
        private javax.swing.JLabel instructionLabelTC3;
        private javax.swing.JLabel instructionLabelTC4;
        private javax.swing.JLabel instructionLabelTC5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel jPanel9;
        private javax.swing.JButton nextButtonH1;
        private javax.swing.JButton nextButtonH2;
        private javax.swing.JButton nextButtonH3;
        private javax.swing.JButton nextButtonH4;
        private javax.swing.JButton nextButtonH5;
        private javax.swing.JButton readButtonH1;
        private javax.swing.JButton readButtonH2;
        private javax.swing.JButton readButtonH3;
        private javax.swing.JButton readButtonH4;
        private javax.swing.JButton readButtonH5;
        private javax.swing.JButton returnButtonH1;
        private javax.swing.JButton returnButtonH5;
        private javax.swing.JToggleButton soundToggleButtonH1;
        private javax.swing.JToggleButton soundToggleButtonH2;
        private javax.swing.JToggleButton soundToggleButtonH3;
        private javax.swing.JToggleButton soundToggleButtonH4;
        private javax.swing.JToggleButton soundToggleButtonH5;
        private javax.swing.JTextArea textAreaH1;
        private javax.swing.JTextArea textAreaH2;
        private javax.swing.JTextArea textAreaH3;
        private javax.swing.JTextArea textAreaH4;
        private javax.swing.JTextArea textAreaH5;
        // End of variables declaration//GEN-END:variables
}
