/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Core.AssessmentPage.TakeChallengeModeOfDifficulty;

import Core.Actions.ButtonActions;
import Core.AssessmentPage.TakeChallengeAssessment;
import Utilities.MusicPlayer;

import javax.swing.*;
import java.awt.*;

/**
 * @author Marc
 */
public class IntermediateTakeChallenge extends javax.swing.JFrame {

    private MusicPlayer musicPlayer;

    /**
     * Creates new form IntermediateTakeChallenge
     */
    public IntermediateTakeChallenge() {
        initComponents();

        musicPlayer = MusicPlayer.getInstance();

        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/WATCH.png"));
        ImageIcon icon = new ImageIcon(originalIcon.getImage().getScaledInstance(iconT1.getWidth(), iconT1.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT1.setIcon(icon);

        ImageIcon originalIcon2 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/SQUIRREL.png"));
        ImageIcon icon2 = new ImageIcon(originalIcon2.getImage().getScaledInstance(iconT2.getWidth(), iconT2.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT2.setIcon(icon2);

        ImageIcon originalIcon3 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/CASTLE.png"));
        ImageIcon icon3 = new ImageIcon(originalIcon3.getImage().getScaledInstance(iconT3.getWidth(), iconT3.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT3.setIcon(icon3);

        ImageIcon originalIcon4 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/DRAGON.png"));
        ImageIcon icon4 = new ImageIcon(originalIcon4.getImage().getScaledInstance(iconT4.getWidth(), iconT4.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT4.setIcon(icon4);

        ImageIcon originalIcon5 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/GUITAR.png"));
        ImageIcon icon5 = new ImageIcon(originalIcon5.getImage().getScaledInstance(iconT5.getWidth(), iconT5.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT5.setIcon(icon5);

        ButtonActions.setCursorForButtons(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR),
                WButtonI1, AButtonI1, TButtonI1, CButtonI1, HButtonI1, returnButtonI1, nextButtonI1,
                SButtonI2, QButtonI2, UButtonI2, IButtonI2, R1ButtonI2, R2ButtonI2, EButtonI2, LButtonI2, nextButtonI2,
                CButtonI3, AButtonI3, SButtonI3, TButtonI3, EButtonI3, LButtonI3, nextButtonI3,
                DButtonI4, RButtonI4, AButtonI4, GButtonI4, OButtonI4, NButtonI4, nextButtonI4,
                RButtonI5, AButtonI5, TButtonI5, IButtonI5, UButtonI5, GButtonI5, returnButtonI5, nextButtonI5
        );
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ITakeChallengeJTabbedPane = new javax.swing.JTabbedPane();
        TCtabbedPane1I = new javax.swing.JPanel();
        instructionLabelTC1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        readButtonI1 = new javax.swing.JButton();
        clearButtonI1 = new javax.swing.JButton();
        hintButtonI1 = new javax.swing.JButton();
        HButtonI1 = new javax.swing.JLabel();
        CButtonI1 = new javax.swing.JLabel();
        TButtonI1 = new javax.swing.JLabel();
        AButtonI1 = new javax.swing.JLabel();
        WButtonI1 = new javax.swing.JLabel();
        textAreaI1 = new javax.swing.JTextArea();
        soundToggleButtonI1 = new javax.swing.JToggleButton();
        returnButtonI1 = new javax.swing.JLabel();
        nextButtonI1 = new javax.swing.JLabel();
        iconT1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        TCtabbedPane2I = new javax.swing.JPanel();
        instructionLabelTC2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        readButtonI2 = new javax.swing.JButton();
        clearButtonI2 = new javax.swing.JButton();
        hintButtonI2 = new javax.swing.JButton();
        nextButtonI2 = new javax.swing.JLabel();
        textAreaI2 = new javax.swing.JTextArea();
        soundToggleButtonI2 = new javax.swing.JToggleButton();
        LButtonI2 = new javax.swing.JLabel();
        EButtonI2 = new javax.swing.JLabel();
        R2ButtonI2 = new javax.swing.JLabel();
        R1ButtonI2 = new javax.swing.JLabel();
        IButtonI2 = new javax.swing.JLabel();
        UButtonI2 = new javax.swing.JLabel();
        QButtonI2 = new javax.swing.JLabel();
        SButtonI2 = new javax.swing.JLabel();
        iconT2 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        TCtabbedPane3I = new javax.swing.JPanel();
        instructionLabelTC6 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        readButtonI3 = new javax.swing.JButton();
        clearButtonI3 = new javax.swing.JButton();
        hintButtonI3 = new javax.swing.JButton();
        nextButtonI3 = new javax.swing.JLabel();
        textAreaI3 = new javax.swing.JTextArea();
        soundToggleButtonI3 = new javax.swing.JToggleButton();
        EButtonI3 = new javax.swing.JLabel();
        LButtonI3 = new javax.swing.JLabel();
        TButtonI3 = new javax.swing.JLabel();
        SButtonI3 = new javax.swing.JLabel();
        AButtonI3 = new javax.swing.JLabel();
        CButtonI3 = new javax.swing.JLabel();
        iconT3 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        TCtabbedPane4I = new javax.swing.JPanel();
        instructionLabelTC7 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        readButtonI4 = new javax.swing.JButton();
        clearButtonI4 = new javax.swing.JButton();
        hintButtonI4 = new javax.swing.JButton();
        nextButtonI4 = new javax.swing.JLabel();
        textAreaI4 = new javax.swing.JTextArea();
        soundToggleButtonI4 = new javax.swing.JToggleButton();
        NButtonI4 = new javax.swing.JLabel();
        OButtonI4 = new javax.swing.JLabel();
        GButtonI4 = new javax.swing.JLabel();
        AButtonI4 = new javax.swing.JLabel();
        RButtonI4 = new javax.swing.JLabel();
        DButtonI4 = new javax.swing.JLabel();
        iconT4 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();
        TCtabbedPane5I = new javax.swing.JPanel();
        instructionLabelTC8 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        readButtonI5 = new javax.swing.JButton();
        clearButtonI5 = new javax.swing.JButton();
        hintButtonI5 = new javax.swing.JButton();
        textAreaI5 = new javax.swing.JTextArea();
        soundToggleButtonI5 = new javax.swing.JToggleButton();
        RButtonI5 = new javax.swing.JLabel();
        AButtonI5 = new javax.swing.JLabel();
        TButtonI5 = new javax.swing.JLabel();
        IButtonI5 = new javax.swing.JLabel();
        UButtonI5 = new javax.swing.JLabel();
        GButtonI5 = new javax.swing.JLabel();
        returnButtonI5 = new javax.swing.JLabel();
        nextButtonI5 = new javax.swing.JLabel();
        iconT5 = new javax.swing.JLabel();
        background4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TCtabbedPane1I.setBackground(new java.awt.Color(204, 204, 204));
        TCtabbedPane1I.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabelTC1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        instructionLabelTC1.setForeground(new java.awt.Color(0, 0, 0));
        instructionLabelTC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabelTC1.setText("Guess the Word");
        TCtabbedPane1I.add(instructionLabelTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        TCtabbedPane1I.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        readButtonI1.setText("Read");
        readButtonI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonI1ActionPerformed(evt);
            }
        });
        TCtabbedPane1I.add(readButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 73, -1));

        clearButtonI1.setText("Clear");
        clearButtonI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonI1ActionPerformed(evt);
            }
        });
        TCtabbedPane1I.add(clearButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 73, -1));

        hintButtonI1.setText("Hint");
        TCtabbedPane1I.add(hintButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 73, -1));

        HButtonI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/H button.png"))); // NOI18N
        HButtonI1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HButtonI1MouseClicked(evt);
            }
        });
        TCtabbedPane1I.add(HButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        CButtonI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/C button.png"))); // NOI18N
        CButtonI1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CButtonI1MouseClicked(evt);
            }
        });
        TCtabbedPane1I.add(CButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        TButtonI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/T button.png"))); // NOI18N
        TButtonI1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TButtonI1MouseClicked(evt);
            }
        });
        TCtabbedPane1I.add(TButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        AButtonI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/A button.png"))); // NOI18N
        AButtonI1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AButtonI1MouseClicked(evt);
            }
        });
        TCtabbedPane1I.add(AButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        WButtonI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/W Button.png"))); // NOI18N
        WButtonI1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WButtonI1MouseClicked(evt);
            }
        });
        TCtabbedPane1I.add(WButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        textAreaI1.setEditable(false);
        textAreaI1.setColumns(20);
        textAreaI1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textAreaI1.setRows(5);
        TCtabbedPane1I.add(textAreaI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 320, 70));

        soundToggleButtonI1.setText("Sound");
        soundToggleButtonI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonI1ActionPerformed(evt);
            }
        });
        TCtabbedPane1I.add(soundToggleButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        returnButtonI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/back button.png"))); // NOI18N
        returnButtonI1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonI1MouseClicked(evt);
            }
        });
        TCtabbedPane1I.add(returnButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        nextButtonI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/next button.png"))); // NOI18N
        nextButtonI1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonI1MouseClicked(evt);
            }
        });
        TCtabbedPane1I.add(nextButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, -1, -1));

        iconT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/WATCH.png"))); // NOI18N
        iconT1.setPreferredSize(new java.awt.Dimension(50, 15));
        TCtabbedPane1I.add(iconT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgbgbg.gif"))); // NOI18N
        TCtabbedPane1I.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 590));

        ITakeChallengeJTabbedPane.addTab("tab1", TCtabbedPane1I);

        TCtabbedPane2I.setBackground(new java.awt.Color(204, 204, 204));
        TCtabbedPane2I.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabelTC2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        instructionLabelTC2.setForeground(new java.awt.Color(0, 0, 0));
        instructionLabelTC2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabelTC2.setText("Guess the Word");
        TCtabbedPane2I.add(instructionLabelTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        TCtabbedPane2I.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        readButtonI2.setText("Read");
        readButtonI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonI2ActionPerformed(evt);
            }
        });
        TCtabbedPane2I.add(readButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

        clearButtonI2.setText("Clear");
        clearButtonI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonI2ActionPerformed(evt);
            }
        });
        TCtabbedPane2I.add(clearButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

        hintButtonI2.setText("Hint");
        TCtabbedPane2I.add(hintButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

        nextButtonI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/next button.png"))); // NOI18N
        nextButtonI2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonI2MouseClicked(evt);
            }
        });
        TCtabbedPane2I.add(nextButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        textAreaI2.setEditable(false);
        textAreaI2.setColumns(20);
        textAreaI2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textAreaI2.setRows(5);
        TCtabbedPane2I.add(textAreaI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

        soundToggleButtonI2.setText("Sound");
        soundToggleButtonI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonI2ActionPerformed(evt);
            }
        });
        TCtabbedPane2I.add(soundToggleButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        LButtonI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/L button.png"))); // NOI18N
        LButtonI2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LButtonI2MouseClicked(evt);
            }
        });
        TCtabbedPane2I.add(LButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        EButtonI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/E button.png"))); // NOI18N
        EButtonI2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EButtonI2MouseClicked(evt);
            }
        });
        TCtabbedPane2I.add(EButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        R2ButtonI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/R button.png"))); // NOI18N
        R2ButtonI2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                R2ButtonI2MouseClicked(evt);
            }
        });
        TCtabbedPane2I.add(R2ButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, -1, -1));

        R1ButtonI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/R button.png"))); // NOI18N
        R1ButtonI2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                R1ButtonI2MouseClicked(evt);
            }
        });
        TCtabbedPane2I.add(R1ButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        IButtonI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/I button.png"))); // NOI18N
        IButtonI2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IButtonI2MouseClicked(evt);
            }
        });
        TCtabbedPane2I.add(IButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, -1));

        UButtonI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/U button.png"))); // NOI18N
        UButtonI2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UButtonI2MouseClicked(evt);
            }
        });
        TCtabbedPane2I.add(UButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, -1, -1));

        QButtonI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/Q button.png"))); // NOI18N
        QButtonI2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QButtonI2MouseClicked(evt);
            }
        });
        TCtabbedPane2I.add(QButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        SButtonI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/S button.png"))); // NOI18N
        SButtonI2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SButtonI2MouseClicked(evt);
            }
        });
        TCtabbedPane2I.add(SButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        iconT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/SQUIRREL.png"))); // NOI18N
        iconT2.setPreferredSize(new java.awt.Dimension(50, 15));
        TCtabbedPane2I.add(iconT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgbgbg.gif"))); // NOI18N
        TCtabbedPane2I.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 590));

        ITakeChallengeJTabbedPane.addTab("tab2", TCtabbedPane2I);

        TCtabbedPane3I.setBackground(new java.awt.Color(204, 204, 204));
        TCtabbedPane3I.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabelTC6.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        instructionLabelTC6.setForeground(new java.awt.Color(0, 0, 0));
        instructionLabelTC6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabelTC6.setText("Guess the Word");
        TCtabbedPane3I.add(instructionLabelTC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        TCtabbedPane3I.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        readButtonI3.setText("Read");
        readButtonI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonI3ActionPerformed(evt);
            }
        });
        TCtabbedPane3I.add(readButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

        clearButtonI3.setText("Clear");
        clearButtonI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonI3ActionPerformed(evt);
            }
        });
        TCtabbedPane3I.add(clearButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

        hintButtonI3.setText("Hint");
        TCtabbedPane3I.add(hintButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

        nextButtonI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/next button.png"))); // NOI18N
        nextButtonI3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonI3MouseClicked(evt);
            }
        });
        TCtabbedPane3I.add(nextButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        textAreaI3.setEditable(false);
        textAreaI3.setColumns(20);
        textAreaI3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textAreaI3.setRows(5);
        TCtabbedPane3I.add(textAreaI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

        soundToggleButtonI3.setText("Sound");
        soundToggleButtonI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonI3ActionPerformed(evt);
            }
        });
        TCtabbedPane3I.add(soundToggleButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        EButtonI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/E button.png"))); // NOI18N
        EButtonI3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EButtonI3MouseClicked(evt);
            }
        });
        TCtabbedPane3I.add(EButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        LButtonI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/L button.png"))); // NOI18N
        LButtonI3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LButtonI3MouseClicked(evt);
            }
        });
        TCtabbedPane3I.add(LButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        TButtonI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/T button.png"))); // NOI18N
        TButtonI3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TButtonI3MouseClicked(evt);
            }
        });
        TCtabbedPane3I.add(TButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        SButtonI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/S button.png"))); // NOI18N
        SButtonI3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SButtonI3MouseClicked(evt);
            }
        });
        TCtabbedPane3I.add(SButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, -1));

        AButtonI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/A button.png"))); // NOI18N
        AButtonI3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AButtonI3MouseClicked(evt);
            }
        });
        TCtabbedPane3I.add(AButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, -1));

        CButtonI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/C button.png"))); // NOI18N
        CButtonI3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CButtonI3MouseClicked(evt);
            }
        });
        TCtabbedPane3I.add(CButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        iconT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/CASTLE.png"))); // NOI18N
        iconT3.setPreferredSize(new java.awt.Dimension(50, 15));
        TCtabbedPane3I.add(iconT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgbgbg.gif"))); // NOI18N
        TCtabbedPane3I.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 590));

        ITakeChallengeJTabbedPane.addTab("tab3", TCtabbedPane3I);

        TCtabbedPane4I.setBackground(new java.awt.Color(204, 204, 204));
        TCtabbedPane4I.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabelTC7.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        instructionLabelTC7.setForeground(new java.awt.Color(0, 0, 0));
        instructionLabelTC7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabelTC7.setText("Guess the Word");
        TCtabbedPane4I.add(instructionLabelTC7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        TCtabbedPane4I.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        readButtonI4.setText("Read");
        readButtonI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonI4ActionPerformed(evt);
            }
        });
        TCtabbedPane4I.add(readButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

        clearButtonI4.setText("Clear");
        clearButtonI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonI4ActionPerformed(evt);
            }
        });
        TCtabbedPane4I.add(clearButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

        hintButtonI4.setText("Hint");
        TCtabbedPane4I.add(hintButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

        nextButtonI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/next button.png"))); // NOI18N
        nextButtonI4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonI4MouseClicked(evt);
            }
        });
        TCtabbedPane4I.add(nextButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        textAreaI4.setEditable(false);
        textAreaI4.setColumns(20);
        textAreaI4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textAreaI4.setRows(5);
        TCtabbedPane4I.add(textAreaI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

        soundToggleButtonI4.setText("Sound");
        soundToggleButtonI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonI4ActionPerformed(evt);
            }
        });
        TCtabbedPane4I.add(soundToggleButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        NButtonI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/N button.png"))); // NOI18N
        NButtonI4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NButtonI4MouseClicked(evt);
            }
        });
        TCtabbedPane4I.add(NButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        OButtonI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/O button.png"))); // NOI18N
        OButtonI4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OButtonI4MouseClicked(evt);
            }
        });
        TCtabbedPane4I.add(OButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        GButtonI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/G button.png"))); // NOI18N
        GButtonI4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GButtonI4MouseClicked(evt);
            }
        });
        TCtabbedPane4I.add(GButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        AButtonI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/A button.png"))); // NOI18N
        AButtonI4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AButtonI4MouseClicked(evt);
            }
        });
        TCtabbedPane4I.add(AButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        RButtonI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/R button.png"))); // NOI18N
        RButtonI4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RButtonI4MouseClicked(evt);
            }
        });
        TCtabbedPane4I.add(RButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, -1));

        DButtonI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/D button.png"))); // NOI18N
        DButtonI4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DButtonI4MouseClicked(evt);
            }
        });
        TCtabbedPane4I.add(DButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, -1, -1));

        iconT4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/DRAGON.png"))); // NOI18N
        iconT4.setPreferredSize(new java.awt.Dimension(50, 15));
        TCtabbedPane4I.add(iconT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgbgbg.gif"))); // NOI18N
        TCtabbedPane4I.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 590));

        ITakeChallengeJTabbedPane.addTab("tab4", TCtabbedPane4I);

        TCtabbedPane5I.setBackground(new java.awt.Color(204, 204, 204));
        TCtabbedPane5I.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabelTC8.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        instructionLabelTC8.setForeground(new java.awt.Color(0, 0, 0));
        instructionLabelTC8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabelTC8.setText("Guess the Word");
        TCtabbedPane5I.add(instructionLabelTC8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        TCtabbedPane5I.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        readButtonI5.setText("Read");
        readButtonI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonI5ActionPerformed(evt);
            }
        });
        TCtabbedPane5I.add(readButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

        clearButtonI5.setText("Clear");
        clearButtonI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonI5ActionPerformed(evt);
            }
        });
        TCtabbedPane5I.add(clearButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

        hintButtonI5.setText("Hint");
        TCtabbedPane5I.add(hintButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

        textAreaI5.setEditable(false);
        textAreaI5.setColumns(20);
        textAreaI5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textAreaI5.setRows(5);
        TCtabbedPane5I.add(textAreaI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

        soundToggleButtonI5.setText("Sound");
        soundToggleButtonI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonI5ActionPerformed(evt);
            }
        });
        TCtabbedPane5I.add(soundToggleButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        RButtonI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/R button.png"))); // NOI18N
        RButtonI5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RButtonI5MouseClicked(evt);
            }
        });
        TCtabbedPane5I.add(RButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, -1));

        AButtonI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/A button.png"))); // NOI18N
        AButtonI5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AButtonI5MouseClicked(evt);
            }
        });
        TCtabbedPane5I.add(AButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        TButtonI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/T button.png"))); // NOI18N
        TButtonI5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TButtonI5MouseClicked(evt);
            }
        });
        TCtabbedPane5I.add(TButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        IButtonI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/I button.png"))); // NOI18N
        IButtonI5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IButtonI5MouseClicked(evt);
            }
        });
        TCtabbedPane5I.add(IButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, -1, -1));

        UButtonI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/U button.png"))); // NOI18N
        UButtonI5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UButtonI5MouseClicked(evt);
            }
        });
        TCtabbedPane5I.add(UButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        GButtonI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/G button.png"))); // NOI18N
        GButtonI5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GButtonI5MouseClicked(evt);
            }
        });
        TCtabbedPane5I.add(GButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        returnButtonI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/back button.png"))); // NOI18N
        returnButtonI5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonI5MouseClicked(evt);
            }
        });
        TCtabbedPane5I.add(returnButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        nextButtonI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_Letters/next button.png"))); // NOI18N
        nextButtonI5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonI5MouseClicked(evt);
            }
        });
        TCtabbedPane5I.add(nextButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, -1, -1));

        iconT5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/GUITAR.png"))); // NOI18N
        iconT5.setPreferredSize(new java.awt.Dimension(50, 15));
        TCtabbedPane5I.add(iconT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgbgbg.gif"))); // NOI18N
        TCtabbedPane5I.add(background4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 790, 590));

        ITakeChallengeJTabbedPane.addTab("tab5", TCtabbedPane5I);

        getContentPane().add(ITakeChallengeJTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -22, 790, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    String[] wordI1 = {"W", "A", "T", "C", "H"};
    String[] wordI2 = {"S", "Q", "U", "I", "R", "R", "E", "L"};
    String[] wordI3 = {"C", "A", "S", "T", "L", "E"};
    String[] wordI4 = {"D", "R", "A", "G", "O", "N"};
    String[] wordI5 = {"G", "U", "I", "T", "A", "R"};

    private void readButtonI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonI1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaI1, musicPlayer);
    }//GEN-LAST:event_readButtonI1ActionPerformed

    private void clearButtonI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonI1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaI1);
    }//GEN-LAST:event_clearButtonI1ActionPerformed

    private void soundToggleButtonI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonI1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonI1);
    }//GEN-LAST:event_soundToggleButtonI1ActionPerformed

    private void readButtonI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonI2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaI2, musicPlayer);
    }//GEN-LAST:event_readButtonI2ActionPerformed

    private void clearButtonI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonI2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaI2);
    }//GEN-LAST:event_clearButtonI2ActionPerformed

    private void soundToggleButtonI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonI2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonI2);
    }//GEN-LAST:event_soundToggleButtonI2ActionPerformed

    private void readButtonI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonI3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaI3, musicPlayer);
    }//GEN-LAST:event_readButtonI3ActionPerformed

    private void clearButtonI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonI3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaI3);
    }//GEN-LAST:event_clearButtonI3ActionPerformed

    private void soundToggleButtonI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonI3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonI3);
    }//GEN-LAST:event_soundToggleButtonI3ActionPerformed

    private void readButtonI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonI4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaI4, musicPlayer);
    }//GEN-LAST:event_readButtonI4ActionPerformed

    private void clearButtonI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonI4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaI4);
    }//GEN-LAST:event_clearButtonI4ActionPerformed

    private void soundToggleButtonI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonI4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonI4);
    }//GEN-LAST:event_soundToggleButtonI4ActionPerformed

    private void readButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonI5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaI5, musicPlayer);
    }//GEN-LAST:event_readButtonI5ActionPerformed

    private void clearButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonI5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaI5);
    }//GEN-LAST:event_clearButtonI5ActionPerformed

    private void soundToggleButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonI5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonI5);
    }//GEN-LAST:event_soundToggleButtonI5ActionPerformed

    private void WButtonI1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WButtonI1MouseClicked
        // TODO add your handling code here:
        textAreaI1.append(wordI1[0]);
        ButtonActions.speak(wordI1[0], soundToggleButtonI1);
    }//GEN-LAST:event_WButtonI1MouseClicked

    private void AButtonI1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AButtonI1MouseClicked
        // TODO add your handling code here:
        textAreaI1.append(wordI1[1]);
        ButtonActions.speak(wordI1[1], soundToggleButtonI1);
    }//GEN-LAST:event_AButtonI1MouseClicked

    private void TButtonI1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TButtonI1MouseClicked
        // TODO add your handling code here:
        textAreaI1.append(wordI1[2]);
        ButtonActions.speak(wordI1[2], soundToggleButtonI1);
    }//GEN-LAST:event_TButtonI1MouseClicked

    private void CButtonI1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CButtonI1MouseClicked
        // TODO add your handling code here:
        textAreaI1.append(wordI1[3]);
        ButtonActions.speak(wordI1[3], soundToggleButtonI1);
    }//GEN-LAST:event_CButtonI1MouseClicked

    private void HButtonI1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HButtonI1MouseClicked
        // TODO add your handling code here:
        textAreaI1.append(wordI1[4]);
        ButtonActions.speak(wordI1[4], soundToggleButtonI1);
    }//GEN-LAST:event_HButtonI1MouseClicked

    private void nextButtonI1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonI1MouseClicked
        // TODO add your handling code here:
        String userAnswer = textAreaI1.getText().trim();
        ButtonActions.checkAnswerAndNext(wordI1, userAnswer, ITakeChallengeJTabbedPane, textAreaI1, false);
    }//GEN-LAST:event_nextButtonI1MouseClicked

    private void returnButtonI1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonI1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new TakeChallengeAssessment().setVisible(true);
    }//GEN-LAST:event_returnButtonI1MouseClicked

    private void SButtonI2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SButtonI2MouseClicked
        // TODO add your handling code here:
        textAreaI2.append(wordI2[0]);
        ButtonActions.speak(wordI2[0], soundToggleButtonI2);
    }//GEN-LAST:event_SButtonI2MouseClicked

    private void QButtonI2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QButtonI2MouseClicked
        // TODO add your handling code here:
        textAreaI2.append(wordI2[1]);
        ButtonActions.speak(wordI2[1], soundToggleButtonI2);
    }//GEN-LAST:event_QButtonI2MouseClicked

    private void UButtonI2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UButtonI2MouseClicked
        // TODO add your handling code here:
        textAreaI2.append(wordI2[2]);
        ButtonActions.speak(wordI2[2], soundToggleButtonI2);
    }//GEN-LAST:event_UButtonI2MouseClicked

    private void IButtonI2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IButtonI2MouseClicked
        // TODO add your handling code here:
        textAreaI2.append(wordI2[3]);
        ButtonActions.speak(wordI2[3], soundToggleButtonI2);
    }//GEN-LAST:event_IButtonI2MouseClicked

    private void R1ButtonI2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_R1ButtonI2MouseClicked
        // TODO add your handling code here:
        textAreaI2.append(wordI2[4]);
        ButtonActions.speak(wordI2[4], soundToggleButtonI2);
    }//GEN-LAST:event_R1ButtonI2MouseClicked

    private void R2ButtonI2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_R2ButtonI2MouseClicked
        // TODO add your handling code here:
        textAreaI2.append(wordI2[5]);
        ButtonActions.speak(wordI2[5], soundToggleButtonI2);
    }//GEN-LAST:event_R2ButtonI2MouseClicked

    private void EButtonI2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EButtonI2MouseClicked
        // TODO add your handling code here:
        textAreaI2.append(wordI2[6]);
        ButtonActions.speak(wordI2[6], soundToggleButtonI2);
    }//GEN-LAST:event_EButtonI2MouseClicked

    private void LButtonI2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LButtonI2MouseClicked
        // TODO add your handling code here:
        textAreaI2.append(wordI2[7]);
        ButtonActions.speak(wordI2[7], soundToggleButtonI2);
    }//GEN-LAST:event_LButtonI2MouseClicked

    private void nextButtonI2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonI2MouseClicked
        // TODO add your handling code here:
        String userAnswer = textAreaI2.getText().trim();
        ButtonActions.checkAnswerAndNext(wordI2, userAnswer, ITakeChallengeJTabbedPane, textAreaI2, false);
    }//GEN-LAST:event_nextButtonI2MouseClicked

    private void CButtonI3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CButtonI3MouseClicked
        // TODO add your handling code here:
        textAreaI3.append(wordI3[0]);
        ButtonActions.speak(wordI3[0], soundToggleButtonI3);
    }//GEN-LAST:event_CButtonI3MouseClicked

    private void AButtonI3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AButtonI3MouseClicked
        // TODO add your handling code here:
        textAreaI3.append(wordI3[1]);
        ButtonActions.speak(wordI3[1], soundToggleButtonI3);
    }//GEN-LAST:event_AButtonI3MouseClicked

    private void SButtonI3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SButtonI3MouseClicked
        // TODO add your handling code here:
        textAreaI3.append(wordI3[2]);
        ButtonActions.speak(wordI3[2], soundToggleButtonI3);
    }//GEN-LAST:event_SButtonI3MouseClicked

    private void TButtonI3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TButtonI3MouseClicked
        // TODO add your handling code here:
        textAreaI3.append(wordI3[3]);
        ButtonActions.speak(wordI3[3], soundToggleButtonI3);
    }//GEN-LAST:event_TButtonI3MouseClicked

    private void LButtonI3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LButtonI3MouseClicked
        // TODO add your handling code here:
        textAreaI3.append(wordI3[4]);
        ButtonActions.speak(wordI3[4], soundToggleButtonI3);
    }//GEN-LAST:event_LButtonI3MouseClicked

    private void EButtonI3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EButtonI3MouseClicked
        // TODO add your handling code here:
        textAreaI3.append(wordI3[5]);
        ButtonActions.speak(wordI3[5], soundToggleButtonI3);
    }//GEN-LAST:event_EButtonI3MouseClicked

    private void nextButtonI3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonI3MouseClicked
        // TODO add your handling code here:
        String userAnswer = textAreaI3.getText().trim();
        ButtonActions.checkAnswerAndNext(wordI3, userAnswer, ITakeChallengeJTabbedPane, textAreaI3, false);
    }//GEN-LAST:event_nextButtonI3MouseClicked

    private void DButtonI4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DButtonI4MouseClicked
        // TODO add your handling code here:
        textAreaI4.append(wordI4[0]);
        ButtonActions.speak(wordI4[0], soundToggleButtonI4);
    }//GEN-LAST:event_DButtonI4MouseClicked

    private void RButtonI4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RButtonI4MouseClicked
        // TODO add your handling code here:
        textAreaI4.append(wordI4[1]);
        ButtonActions.speak(wordI4[1], soundToggleButtonI4);
    }//GEN-LAST:event_RButtonI4MouseClicked

    private void AButtonI4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AButtonI4MouseClicked
        // TODO add your handling code here:
        textAreaI4.append(wordI4[2]);
        ButtonActions.speak(wordI4[2], soundToggleButtonI4);
    }//GEN-LAST:event_AButtonI4MouseClicked

    private void GButtonI4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GButtonI4MouseClicked
        // TODO add your handling code here:
        textAreaI4.append(wordI4[3]);
        ButtonActions.speak(wordI4[3], soundToggleButtonI4);
    }//GEN-LAST:event_GButtonI4MouseClicked

    private void OButtonI4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OButtonI4MouseClicked
        // TODO add your handling code here:
        textAreaI4.append(wordI4[4]);
        ButtonActions.speak(wordI4[4], soundToggleButtonI4);
    }//GEN-LAST:event_OButtonI4MouseClicked

    private void NButtonI4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NButtonI4MouseClicked
        // TODO add your handling code here:
        textAreaI4.append(wordI4[5]);
        ButtonActions.speak(wordI4[5], soundToggleButtonI4);
    }//GEN-LAST:event_NButtonI4MouseClicked

    private void nextButtonI4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonI4MouseClicked
        // TODO add your handling code here:
        String userAnswer = textAreaI4.getText().trim();
        ButtonActions.checkAnswerAndNext(wordI4, userAnswer, ITakeChallengeJTabbedPane, textAreaI4, false);
    }//GEN-LAST:event_nextButtonI4MouseClicked

    private void GButtonI5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GButtonI5MouseClicked
        // TODO add your handling code here:
        textAreaI5.append(wordI5[0]);
        ButtonActions.speak(wordI5[0], soundToggleButtonI5);
    }//GEN-LAST:event_GButtonI5MouseClicked

    private void UButtonI5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UButtonI5MouseClicked
        // TODO add your handling code here:
        textAreaI5.append(wordI5[1]);
        ButtonActions.speak(wordI5[1], soundToggleButtonI5);
    }//GEN-LAST:event_UButtonI5MouseClicked

    private void IButtonI5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IButtonI5MouseClicked
        // TODO add your handling code here:
        textAreaI5.append(wordI5[2]);
        ButtonActions.speak(wordI5[2], soundToggleButtonI5);
    }//GEN-LAST:event_IButtonI5MouseClicked

    private void TButtonI5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TButtonI5MouseClicked
        // TODO add your handling code here:
        textAreaI5.append(wordI5[3]);
        ButtonActions.speak(wordI5[3], soundToggleButtonI5);
    }//GEN-LAST:event_TButtonI5MouseClicked

    private void AButtonI5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AButtonI5MouseClicked
        // TODO add your handling code here:
        textAreaI5.append(wordI5[4]);
        ButtonActions.speak(wordI5[4], soundToggleButtonI5);
    }//GEN-LAST:event_AButtonI5MouseClicked

    private void RButtonI5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RButtonI5MouseClicked
        // TODO add your handling code here:
        textAreaI5.append(wordI5[5]);
        ButtonActions.speak(wordI5[5], soundToggleButtonI5);
    }//GEN-LAST:event_RButtonI5MouseClicked

    private void nextButtonI5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonI5MouseClicked
        // TODO add your handling code here:
        String userAnswer = textAreaI5.getText().trim();
        ButtonActions.checkAnswerAndNext(wordI5, userAnswer, ITakeChallengeJTabbedPane, textAreaI5, false);
    }//GEN-LAST:event_nextButtonI5MouseClicked

    private void returnButtonI5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonI5MouseClicked
        // TODO add your handling code here:
        TakeChallengeAssessment takeChallengeAssessment = new TakeChallengeAssessment();
        takeChallengeAssessment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnButtonI5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntermediateTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntermediateTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntermediateTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntermediateTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntermediateTakeChallenge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AButtonI1;
    private javax.swing.JLabel AButtonI3;
    private javax.swing.JLabel AButtonI4;
    private javax.swing.JLabel AButtonI5;
    private javax.swing.JLabel CButtonI1;
    private javax.swing.JLabel CButtonI3;
    private javax.swing.JLabel DButtonI4;
    private javax.swing.JLabel EButtonI2;
    private javax.swing.JLabel EButtonI3;
    private javax.swing.JLabel GButtonI4;
    private javax.swing.JLabel GButtonI5;
    private javax.swing.JLabel HButtonI1;
    private javax.swing.JLabel IButtonI2;
    private javax.swing.JLabel IButtonI5;
    private javax.swing.JTabbedPane ITakeChallengeJTabbedPane;
    private javax.swing.JLabel LButtonI2;
    private javax.swing.JLabel LButtonI3;
    private javax.swing.JLabel NButtonI4;
    private javax.swing.JLabel OButtonI4;
    private javax.swing.JLabel QButtonI2;
    private javax.swing.JLabel R1ButtonI2;
    private javax.swing.JLabel R2ButtonI2;
    private javax.swing.JLabel RButtonI4;
    private javax.swing.JLabel RButtonI5;
    private javax.swing.JLabel SButtonI2;
    private javax.swing.JLabel SButtonI3;
    private javax.swing.JLabel TButtonI1;
    private javax.swing.JLabel TButtonI3;
    private javax.swing.JLabel TButtonI5;
    private javax.swing.JPanel TCtabbedPane1I;
    private javax.swing.JPanel TCtabbedPane2I;
    private javax.swing.JPanel TCtabbedPane3I;
    private javax.swing.JPanel TCtabbedPane4I;
    private javax.swing.JPanel TCtabbedPane5I;
    private javax.swing.JLabel UButtonI2;
    private javax.swing.JLabel UButtonI5;
    private javax.swing.JLabel WButtonI1;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JButton clearButtonI1;
    private javax.swing.JButton clearButtonI2;
    private javax.swing.JButton clearButtonI3;
    private javax.swing.JButton clearButtonI4;
    private javax.swing.JButton clearButtonI5;
    private javax.swing.JButton hintButtonI1;
    private javax.swing.JButton hintButtonI2;
    private javax.swing.JButton hintButtonI3;
    private javax.swing.JButton hintButtonI4;
    private javax.swing.JButton hintButtonI5;
    private javax.swing.JLabel iconT1;
    private javax.swing.JLabel iconT2;
    private javax.swing.JLabel iconT3;
    private javax.swing.JLabel iconT4;
    private javax.swing.JLabel iconT5;
    private javax.swing.JLabel instructionLabelTC1;
    private javax.swing.JLabel instructionLabelTC2;
    private javax.swing.JLabel instructionLabelTC6;
    private javax.swing.JLabel instructionLabelTC7;
    private javax.swing.JLabel instructionLabelTC8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nextButtonI1;
    private javax.swing.JLabel nextButtonI2;
    private javax.swing.JLabel nextButtonI3;
    private javax.swing.JLabel nextButtonI4;
    private javax.swing.JLabel nextButtonI5;
    private javax.swing.JButton readButtonI1;
    private javax.swing.JButton readButtonI2;
    private javax.swing.JButton readButtonI3;
    private javax.swing.JButton readButtonI4;
    private javax.swing.JButton readButtonI5;
    private javax.swing.JLabel returnButtonI1;
    private javax.swing.JLabel returnButtonI5;
    private javax.swing.JToggleButton soundToggleButtonI1;
    private javax.swing.JToggleButton soundToggleButtonI2;
    private javax.swing.JToggleButton soundToggleButtonI3;
    private javax.swing.JToggleButton soundToggleButtonI4;
    private javax.swing.JToggleButton soundToggleButtonI5;
    private javax.swing.JTextArea textAreaI1;
    private javax.swing.JTextArea textAreaI2;
    private javax.swing.JTextArea textAreaI3;
    private javax.swing.JTextArea textAreaI4;
    private javax.swing.JTextArea textAreaI5;
    // End of variables declaration//GEN-END:variables
}
