/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Core.AssessmentPage.TakeChallengeModeOfDifficulty;

import Core.Actions.ButtonActions;
import Core.AssessmentPage.TakeChallengeAssessment;

import javax.swing.*;

/**
 * @author Marc
 */
public class IntermediateTakeChallenge extends javax.swing.JFrame {

    /**
     * Creates new form IntermediateTakeChallenge
     */
    public IntermediateTakeChallenge() {
        initComponents();

        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/WATCH.png"));
        ImageIcon icon = new ImageIcon(originalIcon.getImage().getScaledInstance(iconT1.getWidth(), iconT1.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT1.setIcon(icon);

        ImageIcon originalIcon2 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/SQUIRREL.png"));
        ImageIcon icon2 = new ImageIcon(originalIcon2.getImage().getScaledInstance(iconT2.getWidth(), iconT2.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT2.setIcon(icon2);

        ImageIcon originalIcon3 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/CASTLE.png"));
        ImageIcon icon3 = new ImageIcon(originalIcon3.getImage().getScaledInstance(iconT3.getWidth(), iconT3.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT3.setIcon(icon3);

        ImageIcon originalIcon4 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/DRAGON.png"));
        ImageIcon icon4 = new ImageIcon(originalIcon4.getImage().getScaledInstance(iconT4.getWidth(), iconT4.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT4.setIcon(icon4);

        ImageIcon originalIcon5 = new ImageIcon(getClass().getResource("/Assessment/Take Challenge/GUITAR.png"));
        ImageIcon icon5 = new ImageIcon(originalIcon5.getImage().getScaledInstance(iconT5.getWidth(), iconT5.getHeight(), java.awt.Image.SCALE_SMOOTH));
        iconT5.setIcon(icon5);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                ITakeChallengeJTabbedPane = new javax.swing.JTabbedPane();
                TCtabbedPane1I = new javax.swing.JPanel();
                instructionLabelTC1 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                readButtonI1 = new javax.swing.JButton();
                clearButtonI1 = new javax.swing.JButton();
                hintButtonI1 = new javax.swing.JButton();
                AButtonI1 = new javax.swing.JButton();
                WButtonI1 = new javax.swing.JButton();
                TButtonI1 = new javax.swing.JButton();
                HButtonI1 = new javax.swing.JButton();
                nextButtonI1 = new javax.swing.JButton();
                textAreaI1 = new javax.swing.JTextArea();
                soundToggleButtonI1 = new javax.swing.JToggleButton();
                returnButtonI1 = new javax.swing.JButton();
                CButtonI1 = new javax.swing.JButton();
                iconT1 = new javax.swing.JLabel();
                TCtabbedPane2I = new javax.swing.JPanel();
                instructionLabelTC2 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                readButtonI2 = new javax.swing.JButton();
                clearButtonI2 = new javax.swing.JButton();
                hintButtonI2 = new javax.swing.JButton();
                QButtonI2 = new javax.swing.JButton();
                LButtonI2 = new javax.swing.JButton();
                EButtonI2 = new javax.swing.JButton();
                R1ButtonI2 = new javax.swing.JButton();
                nextButtonI2 = new javax.swing.JButton();
                textAreaI2 = new javax.swing.JTextArea();
                soundToggleButtonI2 = new javax.swing.JToggleButton();
                UButtonI2 = new javax.swing.JButton();
                SButtonI2 = new javax.swing.JButton();
                R2ButtonI2 = new javax.swing.JButton();
                IButtonI2 = new javax.swing.JButton();
                iconT2 = new javax.swing.JLabel();
                TCtabbedPane3I = new javax.swing.JPanel();
                instructionLabelTC6 = new javax.swing.JLabel();
                jPanel11 = new javax.swing.JPanel();
                readButtonI3 = new javax.swing.JButton();
                clearButtonI3 = new javax.swing.JButton();
                hintButtonI3 = new javax.swing.JButton();
                EButtonI3 = new javax.swing.JButton();
                AButtonI3 = new javax.swing.JButton();
                SButtonI3 = new javax.swing.JButton();
                TButtonI3 = new javax.swing.JButton();
                nextButtonI3 = new javax.swing.JButton();
                textAreaI3 = new javax.swing.JTextArea();
                soundToggleButtonI3 = new javax.swing.JToggleButton();
                LButtonI3 = new javax.swing.JButton();
                CButtonI3 = new javax.swing.JButton();
                iconT3 = new javax.swing.JLabel();
                TCtabbedPane4I = new javax.swing.JPanel();
                instructionLabelTC7 = new javax.swing.JLabel();
                jPanel13 = new javax.swing.JPanel();
                readButtonI4 = new javax.swing.JButton();
                clearButtonI4 = new javax.swing.JButton();
                hintButtonI4 = new javax.swing.JButton();
                NButtonI4 = new javax.swing.JButton();
                RButtonI4 = new javax.swing.JButton();
                DButtonI4 = new javax.swing.JButton();
                OButtonI4 = new javax.swing.JButton();
                nextButtonI4 = new javax.swing.JButton();
                textAreaI4 = new javax.swing.JTextArea();
                soundToggleButtonI4 = new javax.swing.JToggleButton();
                AButtonI4 = new javax.swing.JButton();
                GButtonI4 = new javax.swing.JButton();
                iconT4 = new javax.swing.JLabel();
                TCtabbedPane5I = new javax.swing.JPanel();
                instructionLabelTC8 = new javax.swing.JLabel();
                jPanel15 = new javax.swing.JPanel();
                readButtonI5 = new javax.swing.JButton();
                clearButtonI5 = new javax.swing.JButton();
                hintButtonI5 = new javax.swing.JButton();
                GButtonI5 = new javax.swing.JButton();
                TButtonI5 = new javax.swing.JButton();
                IButtonI5 = new javax.swing.JButton();
                UButtonI5 = new javax.swing.JButton();
                nextButtonI5 = new javax.swing.JButton();
                textAreaI5 = new javax.swing.JTextArea();
                soundToggleButtonI5 = new javax.swing.JToggleButton();
                RButtonI5 = new javax.swing.JButton();
                AButtonI5 = new javax.swing.JButton();
                returnButtonI5 = new javax.swing.JButton();
                iconT5 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                TCtabbedPane1I.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane1I.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC1.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC1.setText("Guess the Word");
                TCtabbedPane1I.add(instructionLabelTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane1I.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonI1.setText("Read");
                readButtonI1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonI1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1I.add(readButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 73, -1));

                clearButtonI1.setText("Clear");
                clearButtonI1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonI1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1I.add(clearButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 73, -1));

                hintButtonI1.setText("Hint");
                TCtabbedPane1I.add(hintButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 73, -1));

                AButtonI1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                AButtonI1.setText("A");
                AButtonI1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AButtonI1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1I.add(AButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 98, 67));

                WButtonI1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                WButtonI1.setText("W");
                WButtonI1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                WButtonI1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1I.add(WButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 98, 67));

                TButtonI1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                TButtonI1.setText("T");
                TButtonI1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TButtonI1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1I.add(TButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 98, 67));

                HButtonI1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                HButtonI1.setText("H");
                HButtonI1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                HButtonI1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1I.add(HButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 98, 67));

                nextButtonI1.setText("Next");
                nextButtonI1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonI1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1I.add(nextButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                textAreaI1.setEditable(false);
                textAreaI1.setColumns(20);
                textAreaI1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaI1.setRows(5);
                TCtabbedPane1I.add(textAreaI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 320, 70));

                soundToggleButtonI1.setText("Sound");
                soundToggleButtonI1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonI1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1I.add(soundToggleButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                returnButtonI1.setText("Return");
                returnButtonI1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                returnButtonI1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1I.add(returnButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 485, 73, -1));

                CButtonI1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                CButtonI1.setText("C");
                CButtonI1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CButtonI1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1I.add(CButtonI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 98, 67));

                iconT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/WATCH.png"))); // NOI18N
                iconT1.setPreferredSize(new java.awt.Dimension(50, 15));
                TCtabbedPane1I.add(iconT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

                ITakeChallengeJTabbedPane.addTab("tab1", TCtabbedPane1I);

                TCtabbedPane2I.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane2I.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC2.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC2.setText("Guess the Word");
                TCtabbedPane2I.add(instructionLabelTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane2I.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonI2.setText("Read");
                readButtonI2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonI2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2I.add(readButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonI2.setText("Clear");
                clearButtonI2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonI2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2I.add(clearButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonI2.setText("Hint");
                TCtabbedPane2I.add(hintButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                QButtonI2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                QButtonI2.setText("Q");
                QButtonI2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                QButtonI2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2I.add(QButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 98, 67));

                LButtonI2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                LButtonI2.setText("L");
                LButtonI2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LButtonI2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2I.add(LButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 98, 67));

                EButtonI2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                EButtonI2.setText("E");
                EButtonI2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EButtonI2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2I.add(EButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 98, 67));

                R1ButtonI2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                R1ButtonI2.setText("R");
                R1ButtonI2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                R1ButtonI2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2I.add(R1ButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 98, 67));

                nextButtonI2.setText("Next");
                nextButtonI2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonI2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2I.add(nextButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                textAreaI2.setEditable(false);
                textAreaI2.setColumns(20);
                textAreaI2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaI2.setRows(5);
                TCtabbedPane2I.add(textAreaI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

                soundToggleButtonI2.setText("Sound");
                soundToggleButtonI2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonI2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2I.add(soundToggleButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                UButtonI2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                UButtonI2.setText("U");
                UButtonI2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                UButtonI2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2I.add(UButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 98, 67));

                SButtonI2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                SButtonI2.setText("S");
                SButtonI2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                SButtonI2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2I.add(SButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 98, 67));

                R2ButtonI2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                R2ButtonI2.setText("R");
                R2ButtonI2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                R2ButtonI2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2I.add(R2ButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 98, 67));

                IButtonI2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                IButtonI2.setText("I");
                IButtonI2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                IButtonI2ActionPerformed(evt);
                        }
                });
                TCtabbedPane2I.add(IButtonI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 98, 67));

                iconT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/SQUIRREL.png"))); // NOI18N
                iconT2.setPreferredSize(new java.awt.Dimension(50, 15));
                TCtabbedPane2I.add(iconT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

                ITakeChallengeJTabbedPane.addTab("tab2", TCtabbedPane2I);

                TCtabbedPane3I.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane3I.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC6.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC6.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC6.setText("Guess the Word");
                TCtabbedPane3I.add(instructionLabelTC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
                jPanel11.setLayout(jPanel11Layout);
                jPanel11Layout.setHorizontalGroup(
                        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel11Layout.setVerticalGroup(
                        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane3I.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonI3.setText("Read");
                readButtonI3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonI3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3I.add(readButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonI3.setText("Clear");
                clearButtonI3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonI3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3I.add(clearButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonI3.setText("Hint");
                TCtabbedPane3I.add(hintButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                EButtonI3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                EButtonI3.setText("E");
                EButtonI3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EButtonI3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3I.add(EButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 98, 67));

                AButtonI3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                AButtonI3.setText("A");
                AButtonI3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AButtonI3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3I.add(AButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 98, 67));

                SButtonI3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                SButtonI3.setText("S");
                SButtonI3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                SButtonI3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3I.add(SButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 98, 67));

                TButtonI3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                TButtonI3.setText("T");
                TButtonI3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TButtonI3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3I.add(TButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 98, 67));

                nextButtonI3.setText("Next");
                nextButtonI3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonI3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3I.add(nextButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                textAreaI3.setEditable(false);
                textAreaI3.setColumns(20);
                textAreaI3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaI3.setRows(5);
                TCtabbedPane3I.add(textAreaI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

                soundToggleButtonI3.setText("Sound");
                soundToggleButtonI3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonI3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3I.add(soundToggleButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                LButtonI3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                LButtonI3.setText("L");
                LButtonI3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LButtonI3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3I.add(LButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 98, 67));

                CButtonI3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                CButtonI3.setText("C");
                CButtonI3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CButtonI3ActionPerformed(evt);
                        }
                });
                TCtabbedPane3I.add(CButtonI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 98, 67));

                iconT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/CASTLE.png"))); // NOI18N
                iconT3.setPreferredSize(new java.awt.Dimension(50, 15));
                TCtabbedPane3I.add(iconT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

                ITakeChallengeJTabbedPane.addTab("tab3", TCtabbedPane3I);

                TCtabbedPane4I.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane4I.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC7.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC7.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC7.setText("Guess the Word");
                TCtabbedPane4I.add(instructionLabelTC7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
                jPanel13.setLayout(jPanel13Layout);
                jPanel13Layout.setHorizontalGroup(
                        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel13Layout.setVerticalGroup(
                        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane4I.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonI4.setText("Read");
                readButtonI4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonI4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4I.add(readButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonI4.setText("Clear");
                clearButtonI4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonI4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4I.add(clearButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonI4.setText("Hint");
                TCtabbedPane4I.add(hintButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                NButtonI4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                NButtonI4.setText("N");
                NButtonI4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                NButtonI4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4I.add(NButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 98, 67));

                RButtonI4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                RButtonI4.setText("R");
                RButtonI4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                RButtonI4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4I.add(RButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 98, 67));

                DButtonI4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                DButtonI4.setText("D");
                DButtonI4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                DButtonI4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4I.add(DButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 98, 67));

                OButtonI4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                OButtonI4.setText("O");
                OButtonI4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                OButtonI4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4I.add(OButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 98, 67));

                nextButtonI4.setText("Next");
                nextButtonI4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonI4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4I.add(nextButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                textAreaI4.setEditable(false);
                textAreaI4.setColumns(20);
                textAreaI4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaI4.setRows(5);
                TCtabbedPane4I.add(textAreaI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

                soundToggleButtonI4.setText("Sound");
                soundToggleButtonI4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonI4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4I.add(soundToggleButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                AButtonI4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                AButtonI4.setText("A");
                AButtonI4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AButtonI4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4I.add(AButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 98, 67));

                GButtonI4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                GButtonI4.setText("G");
                GButtonI4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                GButtonI4ActionPerformed(evt);
                        }
                });
                TCtabbedPane4I.add(GButtonI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 98, 67));

                iconT4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/DRAGON.png"))); // NOI18N
                iconT4.setPreferredSize(new java.awt.Dimension(50, 15));
                TCtabbedPane4I.add(iconT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

                ITakeChallengeJTabbedPane.addTab("tab4", TCtabbedPane4I);

                TCtabbedPane5I.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane5I.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC8.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC8.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC8.setText("Guess the Word");
                TCtabbedPane5I.add(instructionLabelTC8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
                jPanel15.setLayout(jPanel15Layout);
                jPanel15Layout.setHorizontalGroup(
                        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel15Layout.setVerticalGroup(
                        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane5I.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonI5.setText("Read");
                readButtonI5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonI5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5I.add(readButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonI5.setText("Clear");
                clearButtonI5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonI5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5I.add(clearButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonI5.setText("Hint");
                TCtabbedPane5I.add(hintButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                GButtonI5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                GButtonI5.setText("G");
                GButtonI5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                GButtonI5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5I.add(GButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 98, 67));

                TButtonI5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                TButtonI5.setText("T");
                TButtonI5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TButtonI5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5I.add(TButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 98, 67));

                IButtonI5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                IButtonI5.setText("I");
                IButtonI5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                IButtonI5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5I.add(IButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 98, 67));

                UButtonI5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                UButtonI5.setText("U");
                UButtonI5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                UButtonI5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5I.add(UButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 98, 67));

                nextButtonI5.setText("Next");
                nextButtonI5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonI5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5I.add(nextButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                textAreaI5.setEditable(false);
                textAreaI5.setColumns(20);
                textAreaI5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaI5.setRows(5);
                TCtabbedPane5I.add(textAreaI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 320, 80));

                soundToggleButtonI5.setText("Sound");
                soundToggleButtonI5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonI5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5I.add(soundToggleButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                RButtonI5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                RButtonI5.setText("R");
                RButtonI5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                RButtonI5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5I.add(RButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 98, 67));

                AButtonI5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                AButtonI5.setText("A");
                AButtonI5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AButtonI5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5I.add(AButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 98, 67));

                returnButtonI5.setText("Return");
                returnButtonI5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                returnButtonI5ActionPerformed(evt);
                        }
                });
                TCtabbedPane5I.add(returnButtonI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 485, 73, -1));

                iconT5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assessment/Take Challenge/GUITAR.png"))); // NOI18N
                iconT5.setPreferredSize(new java.awt.Dimension(50, 15));
                TCtabbedPane5I.add(iconT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 439, 209));

                ITakeChallengeJTabbedPane.addTab("tab5", TCtabbedPane5I);

                getContentPane().add(ITakeChallengeJTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -22, 780, 570));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    String[] wordI1 = {"W", "A", "T", "C", "H"};
    String[] wordI2 = {"S", "Q", "U", "I", "R", "R", "E", "L"};
    String[] wordI3 = {"C", "A", "S", "T", "L", "E"};
    String[] wordI4 = {"D", "R", "A", "G", "O", "N"};
    String[] wordI5 = {"G", "U", "I", "T", "A", "R"};

    private void readButtonI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonI1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaI1);
    }//GEN-LAST:event_readButtonI1ActionPerformed

    private void clearButtonI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonI1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaI1);
    }//GEN-LAST:event_clearButtonI1ActionPerformed

    private void AButtonI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonI1ActionPerformed
        // TODO add your handling code here:
        textAreaI1.append(wordI1[1]);
        ButtonActions.speak(wordI1[1], soundToggleButtonI1);
    }//GEN-LAST:event_AButtonI1ActionPerformed

    private void WButtonI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WButtonI1ActionPerformed
        // TODO add your handling code here:
        textAreaI1.append(wordI1[0]);
        ButtonActions.speak(wordI1[0], soundToggleButtonI1);
    }//GEN-LAST:event_WButtonI1ActionPerformed

    private void TButtonI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TButtonI1ActionPerformed
        // TODO add your handling code here:
        textAreaI1.append(wordI1[2]);
        ButtonActions.speak(wordI1[2], soundToggleButtonI1);
    }//GEN-LAST:event_TButtonI1ActionPerformed

    private void HButtonI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HButtonI1ActionPerformed
        // TODO add your handling code here:
        textAreaI1.append(wordI1[4]);
        ButtonActions.speak(wordI1[4], soundToggleButtonI1);
    }//GEN-LAST:event_HButtonI1ActionPerformed

    private void nextButtonI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonI1ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaI1.getText().trim();
        ButtonActions.checkAnswerAndNext(wordI1, userAnswer, ITakeChallengeJTabbedPane, textAreaI1, false);
    }//GEN-LAST:event_nextButtonI1ActionPerformed

    private void soundToggleButtonI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonI1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonI1);
    }//GEN-LAST:event_soundToggleButtonI1ActionPerformed

    private void returnButtonI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonI1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TakeChallengeAssessment().setVisible(true);
    }//GEN-LAST:event_returnButtonI1ActionPerformed

    private void CButtonI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CButtonI1ActionPerformed
        // TODO add your handling code here:
        textAreaI1.append(wordI1[3]);
        ButtonActions.speak(wordI1[3], soundToggleButtonI1);
    }//GEN-LAST:event_CButtonI1ActionPerformed

    private void readButtonI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonI2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaI2);
    }//GEN-LAST:event_readButtonI2ActionPerformed

    private void clearButtonI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonI2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaI2);
    }//GEN-LAST:event_clearButtonI2ActionPerformed

    private void QButtonI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QButtonI2ActionPerformed
        // TODO add your handling code here:
        textAreaI2.append(wordI2[1]);
        ButtonActions.speak(wordI2[1], soundToggleButtonI2);
    }//GEN-LAST:event_QButtonI2ActionPerformed

    private void LButtonI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButtonI2ActionPerformed
        // TODO add your handling code here:
        textAreaI2.append(wordI2[7]);
        ButtonActions.speak(wordI2[7], soundToggleButtonI2);
    }//GEN-LAST:event_LButtonI2ActionPerformed

    private void EButtonI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonI2ActionPerformed
        // TODO add your handling code here:
        textAreaI2.append(wordI2[6]);
        ButtonActions.speak(wordI2[6], soundToggleButtonI2);
    }//GEN-LAST:event_EButtonI2ActionPerformed

    private void R1ButtonI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ButtonI2ActionPerformed
        // TODO add your handling code here:
        textAreaI2.append(wordI2[4]);
        ButtonActions.speak(wordI2[4], soundToggleButtonI2);
    }//GEN-LAST:event_R1ButtonI2ActionPerformed

    private void nextButtonI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonI2ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaI2.getText().trim();
        ButtonActions.checkAnswerAndNext(wordI2, userAnswer, ITakeChallengeJTabbedPane, textAreaI2, false);
    }//GEN-LAST:event_nextButtonI2ActionPerformed

    private void soundToggleButtonI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonI2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonI2);
    }//GEN-LAST:event_soundToggleButtonI2ActionPerformed

    private void UButtonI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UButtonI2ActionPerformed
        // TODO add your handling code here:
        textAreaI2.append(wordI2[2]);
        ButtonActions.speak(wordI2[2], soundToggleButtonI2);
    }//GEN-LAST:event_UButtonI2ActionPerformed

    private void SButtonI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SButtonI2ActionPerformed
        // TODO add your handling code here:
        textAreaI2.append(wordI2[0]);
        ButtonActions.speak(wordI2[0], soundToggleButtonI2);
    }//GEN-LAST:event_SButtonI2ActionPerformed

    private void R2ButtonI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ButtonI2ActionPerformed
        // TODO add your handling code here:
        textAreaI2.append(wordI2[5]);
        ButtonActions.speak(wordI2[5], soundToggleButtonI2);
    }//GEN-LAST:event_R2ButtonI2ActionPerformed

    private void IButtonI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IButtonI2ActionPerformed
        // TODO add your handling code here:
        textAreaI2.append(wordI2[3]);
        ButtonActions.speak(wordI2[3], soundToggleButtonI2);
    }//GEN-LAST:event_IButtonI2ActionPerformed

    private void readButtonI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonI3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaI3);
    }//GEN-LAST:event_readButtonI3ActionPerformed

    private void clearButtonI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonI3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaI3);
    }//GEN-LAST:event_clearButtonI3ActionPerformed

    private void EButtonI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonI3ActionPerformed
        // TODO add your handling code here:
        textAreaI3.append(wordI3[5]);
        ButtonActions.speak(wordI3[5], soundToggleButtonI3);
    }//GEN-LAST:event_EButtonI3ActionPerformed

    private void AButtonI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonI3ActionPerformed
        // TODO add your handling code here:
        textAreaI3.append(wordI3[1]);
        ButtonActions.speak(wordI3[1], soundToggleButtonI3);
    }//GEN-LAST:event_AButtonI3ActionPerformed

    private void SButtonI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SButtonI3ActionPerformed
        // TODO add your handling code here:
        textAreaI3.append(wordI3[2]);
        ButtonActions.speak(wordI3[2], soundToggleButtonI3);
    }//GEN-LAST:event_SButtonI3ActionPerformed

    private void TButtonI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TButtonI3ActionPerformed
        // TODO add your handling code here:
        textAreaI3.append(wordI3[3]);
        ButtonActions.speak(wordI3[3], soundToggleButtonI3);
    }//GEN-LAST:event_TButtonI3ActionPerformed

    private void nextButtonI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonI3ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaI3.getText().trim();
        ButtonActions.checkAnswerAndNext(wordI3, userAnswer, ITakeChallengeJTabbedPane, textAreaI3, false);
    }//GEN-LAST:event_nextButtonI3ActionPerformed

    private void soundToggleButtonI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonI3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonI3);
    }//GEN-LAST:event_soundToggleButtonI3ActionPerformed

    private void LButtonI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButtonI3ActionPerformed
        // TODO add your handling code here:
        textAreaI3.append(wordI3[4]);
        ButtonActions.speak(wordI3[4], soundToggleButtonI3);
    }//GEN-LAST:event_LButtonI3ActionPerformed

    private void CButtonI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CButtonI3ActionPerformed
        // TODO add your handling code here:
        textAreaI3.append(wordI3[0]);
        ButtonActions.speak(wordI3[0], soundToggleButtonI3);
    }//GEN-LAST:event_CButtonI3ActionPerformed

    private void readButtonI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonI4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaI4);
    }//GEN-LAST:event_readButtonI4ActionPerformed

    private void clearButtonI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonI4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaI4);
    }//GEN-LAST:event_clearButtonI4ActionPerformed

    private void NButtonI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NButtonI4ActionPerformed
        // TODO add your handling code here:
        textAreaI4.append(wordI4[5]);
        ButtonActions.speak(wordI4[5], soundToggleButtonI4);
    }//GEN-LAST:event_NButtonI4ActionPerformed

    private void RButtonI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonI4ActionPerformed
        // TODO add your handling code here:
        textAreaI4.append(wordI4[1]);
        ButtonActions.speak(wordI4[1], soundToggleButtonI4);
    }//GEN-LAST:event_RButtonI4ActionPerformed

    private void DButtonI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DButtonI4ActionPerformed
        // TODO add your handling code here:
        textAreaI4.append(wordI4[0]);
        ButtonActions.speak(wordI4[0], soundToggleButtonI4);
    }//GEN-LAST:event_DButtonI4ActionPerformed

    private void OButtonI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OButtonI4ActionPerformed
        // TODO add your handling code here:
        textAreaI4.append(wordI4[4]);
        ButtonActions.speak(wordI4[4], soundToggleButtonI4);
    }//GEN-LAST:event_OButtonI4ActionPerformed

    private void nextButtonI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonI4ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaI4.getText().trim();
        ButtonActions.checkAnswerAndNext(wordI4, userAnswer, ITakeChallengeJTabbedPane, textAreaI4, false);
    }//GEN-LAST:event_nextButtonI4ActionPerformed

    private void soundToggleButtonI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonI4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonI4);
    }//GEN-LAST:event_soundToggleButtonI4ActionPerformed

    private void AButtonI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonI4ActionPerformed
        // TODO add your handling code here:
        textAreaI4.append(wordI4[2]);
        ButtonActions.speak(wordI4[2], soundToggleButtonI4);
    }//GEN-LAST:event_AButtonI4ActionPerformed

    private void GButtonI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GButtonI4ActionPerformed
        // TODO add your handling code here:
        textAreaI4.append(wordI4[3]);
        ButtonActions.speak(wordI4[3], soundToggleButtonI4);
    }//GEN-LAST:event_GButtonI4ActionPerformed

    private void readButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonI5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaI5);
    }//GEN-LAST:event_readButtonI5ActionPerformed

    private void clearButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonI5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaI5);
    }//GEN-LAST:event_clearButtonI5ActionPerformed

    private void GButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GButtonI5ActionPerformed
        // TODO add your handling code here:
        textAreaI5.append(wordI5[0]);
        ButtonActions.speak(wordI5[0], soundToggleButtonI5);
    }//GEN-LAST:event_GButtonI5ActionPerformed

    private void TButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TButtonI5ActionPerformed
        // TODO add your handling code here:
        textAreaI5.append(wordI5[3]);
        ButtonActions.speak(wordI5[3], soundToggleButtonI5);
    }//GEN-LAST:event_TButtonI5ActionPerformed

    private void IButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IButtonI5ActionPerformed
        // TODO add your handling code here:
        textAreaI5.append(wordI5[2]);
        ButtonActions.speak(wordI5[2], soundToggleButtonI5);
    }//GEN-LAST:event_IButtonI5ActionPerformed

    private void UButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UButtonI5ActionPerformed
        // TODO add your handling code here:
        textAreaI5.append(wordI5[1]);
        ButtonActions.speak(wordI5[1], soundToggleButtonI5);
    }//GEN-LAST:event_UButtonI5ActionPerformed

    private void nextButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonI5ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaI5.getText().trim();
        ButtonActions.checkAnswerAndNext(wordI5, userAnswer, ITakeChallengeJTabbedPane, textAreaI5, false);
    }//GEN-LAST:event_nextButtonI5ActionPerformed

    private void soundToggleButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonI5ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonI5);
    }//GEN-LAST:event_soundToggleButtonI5ActionPerformed

    private void RButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonI5ActionPerformed
        // TODO add your handling code here:
        textAreaI5.append(wordI5[5]);
        ButtonActions.speak(wordI5[5], soundToggleButtonI5);
    }//GEN-LAST:event_RButtonI5ActionPerformed

    private void AButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonI5ActionPerformed
        // TODO add your handling code here:
        textAreaI5.append(wordI5[4]);
        ButtonActions.speak(wordI5[4], soundToggleButtonI5);
    }//GEN-LAST:event_AButtonI5ActionPerformed

    private void returnButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonI5ActionPerformed
        // TODO add your handling code here:
        TakeChallengeAssessment takeChallengeAssessment = new TakeChallengeAssessment();
        takeChallengeAssessment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnButtonI5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntermediateTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntermediateTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntermediateTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntermediateTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntermediateTakeChallenge().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton AButtonI1;
        private javax.swing.JButton AButtonI3;
        private javax.swing.JButton AButtonI4;
        private javax.swing.JButton AButtonI5;
        private javax.swing.JButton CButtonI1;
        private javax.swing.JButton CButtonI3;
        private javax.swing.JButton DButtonI4;
        private javax.swing.JButton EButtonI2;
        private javax.swing.JButton EButtonI3;
        private javax.swing.JButton GButtonI4;
        private javax.swing.JButton GButtonI5;
        private javax.swing.JButton HButtonI1;
        private javax.swing.JButton IButtonI2;
        private javax.swing.JButton IButtonI5;
        private javax.swing.JTabbedPane ITakeChallengeJTabbedPane;
        private javax.swing.JButton LButtonI2;
        private javax.swing.JButton LButtonI3;
        private javax.swing.JButton NButtonI4;
        private javax.swing.JButton OButtonI4;
        private javax.swing.JButton QButtonI2;
        private javax.swing.JButton R1ButtonI2;
        private javax.swing.JButton R2ButtonI2;
        private javax.swing.JButton RButtonI4;
        private javax.swing.JButton RButtonI5;
        private javax.swing.JButton SButtonI2;
        private javax.swing.JButton SButtonI3;
        private javax.swing.JButton TButtonI1;
        private javax.swing.JButton TButtonI3;
        private javax.swing.JButton TButtonI5;
        private javax.swing.JPanel TCtabbedPane1I;
        private javax.swing.JPanel TCtabbedPane2I;
        private javax.swing.JPanel TCtabbedPane3I;
        private javax.swing.JPanel TCtabbedPane4I;
        private javax.swing.JPanel TCtabbedPane5I;
        private javax.swing.JButton UButtonI2;
        private javax.swing.JButton UButtonI5;
        private javax.swing.JButton WButtonI1;
        private javax.swing.JButton clearButtonI1;
        private javax.swing.JButton clearButtonI2;
        private javax.swing.JButton clearButtonI3;
        private javax.swing.JButton clearButtonI4;
        private javax.swing.JButton clearButtonI5;
        private javax.swing.JButton hintButtonI1;
        private javax.swing.JButton hintButtonI2;
        private javax.swing.JButton hintButtonI3;
        private javax.swing.JButton hintButtonI4;
        private javax.swing.JButton hintButtonI5;
        private javax.swing.JLabel iconT1;
        private javax.swing.JLabel iconT2;
        private javax.swing.JLabel iconT3;
        private javax.swing.JLabel iconT4;
        private javax.swing.JLabel iconT5;
        private javax.swing.JLabel instructionLabelTC1;
        private javax.swing.JLabel instructionLabelTC2;
        private javax.swing.JLabel instructionLabelTC6;
        private javax.swing.JLabel instructionLabelTC7;
        private javax.swing.JLabel instructionLabelTC8;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel11;
        private javax.swing.JPanel jPanel13;
        private javax.swing.JPanel jPanel15;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JButton nextButtonI1;
        private javax.swing.JButton nextButtonI2;
        private javax.swing.JButton nextButtonI3;
        private javax.swing.JButton nextButtonI4;
        private javax.swing.JButton nextButtonI5;
        private javax.swing.JButton readButtonI1;
        private javax.swing.JButton readButtonI2;
        private javax.swing.JButton readButtonI3;
        private javax.swing.JButton readButtonI4;
        private javax.swing.JButton readButtonI5;
        private javax.swing.JButton returnButtonI1;
        private javax.swing.JButton returnButtonI5;
        private javax.swing.JToggleButton soundToggleButtonI1;
        private javax.swing.JToggleButton soundToggleButtonI2;
        private javax.swing.JToggleButton soundToggleButtonI3;
        private javax.swing.JToggleButton soundToggleButtonI4;
        private javax.swing.JToggleButton soundToggleButtonI5;
        private javax.swing.JTextArea textAreaI1;
        private javax.swing.JTextArea textAreaI2;
        private javax.swing.JTextArea textAreaI3;
        private javax.swing.JTextArea textAreaI4;
        private javax.swing.JTextArea textAreaI5;
        // End of variables declaration//GEN-END:variables
}
